### ISSUE TITLE
Pasted schematic is different to the created one

### ISSUE THREAD

**Issue by JakkitDE** [Iridium-Development/IridiumSkyblock#100]
Here is the created schematic file. The diamond block is the calculated and exact middle:
![2021-05-29_20 31 54](https://user-images.githubusercontent.com/20011543/120081540-6f62d780-c0be-11eb-9338-9857f7893b11.png)
After creating the island based on the created schematic, the island looks following:
![2021-05-29_20 34 32](https://user-images.githubusercontent.com/20011543/120081571-96210e00-c0be-11eb-8d38-ab26041161f4.png)
Here the diamond block (calculated middle) flies over the void. Every player there falls into the void after creating a new island.

**Comment by PeachesMLG** [comment]
This isnt a bug, you can change the default spawn position using the xyz variables, Ill add xyz offsets that allow you to change where the schematic is pasted

**Comment by dlsf** [comment]
This happens because the schematics are automatically shrunken so they don't contain extra air and later centered.
