### ISSUE TITLE
Unlock new island schematics

### ISSUE THREAD

**Issue by joshwenke** [Iridium-Development/IridiumSkyblock#102]
It would be great to be able to unlock new island schematics as you progress through Iridium.

For example, you could unlock an island with a certain amount of money or crystals. You could also unlock an island through a permission node, to help hook in with other plugins.

**Comment by PeachesMLG** [comment]
This is already planned, please only use this for issues, for suggestions use the suggestions channel on our discord https://discord.com/invite/6mdyZbuSDk
