### ISSUE TITLE
menu bug

### ISSUE THREAD

**Issue by p82183645** [Iridium-Development/IridiumSkyblock#123]
check this item, the server will get stuck

and Please check the features on 1.12.2, many have problems

![image](https://user-images.githubusercontent.com/5382252/120872169-7747dd80-c5d0-11eb-8b5b-15e4e7b78d71.png)

![image](https://user-images.githubusercontent.com/5382252/120872162-6e570c00-c5d0-11eb-9981-b05415dbe326.png)

**Comment by dlsf** [comment]
Is there an error message on the log when you click that item?

**Comment by PeachesMLG** [comment]
Doesnt happen to me? Any errors in console? Could you provide a video or something?

**Comment by PeachesMLG** [comment]
@p82183645 please reply or we will close this issue as no one else has reported this and we cant replicate it
