### ISSUE TITLE
daily quests + value island

### ISSUE THREAD

**Issue by gethertv** [Iridium-Development/IridiumSkyblock#132]
Value island dont works, because when im place gold block and get value on island after go to other world my value = 0, restart server dont help, on /is top all have 0 value command like /is recalculate dont help to + after restart server im get new error like below
![image](https://user-images.githubusercontent.com/49717977/120907751-59c45380-c664-11eb-9f30-34a294ca905a.png)

**Comment by PeachesMLG** [comment]
That errors not todo with this, Could you pm me on discord please, ill take a look
