### ISSUE TITLE
The shop is not getting disabled 

### ISSUE THREAD

**Issue by shawn3308** [Iridium-Development/IridiumSkyblock#137]
i made it false and the shop still opens
![unknoaswn](https://user-images.githubusercontent.com/60691117/120958474-6f756e00-c775-11eb-90ea-a12f31e19d4f.png)

**Comment by dlsf** [comment]
We are aware of that issue and already fixed it. Please visit our support Discord if you want a beta jar containing that fix, otherwise it will be released in update 3.0.4 on Friday
