### ISSUE TITLE
Daily missions are faulty

### ISSUE THREAD

**Issue by Spelicious** [Iridium-Development/IridiumSkyblock#139]
Hello. 

So I think i might have find a bug with the daily missions.

Lets say there is 10 players playing. 50% can see their daily missions 50% cant.

The 50% who cant will do /is missions and click on "Daily missions" and the GUI just crashes and this is what the console says: https://pastebin.com/S9DAvn2M 

It seems to come up and dissapear on diffent people. Also daily missions are now way weirder than they used to be.

You login -> Look at your daily missions  (Displays 4 in total) -> do some missions 2-3 dissapear but one of them stays still in the GUI 
Rn i have all the missions done and this is what I see.

![image](https://user-images.githubusercontent.com/62396236/121090505-5ca07f00-c7f1-11eb-96fd-dac962810410.png)

![image](https://user-images.githubusercontent.com/62396236/121090524-64f8ba00-c7f1-11eb-8bd6-fdb86936ef89.png)
![image](https://user-images.githubusercontent.com/62396236/121090537-6a560480-c7f1-11eb-9e0b-d1378489ce24.png)

And no. I havent touched the missions file. It has been like that all along. Before and after translateing.

I could not find any errors on the server startup.  Nor syntax errors viewing the .yml files.

**Comment by dlsf** [comment]
That's only a part of the error message, are you using a web interface or software that may shortens it?

**Comment by Spelicious** [comment]
Im using console logs provided by hosting. Should i look for latest.log?

**Comment by dlsf** [comment]
That would be useful. You could also send it per Discord DMs if you feel uncomfortable with sharing them here

**Comment by Spelicious** [comment]
Do you need full full console log or just the part where it crashes? if so then: https://pastebin.com/UhnxTWRa

**Comment by dlsf** [comment]
That error has already been fixed. Add new slots to the mission GUI (at the bottom of the missions.yml iirc).
