### ISSUE TITLE
Cannot deserialize ItemStack

### ISSUE THREAD

**Issue by LegoCraftNW** [Iridium-Development/IridiumSkyblock#142]
Error: https://paste.ubuntu.com/p/mHNVHHtp2F/

PaperSpigot 1.12.2 latest build

**Comment by dlsf** [comment]
1.12 is currently not fully supported, please wait for the release 3.0.4.

**Comment by MertUnverdi** [comment]
@PeachesMLG @dlsf is didn't fixed yet?

**Comment by dlsf** [comment]
No, it's unfortunately not. However, switching to Worldedit schematics would make it no longer necessary

**Comment by MertUnverdi** [comment]
Still exist ?

**Comment by PeachesMLG** [comment]
https://github.com/Iridium-Development/IridiumSkyblock/issues/340
