### ISSUE TITLE
Writing into PalettedContainer from multiple threads

### ISSUE THREAD

**Issue by Lucreeper74** [Iridium-Development/IridiumSkyblock#147]
I have this error when i make /is regen https://pastebin.com/B0xR8NrR

**Comment by dlsf** [comment]
Looks like an issue with your server software, but I'm not sure. Could you update if possible?

**Comment by Lucreeper74** [comment]
Hello

Update my server software or plugin ? Because i have latest plugin version
and latest spigot version, im on Java 8.

Le dim. 13 juin 2021 à 18:44, Daniel Scherf ***@***.***> a
écrit :

**Comment by dlsf** [comment]
Latest server software. Please make sure you are really using the latest one.

**Comment by Lucreeper74** [comment]
Hi again

The spigot version ?

Le dim. 13 juin 2021 à 20:41, Daniel Scherf ***@***.***> a
écrit :

**Comment by dlsf** [comment]
Yes, the Spigot version

**Comment by PeachesMLG** [comment]
https://github.com/Iridium-Development/IridiumSkyblock/issues/340
