### ISSUE TITLE
/is calc and block values

### ISSUE THREAD

**Issue by StormyBlizzard** [Iridium-Development/IridiumSkyblock#148]
I tried to configure the block values and after configuring them they do show up in the gui and do count value. Although after a few seconds of placing 10 spawners for example the value on /is top goes away. Or /is recalc does not calculate correctly.

**Comment by PeachesMLG** [comment]
Any errors in console?

**Comment by StormyBlizzard** [comment]
Spigot 1.16.5 and plugin version is IridiumSkyblock-3.0.3.jar
