### ISSUE TITLE
Crystall and Money will reset randomly

### ISSUE THREAD

**Issue by antasetyawan** [Iridium-Development/IridiumSkyblock#159]
I dont know the why the crystall and money will reset randomly if use offline player. I think the UUID cannot readed normally. 
Because if i command /is bank which the player reset crystall or money, the name are not appear.

**Comment by PeachesMLG** [comment]
Any errors in console? and can u send your database over

**Comment by dlsf** [comment]
We don't support offline mode, I guess that's the issue here^

**Comment by PeachesMLG** [comment]
Ye if its an offline mode issue then ima just not support offline mode
