### ISSUE TITLE
Bug with region and world border

### ISSUE THREAD

**Issue by Lucreeper74** [Iridium-Development/IridiumSkyblock#168]
The border it's 1 block after de region limit so i can place block but the border it's 1 block after

**Comment by dlsf** [comment]
What is your island size and distance?

**Comment by Nubebuster** [comment]
#173 I sortof fixed this. The island still becomes 1 block bigger when you have an even island size. But the border is fixed.

**Comment by dlsf** [comment]
Just use `Fixes #168` in your PR, it will be linked automatically

**Comment by Lucreeper74** [comment]
Thanks, I'll check it out.

Le mer. 16 juin 2021 à 21:48, Daniel Scherf ***@***.***> a
écrit :
