### ISSUE TITLE
Missing UpgradeData class and other classes in API

### ISSUE THREAD

**Issue by xReveres** [Iridium-Development/IridiumSkyblock#169]
I'm trying to make custom island upgrades, like here:
https://github.com/Iridium-Development/IridiumSkyblock/blob/master/src/main/java/com/iridium/iridiumskyblock/upgrades/SizeUpgrade.java
But my IDE can't find UpgradeData class.
```java
public class SpawnerUpgrade extends UpgradeData{
    public int spawners;
    
    public SpawnerUpgrade(int money, int crystals, int spawners){
        super(money, crystals);
        this.spawners = spawners;
    }
    
    @JsonIgnore
    @Override
    public List<Placeholder> getPlaceholders(){
        return Collections.singletonList(new Placeholder("spawners", String.valueOf(spawners)));
    }
}
```
I added to my pom.xml, repository and dependencies as described on the wiki.
https://github.com/Iridium-Development/IridiumSkyblock/wiki/API

**Comment by xReveres** [comment]
@dlsf
![image](https://user-images.githubusercontent.com/8580908/122259426-78331600-ced2-11eb-85c2-b871f958d94b.png)

**Comment by dlsf** [comment]
The entire upgrade package is missing... Can you reload the Maven project and try again?

**Comment by xReveres** [comment]
I'm tried reload IDE (Apache Netbeans), run maven clean, reload project, reload POM, and same results.

**Comment by dlsf** [comment]
@PeachesMLG any chance that that package is not in the Maven dependency?

**Comment by xReveres** [comment]
@dlsf
Finally i removed C:\Users\<username>\.m2 directory
