### ISSUE TITLE
"You cannot break blocks on this island"

### ISSUE THREAD

**Issue by ejspinn** [Iridium-Development/IridiumSkyblock#176]
When i fall off my tree and land on my own island the warning in the the title appears.  I am the only player on the server, as its just a test server.  fresh 1.17 spigot compile, Iridium 3.0.4 jar

**Comment by PeachesMLG** [comment]
Not quite sure what you mean by this, can you send a video or something?

**Comment by dm1lk** [comment]
![2021-06-26_00 09 55](https://user-images.githubusercontent.com/77703500/123492946-e1253700-d612-11eb-9e98-7d3eacb07c1c.png)

**Comment by dm1lk** [comment]
Trample on Crops on your island, it spams you with this prompt

**Comment by ReySniperio** [comment]
I had this issue to . all in the sudden i couldnt break any blocks anymore.
