### ISSUE TITLE
When do /is deletewarp but i can't remake this error :/

### ISSUE THREAD

**Issue by Lucreeper74** [Iridium-Development/IridiumSkyblock#178]
https://pastebin.com/RrbX7EyZ

**Comment by dlsf** [comment]
This issue only occurs when you don't specify the name of the warp

**Comment by Lucreeper74** [comment]
Ok, so u can fix the error and send message like this "Please specify the
name of warps" or something like that :D

Le ven. 18 juin 2021 à 19:20, Daniel Scherf ***@***.***> a
écrit :
