### ISSUE TITLE
Oak Sapling bought from shop doesn't stack with oak sapling that falls from tree

### ISSUE THREAD

**Issue by ejspinn** [Iridium-Development/IridiumSkyblock#181]
Stupid enderman stole dirt block beside my generator, lava leaked out burned down my only  jungle tree.  I bought a 4 pack of oak saplings from /island shop.  Planted it and harvest it. When I went to combine all the saplings in my chest, the ones from the shop have a different color label then the ones that fell from decomposing leaves.  spigot buildtools jar 1.17 and newest Iridium from spigot site.

**Comment by ejspinn** [comment]
the one with blue letters when you hover over  it says 
minecraft:oak_sapling
NBT: 1 tag(s)

the one with white color letters says
minecraft:oak_sapling

**Comment by dlsf** [comment]
That's normal Vanilla behavior, the name has to be exactly the same

**Comment by ejspinn** [comment]
ive never noticed  had any stacking issues in other games I played.

**Comment by dlsf** [comment]
If you choose the same name it will be stackable. I'll add support for default Minecraft names without colors in the next update
