### ISSUE TITLE
/visit freezes the server

### ISSUE THREAD

**Issue by Nubebuster** [Iridium-Development/IridiumSkyblock#185]
/visit does database operations on the main thread when populating the VisitGUI

**Comment by Nubebuster** [comment]
Looking at the paper freeze stacktrace, maybe the issue is with the server creating a lot of skull items.

Are all islands always loaded into memory?

**Comment by Nubebuster** [comment]
I can confirm the skull lookup is the issue.
According to xTrollxDudex on 
https://www.spigotmc.org/threads/tutorial-get-player-heads-without-lag.396186/
we should be using SkullMeta#setOwningPlayer(OfflinePlayer) on an async thread to prevent the server from downloading the player skin when it is added to the inventory.

**Comment by Nubebuster** [comment]
This freeze issue happens everywhere where a player head is used. In most gui's it's not a huge problem, since they only need to be initialized once. But for example the members gui can also cause major lag spikes.

Since there will only be existing offline players in the members gui and visitgui we should really change the method setting skull owners to the better method.

**Comment by Nubebuster** [comment]
I'm working on a solution. I'll try and make a pull request tomorrow.

**Comment by dlsf** [comment]
Alright, thank you! :)

Feel free to contact me on Discord at any time if you need any help
