### ISSUE TITLE
When I die in overworld I spawn back on my island

### ISSUE THREAD

**Issue by PappoYT** [Iridium-Development/IridiumSkyblock#19]
**Configuration**
Multiplayer Paper 1.16.4 git-Paper-405 (MC: 1.16.4) server
IridiumSkyblock v2.6.7
Multiverse-Core v5.0.0-ACF-BETA-b13

**Problem**
If I die in overworld I spawn back on my island.
It happens to all players on server.

/plugin/multiverse-core/worlds.yml
`respawnWorld` is set for all worlds:
overwrold respawnWorld to overworld
skyblock respawnWorld to skyblock

Link to log: [https://mclo.gs/to1Gpfn](https://mclo.gs/to1Gpfn)

**Comment by PeachesMLG** [comment]
This is for 3.0.0 dont report bugs for 2.6.7 here

**Comment by PappoYT** [comment]
Where can i report bug for 2.6.7?

**Comment by PeachesMLG** [comment]
no where, im not gona fix them since its being recoded

**Comment by PappoYT** [comment]
Can you suggest me if it is better if I move to 3.0.0 (but it is still beta) or wait in 2.6.7?

**Comment by dlsf** [comment]
3.0 has not been released yet and is still lacking many features
