### ISSUE TITLE
Replacement for IslandWorthCalculatedEvent

### ISSUE THREAD

**Issue by LMBishop** [Iridium-Development/IridiumSkyblock#193]
Currently there is no way to know when a player's island value has changed, or has been recalculated. Older versions of the plugin provided an `IslandWorthCalculatedEvent` which was sufficient enough to detect updates on a player's island value, though such solutions no longer exist in this new version.

**Comment by PeachesMLG** [comment]
Please use the discord #suggestions for suggestions

**Comment by PeachesMLG** [comment]
but I belive this suggestion already exists, ill add it by friday's update
