### ISSUE TITLE
Data Wiping Randomly

### ISSUE THREAD

**Issue by itslukemango** [Iridium-Development/IridiumSkyblock#194]
We're having an issue where island banks, crystals and missions are wiping.
Crystals and banks sometimes re-appear but this isn't 100% of the time.

**Comment by itslukemango** [comment]
Just to add to this, using 3.0.4 with SQLite storage.

**Comment by dlsf** [comment]
Is there an error message in the console?

**Comment by itslukemango** [comment]
> 
> 
> Is there an error message in the console?

No, it just disappears randomly

**Comment by dlsf** [comment]
Might be related to #111

**Comment by itslukemango** [comment]
Just to add to this, exported our DB to CSV and there's 5 entries (for both crystals and money) with our Island ID in the island_bank table

**Comment by dlsf** [comment]
I kinda expected that. @PeachesMLG the issues are not gone and they apparently affect other tables besides upgrades too

**Comment by PeachesMLG** [comment]
can u send me your database via pm

**Comment by itslukemango** [comment]
sent @PeachesMLG

**Comment by Nubebuster** [comment]
I have had the same problem with my production server. It runs on mysql. I am pretty sure it has to do with reloading. The error has only ocurred after a session of fixing bugs and using plugman to reload iridiumskyblock.

Anyone experiencing this error, DO NOT RELOAD iridiumskyblock until this has been fixed.

NB: reloading plugins is almost always a bad idea in production environments

**Comment by PeachesMLG** [comment]
Still cant replicate this even with plugman reloading stuff, Perhaps I fixed it in this commit? https://github.com/Iridium-Development/IridiumSkyblock/commit/4f687827971a8531dd0768381ff0f9b4b152996b :shrug:

**Comment by dlsf** [comment]
https://github.com/Iridium-Development/IridiumSkyblock/commit/55f48b837c515a18496e92fe44a257da0376a90e might have also fixed it

**Comment by itslukemango** [comment]
Will this update remove the excess islands from the island_bank table? If not this won't really fix the issue

**Comment by PeachesMLG** [comment]
> Will this update remove the excess islands from the island_bank table? If not this won't really fix the issue

Im working on this right now

**Comment by itslukemango** [comment]
> 
> 
> > Will this update remove the excess islands from the island_bank table? If not this won't really fix the issue
> 
> Im working on this right now

Any updates on this?

**Comment by PeachesMLG** [comment]
Should be fixed in tomorrows update, sorry for the wait
