### ISSUE TITLE
Nether and End Disabled - Still checking for loads and unloads

### ISSUE THREAD

**Issue by itslukemango** [Iridium-Development/IridiumSkyblock#196]
We have end and nether islands disabled but they're the highest on timings, can't unload it either because of the NPE https://pastebin.com/YUg54cGB
![image](https://user-images.githubusercontent.com/29614155/122807552-a2fedf00-d2c3-11eb-8d9a-a6ab23a32394.png)

**Comment by dlsf** [comment]
We don't support disabling worlds at the moment. Using a third-party plugin will obviously fail too

**Comment by itslukemango** [comment]
@dlsf https://lukemango.com/iN0Yz.png you do in the config?

**Comment by dlsf** [comment]
That just prevents users from visiting these islands at the moment, it doesn't stop world generation or unloads these worlds
