### ISSUE TITLE
[Enhancement Request] Add "Back" button to menus

### ISSUE THREAD

**Issue by farum12** [Iridium-Development/IridiumSkyblock#198]
![image](https://user-images.githubusercontent.com/56656135/122817252-f9761880-d2d7-11eb-8663-73fd9c77ba1a.png)

It would be convinient to have "Back" button to all menus, which are accessible via /island command. 

As a User, when I'm browsing deeper menus, like "Regenerate Island" or "Island Bank" I want to have an ability to go back to Island Main Menu.

Currently, I need to close the panel and type /island command.

**Comment by PeachesMLG** [comment]
This is for issues only use #suggestions on the discord for suggestions, but again this suggestion already exists
