### ISSUE TITLE
Islands have more then one biome

### ISSUE THREAD

**Issue by tjaws** [Iridium-Development/IridiumSkyblock#201]
When creating an island it should for example have biome: "PLAINS" but it has a lot of different biomes.
The bigger your island gets the more biomes. It also will not rain in some chunks for this reason.

**Comment by Nubebuster** [comment]
Duplicate of #75

**Comment by PeachesMLG** [comment]
> Duplicate of #75

No its not? Its bgecause we never actually change the biome, I belive ori is making a pr for this

**Comment by dlsf** [comment]
Duplicate of #188
