### ISSUE TITLE
Island Bank Issues

### ISSUE THREAD

**Issue by pixelnw** [Iridium-Development/IridiumSkyblock#206]
**Even though the Island Money is 1000, I am getting the following error:** ![Screenshot_8](https://user-images.githubusercontent.com/67561360/122993276-cacb7100-d3af-11eb-94df-86016a3aa73c.png)

**Even though the Island Crystals is 5, the crystal is not withdraw/deposite and the error message does not appear**

**Even though the Island Experience is 3, I am getting the following error:** ![image](https://user-images.githubusercontent.com/67561360/122993751-5b09b600-d3b0-11eb-97ec-2917905bb48a.png)

**Comment by dlsf** [comment]
You can't withdraw crystals at the moment.

Experience in the bank is the experience you get from killing mobs, not the one on /is experience.
Withdrawing money requires an economy plugin to be installed, is that the case?

**Comment by pixelnw** [comment]
_"Experience in the bank is the experience you get from killing mobs, not the one on /is experience."_
What I'm talking about is experience from missions


_"Withdrawing money requires an economy plugin to be installed, is that the case?"_
Essentials and vault installed but still not working

**Comment by dlsf** [comment]
>  I'm talking about is experience from missions

Then that's not the experience in the bank.

>  Essentials and vault installed but still not working

Sounds weird, but it's working for other users. Can you please check if you really have money in your Essentials purse?

**Comment by MertUnverdi** [comment]
non answered 👍🏻
