### ISSUE TITLE
Missions and Issues

### ISSUE THREAD

**Issue by pixelnw** [Iridium-Development/IridiumSkyblock#207]
**Missions:** Grow Sugar Cane, Grow Cactus, Grow Carrot, Break Oak Log, Grow Melon **(these are the ones I tested and it doesn't work.)** 

**Crafting Table Missions:** After making any recipe on the Crafting Table
When we take it with shift, it does not count the mission, but when we take it with left click, it counts.

**Comment by dlsf** [comment]
What Minecraft version are you on? Growing means breaking the blocks btw afaik

**Comment by PeachesMLG** [comment]
> What Minecraft version are you on? Growing means breaking the blocks btw afaik

Nope, Thats how it was in 2.6.7 but now you just have to pysically grow it, doesnt matter if you break it or not
