### ISSUE TITLE
Issues with island biomes & the 3.0.4 patch from Discord

### ISSUE THREAD

**Issue by Apxthy** [Iridium-Development/IridiumSkyblock#209]
In version 3.0.4 that is released on Spigot, when trying to edit island biome in the schematics.yml file, it will use whatever biome the island is currently in, in the world. It wont detect what is written in the "biome" field on the file. 

Another problem I found is when you use the  jar file that seems to be a patch for 3.0.4 that was posted in Discord, when you use the island command for regenerating the island(/is regen), the default island gets cut in half and ruined, causing the player to have to fully delete their island and re-create it.

**Comment by dlsf** [comment]
> In version 3.0.4 that is released on Spigot, when trying to edit island biome in the schematics.yml file, it will use whatever biome the island is currently in, in the world. It wont detect what is written in the "biome" field on the file.

Biomes are not implemented yet, see #188.

We'll look into that other issue

**Comment by PeachesMLG** [comment]
Cant replicate the other issue, If it still persists after todays update open another ticket i guess
