### ISSUE TITLE
Changing missions from "once" to "daily" and the other way around - not working

### ISSUE THREAD

**Issue by Milan1026** [Iridium-Development/IridiumSkyblock#210]
Hello. I have an issue with editing missions.

I tried changing some missions from the "once" missions to "daily" missions, but I noticed these missions aren't showing up in the "daily" missions GUI. I tried adding DailySlots in missions.yml and also giving "slot: null" a number. Didn't work.

I also tried it the other way around, from "daily" to "once". This works, but it duplicates the missions. So these missions appears in both the "once" and "daily" missions GUI.

**Comment by PeachesMLG** [comment]
Yep, thats because the daily missions have already been set for each island, tomorrow they will get new ones
