### ISSUE TITLE
Placing blocks in Skyblock world - dissapearing

### ISSUE THREAD

**Issue by Milan1026** [Iridium-Development/IridiumSkyblock#212]
When I try to place a block in my Skyblock world, even when bypassing island restrictions, the block dissapears. Block breaking is possible for me. Also interacting or placing item frames is possible.

I can only place blocks inside my own island. I can't place blocks when I go to the nether.

I've tried this on my private server, where I have only the plugins needed for IridiumSkyblock installed and I have the same issue there.

**Comment by amirshah2935** [comment]
Hi yes i have been having this issue..where i can build in the IridiumSkyblock_nether..i have check with my multiverse setting or world edit setting ..i dont htin kthere is any block..also im op should have any issue..checking the logs doesnt provide any ewrrors.

**Comment by PeachesMLG** [comment]
Duplicate of https://github.com/Iridium-Development/IridiumSkyblock/issues/208
