### ISSUE TITLE
1.8.8 Nether spawn issues

### ISSUE THREAD

**Issue by itsmemac** [Iridium-Development/IridiumSkyblock#218]
**Issue** : 
When teleported to nether using nether portal, the spawn height is 0 hence user falls down and gets teleported back to home island. Iridium ignores the spawn height of island from schematics.yml

**Server version** : 1.8.8 Spigot
**Plugin version** :  3.0.5
**All plugins in server** : Essentials, Vault, IridiudiumSkyblock

**Server log** : https://paste.lucko.me/0DqTCdaXQC (No errors in console when this happens)

**Configurations** : All default plugin (No changes done, just dropped in the jar , started server and created island with default)
[schematics.yml](https://paste.lucko.me/uEhBkoOUTq)

**Video** : 

- https://imgur.com/a/51oZzNf
- https://imgur.com/8q6lPPd

**Comment by dlsf** [comment]
Can you please send us your schematics.yml?

**Comment by itsmemac** [comment]
> Can you please send us your schematics.yml?

https://paste.lucko.me/uEhBkoOUTq
Updated in main issue as well

**Comment by dlsf** [comment]
Oh, you didn't change anything. Let me check

**Comment by dlsf** [comment]
Alright, I was able to replicate it

**Comment by PeachesMLG** [comment]
1.8 is no longer supported

**Comment by CayeOficial** [comment]
It's fixed?
