### ISSUE TITLE
Spawn world now has an island world border and /spawn goes to the border

### ISSUE THREAD

**Issue by Sparxez** [Iridium-Development/IridiumSkyblock#224]
I used a 3.0.4 dev build and it completely ruined the spawn world by adding an island sized border there, I am pretty sure islands are also created there. /spawn cannot be edited as well. Updating to 3.0.5 did not fix this

**Comment by dlsf** [comment]
Did you set the IridiumSkyblock world as the default world in the server.properties / bukkit.yml?

**Comment by Sparxez** [comment]
I fixed it by setting the world border to its normal state, it just doesn't make sense that it happened..

**Comment by dlsf** [comment]
How exactly did you set the world border?

**Comment by dlsf** [comment]
I think I know what the issue is

**Comment by Alv5ro** [comment]
![image](https://user-images.githubusercontent.com/57922931/125142511-d63ccd00-e10f-11eb-8a99-4cdffb9a2773.png)
I'm having this problem, do you mind sharing the solution?

**Comment by dlsf** [comment]
We have to find a solution, there is nothing you can do

**Comment by Alv5ro** [comment]
Yeah no worries, if you ever need to test it, you can come on my server

**Comment by Sparxez** [comment]
> ![image](https://user-images.githubusercontent.com/57922931/125142511-d63ccd00-e10f-11eb-8a99-4cdffb9a2773.png)
> I'm having this problem, do you mind sharing the solution?

I just did /worldborder set (number) and it fixed it. I set mine to the default world border
