### ISSUE TITLE
Island creation doesn't create signs

### ISSUE THREAD

**Issue by Alv5ro** [Iridium-Development/IridiumSkyblock#225]
![image](https://user-images.githubusercontent.com/57922931/123794214-81f94800-d8da-11eb-90e8-89ea911f4255.png)

On creating an island, the sign doesn't spawn with colour or normal text, but the sign itself does.

Make sense?

**Comment by dlsf** [comment]
We don't support text on signs. Might be fixed when #75 has been closed though
