### ISSUE TITLE
/is top - TPS Drops

### ISSUE THREAD

**Issue by itslukemango** [Iridium-Development/IridiumSkyblock#226]
The TPS drops whenever /is top is used

**Comment by dlsf** [comment]
What is your IridiumSkyblock and Minecraft version? How many islands do you approximately have?

**Comment by itslukemango** [comment]
Probably a good 1500 islands, 1.16.5 and 3.0.5 (IS)

**Comment by PeachesMLG** [comment]
gonna need a timings report please

**Comment by itslukemango** [comment]
https://timings.aikar.co/?id=4c50084e99574ea9aa80e9489dd3794b

**Comment by PeachesMLG** [comment]
Nevermind ill fix this soon

**Comment by dlsf** [comment]
I still want to improve the existing fix
