### ISSUE TITLE
Quests Are Not Being Completed

### ISSUE THREAD

**Issue by tucokk** [Iridium-Development/IridiumSkyblock#248]
When you make an objective of a Quest (as far I've seen  Daily Quests are working normally), it's not counting in it. It harms a lot of the principal gameplay. (3.0.5, MC 1.17)

**Comment by dlsf** [comment]
Is this still an issue for you? If so, did you generate the island before or after changing the mission objectives?

**Comment by MertUnverdi** [comment]
No response
