### ISSUE TITLE
Islands not generating correctly

### ISSUE THREAD

**Issue by FoxWithSox** [Iridium-Development/IridiumSkyblock#249]
when creating or resetting an island this message shows in console 

https://pastebin.com/PqttkcsM

this is my schematics.yml

https://pastebin.com/4XRR8Kh2

![image](https://user-images.githubusercontent.com/25159633/124381042-69987d00-dc8e-11eb-9a81-8529ce7bf241.png)

**Comment by dlsf** [comment]
There is something wrong with the nether. Did you unload the nether world or did you change anything regarding the schematics?

**Comment by FoxWithSox** [comment]
issue fixed, there were duplicate world folders. deleting the duplicates solved the issue
