### ISSUE TITLE
Island Members GUI Handled Differently

### ISSUE THREAD

**Issue by Sparxez** [Iridium-Development/IridiumSkyblock#251]
Other GUI's such as the main menu and missions GUI allow items to be created that execute a command, but trying to do this in the members GUI gives an error (https://pastebin.com/7pEwQAGT).

**Comment by Sparxez** [comment]
Same issue seems to be present with the warps GUI

**Comment by MertUnverdi** [comment]
Can we see your inventors.yml

**Comment by Sparxez** [comment]
> Can we see your inventors.yml

https://pastebin.com/G1NpHZCT

My inventories.yml has nothing to do with this? :/
These menu's don't have an "items:" sections not allowing custom items.

**Comment by PeachesMLG** [comment]
This isnt a bug, its not possible to do this with membersGUI due to how its coded since its dynamic with items being added with the amount of membrs on your island as apposed to the main /is gui which is always the same
