### ISSUE TITLE
Setting "respawn-on-island: true" bugs bedwars 

### ISSUE THREAD

**Issue by Mattyboys** [Iridium-Development/IridiumSkyblock#254]
i turned on a setting in the configuration.yml in the IridiumSkyblock
but when i do so. Players that die and respawn at there base in bedwars cannot build after
the setting is: respawn-on-island: true
I am not using bungeecord but Bedwars and skyblock are inside of 2 different worlds

**Comment by PeachesMLG** [comment]
Sounds like an issue with bedwars to me
