### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by IamThomasisko** [Iridium-Development/IridiumSkyblock#259]
I write to scoreboard %iridiumskyblock_island_bank_money% and placeholder don´t do it bank account please help me and this is the same problem with crystals
![image](https://user-images.githubusercontent.com/87225455/125158623-8a6f3f80-e172-11eb-9f4a-b6e663814844.png)

**Comment by dlsf** [comment]
Make sure you are using the latest version of IridiumSkyblock, you installed PlaceholderAPI, and your scoreboard plugin supports PlaceholderAPI.

**Comment by rasbwoy** [comment]
I have another question with placeholders that we can see in iridium wiki. I am looking for top value and top name placeholders to make a holo with ranking in server... but these placeholders now doesn't exist. Maybe its already explained so sorry but would be very useful for me.

**Comment by dlsf** [comment]
We don't have top placeholders but they'll be added soon. Does the original issue above still exist?

**Comment by MertUnverdi** [comment]
No response

**Comment by rasbwoy** [comment]
i have no problem with island crystals placeholder, now works correctly. The island bank placeholders i guess works too, but i don't use for nor in my server yet. I hop this will be useful for you. Thanks, and good day.
![screenshotserver](https://user-images.githubusercontent.com/50847949/126483447-7751095a-1185-4b6a-b11a-a3593439ffbf.png)
