### ISSUE TITLE
[Bug] Teleporting to island

### ISSUE THREAD

**Issue by Queijoebom** [Iridium-Development/IridiumSkyblock#264]
When I use "/is go" ON THE ISLAND I teleport to the right area
![2021-07-11_13 31 32](https://user-images.githubusercontent.com/73173641/125203864-d7c1de80-e250-11eb-98c5-4129d92ec7ba.png)
but if i use the same command in another world for example on nether or end i teleport to the highest point of the island
![2021-07-11_13 31 50](https://user-images.githubusercontent.com/73173641/125203871-dee8ec80-e250-11eb-8fcb-6d68f97821f9.png)

**Comment by PeachesMLG** [comment]
Weird, is this still an issue with 3.0.7?

**Comment by MertUnverdi** [comment]
No response, it will close after 1 days 👍🏻
