### ISSUE TITLE
[Bug] Limited Blocks

### ISSUE THREAD

**Issue by Queijoebom** [Iridium-Development/IridiumSkyblock#265]
Well I don't know how I can explain it so I'll do it in stages:

**Version:** 3.0.6
**Minecraft:** 1.12.2
1. First I created an island and tested it to the limit, and managed to place the blocks on the side of the island's edge.
![2021-07-11_17 05 10](https://user-images.githubusercontent.com/73173641/125208855-6f342b00-e26b-11eb-8785-92e2fcb0bd6f.png)

2. Then I deleted my island and created another one in the same structure and I retested the block limit but I couldn't place blocks on the North and West sides with a limit of 1 block difference
![2021-07-11_17 10 36](https://user-images.githubusercontent.com/73173641/125208885-9e4a9c80-e26b-11eb-952e-ae9e066ea9e3.png)

**I've already created several islands and I had the same problem, remembering that they are the original files without any changes and there is no error on the console**

NOTE: I had to delete all files including the worlds, so that the first island in the image could use the entire island area, and even upgrading the island size gave this problem

I'll leave a little video to show

https://user-images.githubusercontent.com/73173641/125209058-b0790a80-e26c-11eb-82b1-ad7ace510a08.mp4

I used Google translator, good afternoon ☕

**Comment by PeachesMLG** [comment]
Hmm Weird, looks like this doesnt happen on Island Id#1 but does on #2

**Comment by PeachesMLG** [comment]
Should be fixed in tomorrows update
