### ISSUE TITLE
When going to an island and placing blocks there is a random chance of the server completely freezing and crashing

### ISSUE THREAD

**Issue by YxriDevOfficial** [Iridium-Development/IridiumSkyblock#27]
Stack Trace: https://pastebin.com/1zvj75QN

Issue was noted to happen frequently when nobody has been online the server for a prolonged amount of time and then someone joins and goes to their island.

All settings are default except for the prefix and leveling rewards.

**Comment by PeachesMLG** [comment]
https://github.com/Iridium-Development/IridiumSkyblock/issues/24
