### ISSUE TITLE
Bugs on 1.8.9

### ISSUE THREAD

**Issue by CayeOficial** [Iridium-Development/IridiumSkyblock#277]
If you are using the Minecraft version 1.8.9.
You can't go to the nether (you spawn under the island so you fall into the void)
You cant complete some missions
Make ultimate stacker compatible with iridiumskyblock

**Comment by dlsf** [comment]
> You can't go to the nether (you spawn under the island so you fall into the void)
Check #218 
> You cant complete some missions
How exactly does that look like? Which missions are affected? Are all islands affected? Are there error messages?
> Make ultimate stacker compatible with iridiumskyblock
It already is

**Comment by CayeOficial** [comment]
All island are affected, you can complete some missions like Hunter, but others like Wheat farmer or crafter not.

Ultimate stacker don't work, because if u put a stacked block, it will count as one, so if u have the diamond block worth 10 points, and u have x64 diamond block stacked, it will give to you 10 points and not 640 points

I'm using 1.8.9

**Comment by CayeOficial** [comment]
And what about nether, how I can fix it? In the issue mentioned don't appears anything to how to fix it

**Comment by dlsf** [comment]
Open issues are still not fixed.

The block stacking issues are probably really a problem.

**Comment by CayeOficial** [comment]
Okay thanks you

**Comment by PeachesMLG** [comment]
In future could you please open each issue in a seperate issue thread
