### ISSUE TITLE
Ignore cancelled events

### ISSUE THREAD

**Issue by xReveres** [Iridium-Development/IridiumSkyblock#281]
I have upgrade to limit (for example 5) spawners.
When I try to place 6th spawner, my plugin (upgrade) cancel it, but not Iridium and adds 6th spawner to island blocks.
I think the problem is in @EventHandlers it should be used with ignoreCancelled=true

Another problem (or rather performance issue) that I discovered, occurs for example here:
https://github.com/Iridium-Development/IridiumSkyblock/blob/master/src/main/java/com/iridium/iridiumskyblock/listeners/BlockBreakListener.java
On line 28 Iridium checks permission to see if player can destroy block, if not, event is cancelled (block is prevented from break), but below (line 35...) code executes and iridium subtract island blocks, so I think you should add "return" below every event.setCancelled(true).

**Comment by MertUnverdi** [comment]
feel free to make pr for each 👍🏻
