### ISSUE TITLE
"Could not pass event BlockFormEvent to IridiumSkyblock"

### ISSUE THREAD

**Issue by Ethanboyz** [Iridium-Development/IridiumSkyblock#284]
**Version: 3.0.6**
**Minecraft: 1.17**

Issue: custom ore generators in upgrades don't work. They only generate cobblestone like a normal cobble gen.

On startup, an error message pops up in console: https://pastebin.com/ThPpw2MF

Then when mining a block from a cobble gen in-game and having a block form, this error pops up: https://pastebin.com/bhLxQwns

Meanwhile, iridium skyblock commands in-game break and world generation in iridiumskyblock appears to break, signaling that the plugin has encountered some fatal error

**Comment by MertUnverdi** [comment]
it shouldn't possible 
can you send upgrades.yml ?

**Comment by dlsf** [comment]
This issue has already been fixed by #269 (nice), please visit our support Discord for a beta jar
