### ISSUE TITLE
This plugin is crashing my server

### ISSUE THREAD

**Issue by CayeOficial** [Iridium-Development/IridiumSkyblock#286]
https://pastebin.ubuntu.com/p/4Krfr8HPfx/

**Comment by MertUnverdi** [comment]
needed more clue, please follow correct issue syntax

**Comment by CayeOficial** [comment]
What I need to tell you?

**Comment by MertUnverdi** [comment]
Server version, plugin version, did any changes, when happens etc.

**Comment by CayeOficial** [comment]
Server v: 1.8.8 spigot
Plugin v: 3.0.6 pinned version on discord
No I don't did any change appears when he feels like it

**Comment by dlsf** [comment]
This issue has already been fixed, please visit our support Discord for a beta jar

**Comment by CayeOficial** [comment]
No, the issue still with the 3.0.7 beta

**Comment by dlsf** [comment]
Is this error message from the 3.0.7 beta or 3.0.6? I need the one from 3.0.7

**Comment by CayeOficial** [comment]
This error is from 3.0.6, I had the .7 version, but the server crashed, so being a beta, I preferred to stop using a beta and use the 3.0.6 pinned on the discord server. In the same way I have the message of the 3.0.7 version, I will check logs, wait

**Comment by CayeOficial** [comment]
https://pastebin.ubuntu.com/p/3nGRYDPGT6/ here is the crash error from 3.0.7 beta

**Comment by MertUnverdi** [comment]
please send full error log this not enough

**Comment by dlsf** [comment]
It's sufficient to know that that's not the correct 3.0.7 beta. @PeachesMLG probably uploaded the wrong version, please try the newest one that is pinned on Discord

**Comment by CayeOficial** [comment]
Okay
