### ISSUE TITLE
ArrayIndexOutOfBounds exception

### ISSUE THREAD

**Issue by xReveres** [Iridium-Development/IridiumSkyblock#287]
> [19:28:54] [Craft Scheduler Thread - 104/WARN]: [IridiumSkyblock] Plugin IridiumSkyblock v3.0.6 generated an exception while executing task 153120
> java.lang.ArrayIndexOutOfBoundsException: 27
> 	at java.util.Arrays$ArrayList.set(Arrays.java:3846) ~[?:1.8.0_282]
> 	at net.minecraft.server.v1_16_R3.NonNullList.set(SourceFile:53) ~[patched_1.16.5.jar:git-Paper-715]
> 	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftInventoryCustom$MinecraftInventory.setItem(CraftInventoryCustom.java:141) ~[patched_1.16.5.jar:git-Paper-715]
> 	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftInventory.setItem(CraftInventory.java:100) ~[patched_1.16.5.jar:git-Paper-715]
> 	at com.iridium.iridiumskyblock.gui.BlockValueGUI.addContent(BlockValueGUI.java:49) ~[?:?]
> 	at com.iridium.iridiumskyblock.gui.GUI.lambda$getInventory$0(GUI.java:43) ~[?:?]
> 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-715]
> 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-715]
> 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-715]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_282]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_282]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

**Comment by MertUnverdi** [comment]
you must increase size of blockValuesGUI on inventories.json if you have put much blocks than 27
