### ISSUE TITLE
IslandRewards SQL exception

### ISSUE THREAD

**Issue by xReveres** [Iridium-Development/IridiumSkyblock#288]
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: java.sql.SQLException: Unable to run insert stmt on object com.iridium.iridiumskyblock.database.IslandReward@225abf6b: INSERT INTO `island_rewards` (`reward` ,`island_id` ) VALUES (?,?)
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: 	at com.iridium.iridiumskyblock.dependencies.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:25)
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: 	at com.iridium.iridiumskyblock.dependencies.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:140)
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: 	at com.iridium.iridiumskyblock.dependencies.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:465)
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: 	at com.iridium.iridiumskyblock.dependencies.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:332)
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: 	at com.iridium.iridiumskyblock.dependencies.ormlite.dao.BaseDaoImpl.createOrUpdate(BaseDaoImpl.java:391)
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: 	at com.iridium.iridiumskyblock.managers.tablemanagers.TableManager.save(TableManager.java:45)
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: 	at com.iridium.iridiumskyblock.IridiumSkyblock.saveData(IridiumSkyblock.java:306)
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: 	at java.lang.Thread.run(Thread.java:748)
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'reward' at row 1
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: 	at com.iridium.iridiumskyblock.dependencies.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:193)
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: 	at com.iridium.iridiumskyblock.dependencies.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:92)
> [19:43:52] [Craft Scheduler Thread - 126/WARN]: 	... 11 more

**Comment by dlsf** [comment]
What version of IridiumSkyblock are you using?

**Comment by xReveres** [comment]
@dlsf 3.0.6

**Comment by xReveres** [comment]
@dlsf we found problem.
So problem is in missing some "database schematic synchronization mechanism" because we are using IridiumSkyblock since v.3.0.0 our column "reward" in "iridium_rewards" was VARCHAR(255), in commit https://github.com/Iridium-Development/IridiumSkyblock/commit/12ccfc8ebda479345edc2208bd1232af4c793a9a length was changed to 2048 but our database has not been updated to new column size.

**Comment by dlsf** [comment]
Thanks, that helps a lot
