### ISSUE TITLE
Bug with world-border interaction

### ISSUE THREAD

**Issue by Opalinium** [Iridium-Development/IridiumSkyblock#290]
When going between dimensions on your island, if the border is enabled, the out-of-bounds vignette will show on the players screen, and all interactions aside from chat will be blocked, as if the player is in adventure mode (Similar to being outside of the world border)

**Comment by tksky1** [comment]
pls fix this, I'm suffering the same problem

**Comment by dlsf** [comment]
Fixed by #258, visit our support Discord for a beta jar
