### ISSUE TITLE
Config error with message.yml and api with rank displayname 

### ISSUE THREAD

**Issue by Farmeurimmo** [Iridium-Development/IridiumSkyblock#297]
In messages.yml, there is "is rank" displayname but they are not applied on /is perms
and with the api too.

**Comment by xReveres** [comment]
I don't know if this is the solution but you can change name in inventories.yml "islandRanksGUI" and what you mean "with the api too"

**Comment by dlsf** [comment]
I suspect that you're just using an old version of the inventories.yml. Try removing the section for the ranks GUI completely and restart your server after that. 

The rank names are all configurable.
