### ISSUE TITLE
Cannot get enum value of 'GRASS_PATH'

### ISSUE THREAD

**Issue by RyVador** [Iridium-Development/IridiumSkyblock#298]
**Describe the bug**
plugin no worky with db )

**To Reproduce**
1. Use any version above 3.0.3
2. Load the db file attached
3. See error

**Expected behavior**
for plugin to work

** Server Version and Plugin Version**
Versions 3.0.3+, Minecraft 1.16.5

**Screenshots**

**Logs**
If there are error messages in your console, please send them via [This](https://paste.gg/ )
https://paste.gg/p/anonymous/09568d2eae4e43129c7e457a6ee19d83

**Additional context**
Resetting the db file fixes this

**Comment by RyVador** [comment]
so the db file didnt attach, its the one i put in the super secret channel

**Comment by dlsf** [comment]
No idea if this is a duplicate tbh but we'll keep it for now
