### ISSUE TITLE
Plugin is crashing my server and spamming a error

### ISSUE THREAD

**Issue by CayeOficial** [Iridium-Development/IridiumSkyblock#303]
Using pinned version on discord,

Crash log: https://pastebin.ubuntu.com/p/4Krfr8HPfx/

Error spam: https://pastebin.ubuntu.com/p/77N5F2qhXJ/

**Comment by MertUnverdi** [comment]
@Oribuin it seems about your obsidian thing

**Comment by CayeOficial** [comment]
How to solve?

**Comment by MertUnverdi** [comment]
im now working on this, i'll update the version at pinned messages i'll ping u

**Comment by MertUnverdi** [comment]
Ty for reported it <3

**Comment by CayeOficial** [comment]
> Ty for reported it <3

You're welcome.



> im now working on this, i'll update the version at pinned messages i'll ping u

zCayeOficial#4848  ^^

**Comment by dlsf** [comment]
Don't close issues that are not fixed on master

**Comment by Oribuin** [comment]
Okay so after looking at the code, Please for the love of God. Maintain the code standard I had in my original PR because doing else ladders seriously hurts my soul

**Comment by CayeOficial** [comment]
Omg, remove it from the code, rewrite it when 3.0.7 comes out

**Comment by CayeOficial** [comment]
Just a suggestion, not an obligation

**Comment by Oribuin** [comment]
I redid this in a way that doesn't make the code look like peaches made it, Try using this, I couldn't push a PR cause i don't have access to this repo.

https://paste.helpch.at/titezosela.java

**Comment by dlsf** [comment]
```java
            if (InventoryUtils.hasEmptySlot(player.getInventory()))
                event.getPlayer().getInventory().addItem(new ItemStack(Material.LAVA_BUCKET));
            else
                event.getPlayer().getWorld().dropItem(player.getLocation(), new ItemStack(Material.LAVA_BUCKET));
```

Yeah no, that gives me nightmares. Always use brackets for if-else blocks.

Normally I use brackets everywhere but in this project, it got kinda out of control so we are mostly using `return` statements on the same line as the `if` statement as long as the condition is short. Otherwise, we use brackets.
