### ISSUE TITLE
1.16 Blocks don't load/copy over

### ISSUE THREAD

**Issue by DevsyTV** [Iridium-Development/IridiumSkyblock#310]
Using Iridium's Schematic system, any 1.16 block doesn't get copied into the .iridiumschematic file, as upon pasting the schematic iridium replaces said blocks with air.

To reproduce, just use the schematic system with any 1.16 block, say nylium variants for example. (/is pos1, /is pos2/, /is saveschematic (name)), and it should reproduce said issue.

The server version I am using is paper 1.16.5, running IridiumSkyblock-3.0.7Dev.jar

Heres a screenshot, if it helps.
[image](https://i.ibb.co/R4BjZg8/2021-07-21-19-40-30.png)

**Comment by MertUnverdi** [comment]
its a known issue we will convert schematics to worldedit
duplicate with #75
