### ISSUE TITLE
Generator Upgrade got reset

### ISSUE THREAD

**Issue by farum12** [Iridium-Development/IridiumSkyblock#311]
**Describe the bug**
The User observed that Generator Upgrade got reset. Level went from 3 to 1.

**To Reproduce**
1. Unknown, as it occured randomly...

**Expected behavior**
Upgrade should not be reset under any circumstances.

**Server Version and Plugin Version**
Server: git-Paper-582 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Plugin: 3.0.7Dev

**Screenshots**
As you can observe - User bought the upgrade, but something occured and it got reset to default state.
![image](https://user-images.githubusercontent.com/56656135/126714581-d5a84a88-fed9-4f8e-9531-80743a0058c2.png)
![image](https://user-images.githubusercontent.com/56656135/126714592-7ee31753-08ec-48e8-a30a-61ecd0c5bff7.png)

**Logs**
I'll send database on Discord to das ist gut, as discussed with SlashRemix.

**Additional context**
The island, which the reset occured on, has ID 19.

**Comment by dlsf** [comment]
Do you know by any chance when the user generated his island and what version of IridiumSkyblock you were running at that time? Such an issue was fixed a few versions ago

**Comment by farum12** [comment]
@dlsf 3.0.7Dev; additionally, it occured today, but in different table - island_bank; his money got reset
![image](https://user-images.githubusercontent.com/56656135/126831677-4c5bf9e9-3d49-4567-80ee-ac7c3f53e8d1.png)

**Comment by dlsf** [comment]
`Dao#createOrUpdate()` appears to check the id of the table, not the island_id. This might be the issue.

**Comment by PeachesMLG** [comment]
Seemsto be something todo with stuff running in async?

**Comment by PeachesMLG** [comment]
Might have fixed it

**Comment by PeachesMLG** [comment]
99% sure its fixed now, will be released in tomorrow's update if not open a new issue report
