### ISSUE TITLE
Missions don't give rewards

### ISSUE THREAD

**Issue by Sixsoul** [Iridium-Development/IridiumSkyblock#313]
**Describe the bug**
Missions don't give any reward like 80% of the time.

**To Reproduce**
1. complete mission
2. claim reward
3. realize that you got no reward, not even in bank

**Expected behavior**
You complete a mission, claim the reward, and it's actually given to you.

** Server Version and Plugin Version**
1.17.1, plugin 3.0.7

**Comment by MertUnverdi** [comment]
there no console errors?

**Comment by Sixsoul** [comment]
nothing in console

**Comment by MertUnverdi** [comment]
we need more clue, so it happens only for you  (hasn't heard this issues before)

**Comment by MertUnverdi** [comment]
no response, will close after 1 days  (if i get forgot it, faun will do it lol)

**Comment by strahil211** [comment]
Having the same issue, not sure what is causing it

**Comment by MertUnverdi** [comment]
> Having the same issue, not sure what is causing it

if you didn't server restarted after then see this issue
Can u send the database?

**Comment by MertUnverdi** [comment]
@strahil211
