### ISSUE TITLE
IridiumSkyblock interfering with hostile mob spawns in the IridiumSkyblock worlds

### ISSUE THREAD

**Issue by Opalinium** [Iridium-Development/IridiumSkyblock#315]
**Describe the bug**
There seems to be an obscure issue with hostile mob spawns in the IridiumSkyblock worlds, in which hostile mobs will unable to be spawned whatsoever (Ex. Commands, spawn eggs, spawners, natural, etc)

This bug occurs at random, and I am unable to determine the cause. 

I singled out Iridium as the cause because I did a binary search of my plugins until only IridiumSkyblock and Vault were left - and this issue only occurs in the IridiumSkyblock worlds.

Testing was also done with a different person, who started a new server with only IridiumSkyblock and Vault - and they confirmed that IridiumSkyblock seemed to be causing issues with hostile mob spawns.

**To Reproduce**
Unknown - This bug seemingly occurs at random, and the exact cause is unknown to me. 
Changing the difficulty will temporarily fix the issue, however it will occur again some time afterwards.

**Expected behavior**
Hostile mob spawning should function as intended.

** Server Version and Plugin Version**
Purpur-1171 (1.16.5)
IridiumSkyblock 3.0.6

**Additional context**
This is a given, but the world difficulty is not peaceful, the gamerule for mobSpawning is not false, and the mob cap has not been reached (not even close)
Mob despawn range is also lower than server render distance

**Comment by dlsf** [comment]
We don't influence mob spawning (except spawners) in any way, please check the biome where mob spawning can't happen, I'd assume that's the issue
