### ISSUE TITLE
Spams no perm message

### ISSUE THREAD

**Issue by CayeOficial** [Iridium-Development/IridiumSkyblock#318]
If you throw an arrow on an island without permission to kill mobs, the arrow doesn't dissapear so it still trying to kill the mob an a message got spammed.
idk if i explain this so good, so an image worth more than 1000 words
https://i.imgur.com/z0unBUR.mp4

**Comment by CayeOficial** [comment]
peaches add a cooldown to the message if you wanna be sexy

**Comment by MertUnverdi** [comment]
isn't cannot fixed with delay
