### ISSUE TITLE
Players lose access to their islands randomly

### ISSUE THREAD

**Issue by Sixsoul** [Iridium-Development/IridiumSkyblock#322]
**Describe the bug**
Players completely lose access to their island. When they use "/island" it tells them "the island already exists"
. When they use "/island delete" it tells them they have no island. This leaves players completely unable to play or do anything without an admin manually editing the database and removing them, and restarting the server.

**To Reproduce**
I honestly have no idea. Doesn't really seem to have any rhyme or reason. Has happened to 5 or 6 players out of 300 unique joins.

** Server Version and Plugin Version**
Plugin version 3.0.7
Server version 1.17.1

As example, I have a player with the issue named GetSuga65.
Here is my database: https://www.dropbox.com/s/fv0lhpglq177wvb/IridiumSkyblock.db?dl=0

**Comment by MertUnverdi** [comment]
i've checked his db and it contains duplicates @PeachesMLG
