### ISSUE TITLE
Island Bank resets randomly

### ISSUE THREAD

**Issue by Sixsoul** [Iridium-Development/IridiumSkyblock#323]
**Describe the bug**
Island bank balances (money, crystals and exp) reset to 0, 0, 0. There is no trackable cause for this but it happens VERY frequently, every player experiencing it periodically.

SOMETIMES, the balances pop back later, again completely randomly with no known trigger, but not always.

**To Reproduce**
Have some crystals, money or exp in bank. Play normally for a bit, maybe earning crystals in whatever way. Balance will eventually 0 out for no discernible reason.

**Expected behavior**
Would be nice to not have all balances reset all the time :P My players are very frustrated.

** Server Version and Plugin Version**
3.0.7, 1.17.1

**Comment by dlsf** [comment]
Are you sure this is still happening with 3.0.7? That version was supposed to fix such issues. 

Maybe there are still duplicate entries in the database 🤔

**Comment by Sixsoul** [comment]
Yes, I've updated and my players are still going crazy about it, haha.

**Comment by Sixsoul** [comment]
Let me add to this one too. Island upgrades are also resetting.

**Comment by PeachesMLG** [comment]
Ye this was fixed in 3.0.7 Are you sure this is still occuring after the update?

**Comment by Sixsoul** [comment]
Yes, 100%. I've only been using 3.0.7 since you guys released it. 

Unless the issues from the previous version last even once you update? Is it not correcting the database or something?

**Comment by PeachesMLG** [comment]
> Yes, 100%. I've only been using 3.0.7 since you guys released it.
> 
> Unless the issues from the previous version last even once you update? Is it not correcting the database or something?

Ah my bad it only fixes the Upgrades duplications, ill write something that fixes all of them

**Comment by EvilInsid** [comment]
im having these problems, what was the fix?
