### ISSUE TITLE
Nether Cant Place blocks

### ISSUE THREAD

**Issue by LukePfister00** [Iridium-Development/IridiumSkyblock#326]
**Describe the bug**
When entering nether through self built portal cant place blocks

**To Reproduce**
1. Build Portal on Island
2. Enter Portal
3. Try place block

**Expected behavior**
Able to get to island

** Server Version and Plugin Version**
Paper 1.17.1
IS V 3.0.7

**Comment by MertUnverdi** [comment]
Are u sure on 3.0.7?

**Comment by dlsf** [comment]
And what exactly is the error? Is there one in the console?

**Comment by LukePfister00** [comment]
There is no physical error in console. it just happens and yes i am sure it is 3.0.7

**Comment by Faun471** [comment]
Please provide a video and be more specific on your server version.

**Comment by LukePfister00** [comment]
> Please provide a video and be more specific on your server version.

Will get one up in a few hours cant hop on the server atm. I have asked my assistants to help me get me a video, the /plugin list and the /version

**Comment by LukePfister00** [comment]
**### See attached images and Vid as promised**

![image](https://user-images.githubusercontent.com/43130096/127689949-51be5f73-03aa-41b4-ab9e-019638f46593.png)
![image](https://user-images.githubusercontent.com/43130096/127690003-dd843070-60fa-4ba1-b036-4647ff28c4ef.png)
![image](https://user-images.githubusercontent.com/43130096/127690091-689e2871-784d-4e6a-a262-665afc24b7be.png)

https://user-images.githubusercontent.com/43130096/127691385-53a99e04-4103-4da0-885c-f3950a50c378.mp4

**Comment by LukePfister00** [comment]
Going to test if Just iridium works properly alone, with essentials and currently using CMI (Which is causing errors) will edit with findings

**Comment by PeachesMLG** [comment]
I dont belive this is todo with Iridium since we send messages when it blocks you placing blocks

**Comment by LukePfister00** [comment]
> I dont belive this is todo with Iridium since we send messages when it blocks you placing blocks

Hmm alright i will run it in multiple test environments to see where the problem originates from

**Comment by Oribuin** [comment]
I cannot reproduce this error personally.
