### ISSUE TITLE
Move items from chest

### ISSUE THREAD

**Issue by CayeOficial** [Iridium-Development/IridiumSkyblock#328]
Players can't move chest items fast
https://cdn.discordapp.com/attachments/742181050926760038/867865177919848500/Minecraft_1.8.9___LabyMod_3.8.53_2021-07-22_22-25-56.mp4
They can't do this ⬆

**Comment by Faun471** [comment]
This is most likely not caused by IridiumSkyblock. Can you try this on a fresh setup - a server with only IridiumSkyblock and its dependencies installed.

And please follow the correct format for creating issues.
