### ISSUE TITLE
Ore Generator doesn't work on Paper 1.8.8 (IS 3.0.7)

### ISSUE THREAD

**Issue by draand28** [Iridium-Development/IridiumSkyblock#329]
**Describe the bug**
Ore Generator doesn't replace the vanilla cobblestone generator on Paper 1.8.8.

**To Reproduce**
Just install the plugin on Paper 1.8.8, leave everything to default values.

**Expected behavior**
It should change the standard cobblestone within the cobblestone generator from only cobblestone to a 3/4 cobble and 1/4 coal ore ratio, but it only generates the cobblestone.  Upgrading the ore generator level doesn't fix the issue (as none of the ores from the default config actually generate).

** Server Version and Plugin Version**
`This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)`

`Plugin Name: IridiumSkyblock
Plugin Version: 3.0.7
Plugin Author: Peaches_MLG
Plugin Contributors: das_, SlashRemix
Plugin Donations: www.patreon.com/Peaches_MLG
`

**Logs**
There are some errors while generating an island or while re-generating it, but I don't think they have anything to do with my issue, as they quote the obfuscate async function (available to 1.17 but non-existent in 1.8).
https://paste.gg/p/anonymous/66205fb218cb469098b5d26bbf17a026

**Additional context**
On Paper 1.17.1 I don't encounter this issue, nor the errors from the above paste.

**Comment by dlsf** [comment]
The ore generator only generates ores starting from level 2, you can upgrade it through /is upgrades.

Does this solve your issue?

**Comment by draand28** [comment]
I have already mentioned that I upgraded my Ore generator level to 3 (maximum default level), but nothing generates except cobblestone. Also, even if I were only at level 1, the default config for 3.0.7 has both STONE and COAL_ORE:
`    1:
      money: 1000
      crystals: 15
      ores:
        STONE: 3
        COAL_ORE: 1
      netherOres:
        BASALT: 1`

**Comment by PeachesMLG** [comment]
Yep the method we are using for ore generators are 1.13+ I believe. we wont be fixing this

**Comment by draand28** [comment]
Then remove the support for all legacy versions from Spigot so people know that this plugin is not compatible with it. Maybe they won't waste their time like I did, thanks.
