### ISSUE TITLE
Console Error on first plugin start

### ISSUE THREAD

**Issue by MineagePvP** [Iridium-Development/IridiumSkyblock#333]
**Describe the bug**
An error appeared in console when i created an island on the newest version

**To Reproduce**

**Expected behavior**
It's not supposed to get an error especially since i did nothing wrong

** Server Version and Plugin Version**
This server is running Hyperion version TacoSpigot (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
 Plugin Name: IridiumSkyblock
 Plugin Version: 3.0.7
 Plugin Author: Peaches_MLG
 Plugin Contributors: das_, SlashRemix
 Plugin Donations: www.patreon.com/Peaches_MLG`

**Screenshots**
N/A

**Logs**
https://pastebin.com/57nCAe36

**Additional context**

**Comment by PeachesMLG** [comment]
This is a duplicate report
