### ISSUE TITLE
Generator Upgrade got reset

### ISSUE THREAD

**Issue by farum12** [Iridium-Development/IridiumSkyblock#345]
**Describe the bug**
The User observed that Generator Upgrade got reset. Level went from 2 to 1.

**To Reproduce**
1. Unknown, as it occured randomly...

**Expected behavior**
Upgrade should not be reset under any circumstances.

** Server Version and Plugin Version**
Server: git-Paper-582 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Plugin: 3.0.8

**Screenshots**
As you can observe - User bought the upgrade, but something occured and it got reset to default state.
![image](https://user-images.githubusercontent.com/56656135/127966979-d7173316-97f8-4ac4-b7a9-76d14f012c6e.png)
![image](https://user-images.githubusercontent.com/56656135/127966992-f7006d81-626d-4a82-869b-442d57f0290b.png)

**Logs**
I can send database file on Discord, PM me - Farum on your Discord server.

**Additional context**
The island, which the reset occured on, has ID 37. Worth to note - there are no duplicates of the same instance of upgrade in the DB.

**Comment by MertUnverdi** [comment]
is seems not duplicated its fine :panda:

**Comment by MertUnverdi** [comment]
this happened again or it was just once?

**Comment by farum12** [comment]
It occurred couple of times. I've reported my DBs to Peaches.

**Comment by MertUnverdi** [comment]
ye is still duplicates, but the plugin is removes them from db
