### ISSUE TITLE
The issues with database and is value still here

### ISSUE THREAD

**Issue by CayeOficial** [Iridium-Development/IridiumSkyblock#346]
**Describe the bug**
No more to say, the issues on database that should be fixed on the last version, stills

** Server Version and Plugin Version**
server: 1.8 
plugin: 3.0.8

**Comment by xReveres** [comment]
@CayeOficial which? link closed issue or something...

**Comment by CayeOficial** [comment]
#305

I think it wont be fixed cause 1.8 is unsupported, but, my skyblovk server are so bugged cause of this bug

**Comment by xReveres** [comment]
I think this issue is not dependent on which server version is running, anyway I wrote what I think about this problem in last message in this issue

**Comment by CayeOficial** [comment]
I've seen your issue. I think Is not the same, read my last comment on #305

**Comment by PeachesMLG** [comment]
duplicate
