### ISSUE TITLE
Using is upgrade breaks and produces console error on 1.16.5 using version 3.0.8

### ISSUE THREAD

**Issue by AlecMcQuarrie** [Iridium-Development/IridiumSkyblock#347]
is upgrade is not working. It produces this error in console:

04.08 01:09:30 [Server] WARN Task #341 for IridiumSkyblock v3.0.8 generated an exception
04.08 01:09:30 [Server] INFO java.lang.NullPointerException: null
04.08 01:09:30 [Server] INFO at com.iridium.iridiumskyblock.gui.UpgradesGUI.addContent(UpgradesGUI.java:39) ~[?:?]
04.08 01:09:30 [Server] INFO at com.iridium.iridiumskyblock.IridiumSkyblock.lambda$null$3(IridiumSkyblock.java:195) ~[?:?]
04.08 01:09:30 [Server] INFO at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
04.08 01:09:30 [Server] INFO at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085) ~[?:?]
04.08 01:09:30 [Server] INFO at com.iridium.iridiumskyblock.IridiumSkyblock.lambda$onEnable$4(IridiumSkyblock.java:192) ~[?:?]
04.08 01:09:30 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
04.08 01:09:30 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1171]
04.08 01:09:30 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503) ~[patched_1.16.5.jar:git-Purpur-1171]
04.08 01:09:30 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
04.08 01:09:30 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
04.08 01:09:30 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
04.08 01:09:30 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
04.08 01:09:30 [Server] INFO at java.lang.Thread.run(Thread.java:829) [?:?]

To reproduce:
Use IS 3.0.8 on purpur/paper 1.16.5

Expected behavior:
Is upgrade should work fine and not produce an error.

**Comment by MertUnverdi** [comment]
Please please and please use paste.gg for errors

**Comment by AlecMcQuarrie** [comment]
Two errors I am getting spammed in console:

https://paste.gg/p/anonymous/a4e6c7c3539b432883e938fa84ae7805

**Comment by xReveres** [comment]
I successfully replicated this issue. In my case I removed all missions from missions.yml
@AlecMcQuarrie Also you can show your missions.yml

**Comment by AlecMcQuarrie** [comment]
Ah, I also have my missions file empty. I will add the empty array to fix it!

**Comment by PeachesMLG** [comment]
> I successfully replicated this issue. In my case I removed all missions from missions.yml
> @AlecMcQuarrie Also you can show your missions.yml
> 
> Edit:
> I found a solution?
> If I left missions.yml like this:
> https://paste.gg/p/anonymous/c201a760c1ea47adae08b802d96ff52c
> Error occured
> 
> But when I left file like this:
> https://paste.gg/p/anonymous/68d306a20cad4f3fa9848384fe44ca47
> Error gone

Ye in the first case your setting missions to null which will cause errors, in the second your setting it to an empty array
