### ISSUE TITLE
Message spammed

### ISSUE THREAD

**Issue by CayeOficial** [Iridium-Development/IridiumSkyblock#349]
**Describe the bug**
If you stand on a preasure plate on an island that you haven't permissions to use redstone, a message got spammed.

**To Reproduce**
1. Stand on a preasure plate on an island that your haven't permissions to use redstone

**Expected behavior**
Should display only one message

** Server Version and Plugin Version**
1.8.8 | 3.0.8

**Screenshots**
https://i.imgur.com/jOoKtuu.mp4

**Additional context**
I know that 1.8.8 are unsupported, but this issue is on all versions of mc

**Comment by PeachesMLG** [comment]
:man_shrugging: dont stand on pressure plates then, not really much we can do about it

**Comment by CayeOficial** [comment]
Add a 1 or 2 seconds cooldown for those message, it wont be spammed in any way
