### ISSUE TITLE
/is home Bug [Luckperm Permission]

### ISSUE THREAD

**Issue by FoxyFoxy67** [Iridium-Development/IridiumSkyblock#354]
If i create my Island with the "default" group i can do /is home (and im teleported),
but if someone change me in "premium" group, i can't go on my island.

1. Check your role 
2. Create your island
3. is home [Functionning]
4. Go To spawn
5. Change your Role to (for example "Premium")
6. Do /is home (and see , you not teleported to your island)
7. Hand in your role before the changes
8. Do /is home (and you are teleported to your island)

**Expected behavior**

** Server Version and Plugin Version**
Iridium Skyblock 3.0.8 (latest)
PaperMC: This server is running Paper version git-Paper-137 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: a67959e) You are 28 version(s) behind

**Screenshots**
-- No Screenshots --

**Logs**
-- No errors in console --

**Comment by MertUnverdi** [comment]
oh tf

**Comment by MertUnverdi** [comment]
isn't related to iridium check your permissions on command.yml or another issue idk
