### ISSUE TITLE
EnderDragon spawn 

### ISSUE THREAD

**Issue by DoctaEnkoda** [Iridium-Development/IridiumSkyblock#361]
**Describe the bug**
The first island spawns the enderdragon as well as the enderdragon hotel 

**To Reproduce**
1. Be first island
2. Create EnderPortal
3. Teleport End Island

**Expected behavior**
Don't spawn the EnderDragon and destroy the island

** Server Version and Plugin Version**
"/version"
```
[14:00:48 INFO]: Checking version, please wait...
>....[14:00:49 INFO]: This server is running Purpur version git-Purpur-1329 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d1d6bc2 on ver/1.17.1)
>....[14:00:49 INFO]: You are 1 version(s) behind
```

"/is about"
```
Plugin Name: IridiumSkyblock
>....[14:01:21 INFO]: Plugin Version: 3.0.8
>....[14:01:21 INFO]: Plugin Author: Peaches_MLG
>....[14:01:21 INFO]: Plugin Contributors: das_, SlashRemix
>....[14:01:21 INFO]: Plugin Donations: www.patreon.com/Peaches_MLG
```
![image](https://user-images.githubusercontent.com/26461373/129354321-4da979b5-bbd4-4d62-9be1-8f90e3583543.png)

**Comment by MertUnverdi** [comment]
fixed with #432
