### ISSUE TITLE
Iridium Skyblock generates void world, but in some places it's not a void

### ISSUE THREAD

**Issue by SlaVistaPL** [Iridium-Development/IridiumSkyblock#363]
**Describe the bug**
as stated in title, Iridium Skyblock when generates the world for islands doesn't make the desired world completely void, in some places it's a normal world

**To Reproduce**
1. install plugin and configure it
2. restart the server
3. invite some people to your server and let them make islands for themselves till they won't see the normal world

**Expected behavior**
Iridium Skyblock creates a completely void world desired for skyblock islands.

**Server Version and Plugin Version**
This server is running Purpur version git-Purpur-1255 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
Plugin version is 3.0.6

**Screenshots**
![2021-08-16_12 58 48](https://user-images.githubusercontent.com/53293133/129553686-5c13a083-4c2a-4b22-a18b-39968f984796.png)
(actual behavior)

![2021-08-16_13 00 26](https://user-images.githubusercontent.com/53293133/129553828-7f579036-1931-46c8-a22a-3ddee2689179.png)
(expected behaviour)

**Logs**
none

**Additional context**
none

**Comment by dlsf** [comment]
You weren't reloading the server? Can you send a list of your plugins?

**Comment by SlaVistaPL** [comment]
I use these plugins:
![image](https://user-images.githubusercontent.com/53293133/129888642-29f6148f-46ff-4a3f-9741-edadca4d30fc.png)

**Comment by dlsf** [comment]
And did you reload the server?

**Comment by SlaVistaPL** [comment]
(Sorry for late response, I was busy back then)

Yes, I did many restarts but it didn't bring any effect.

**Comment by dlsf** [comment]
@PeachesMLG any ideas?

**Comment by MertUnverdi** [comment]
if "restart" means is "/reload" it just brokes plugins did you this? Or just stopped and started again? (Nothing for /is reload it doesn't broke plugin)
Sorry for late response i was forgot :(

**Comment by SlaVistaPL** [comment]
I was actually restarting the whole server, not reloading the plugins.

**Comment by dlsf** [comment]
Without any exception? I'm just thinking about cases where the world can generate but IridiumSkyblock is disabled, maybe when the server is stopping?
