### ISSUE TITLE
Problem with stacked blocks

### ISSUE THREAD

**Issue by CayeOficial** [Iridium-Development/IridiumSkyblock#365]

**Comment by PeachesMLG** [comment]
This doesnt help at all, open a new issue and follow the format

**Comment by CayeOficial** [comment]
I was trying to open an issue on SuperiorSkyblock2 GitHub, but I'm crazy and I opened it here for error, idk where is the button to delete the issue so I decided to remove the description, check edited message, sorry but SuperiorSkyblock2 is better for me 🙇

**Comment by MertUnverdi** [comment]
good for u 👍🏻
