### ISSUE TITLE
Sqlite cannot be converted to Mysql normally

### ISSUE THREAD

**Issue by 28451553** [Iridium-Development/IridiumSkyblock#366]
Sqlite cannot be converted to Mysql normally

https://paste.helpch.at/raw/akasasarod
https://paste.helpch.at/raw/umokesifan

Already on discord for help
But the staff can't help me...

**Comment by PeachesMLG** [comment]
https://stackoverflow.com/questions/163079/exporting-from-sqlite-to-sql-server

**Comment by dlsf** [comment]
I'll work on an automatic solution when I have the time
