### ISSUE TITLE
island name conflict

### ISSUE THREAD

**Issue by 28451553** [Iridium-Development/IridiumSkyblock#367]
**Describe the bug**
island name conflict

**To Reproduce**
When PLAYER1 is transferred to PLAYER2 island PLAYER1 creates another island after exiting the empty island He will show the island name conflict 

**Expected behavior**
fix it

** Server Version and Plugin Version**
Tuinity 1.16.5-R0.1 SNAPSHOT
Iridium Skyblock 3.0.8

**Screenshots**

**Logs**
https://paste.helpch.at/raw/hatexagela

**Comment by dlsf** [comment]
Duplicate of #362
