### ISSUE TITLE
Daily missions missing | Can't enter nether

### ISSUE THREAD

**Issue by Cnzw** [Iridium-Development/IridiumSkyblock#369]
**Describe the bug**

1. /is missions DAILY panel not show all daily missions.
All daily missions format are correct, even I try the original missions.yml, it still can't show all mission.
Every players may show different quantity daily missions.
No error in console or in game.
ONCE missions are working normal.
I try it in 1.13.2, same problem as 1.12.2.

~~2. Mission conditions like FISH:ANY:20 and MINE:OAK_LOG:64 no effect.~~

 ~~3. Can't withdrew and deposited money in Bank~~

4. Can't enter nether
Build a nether portal and teleport to nether is ok. But player teleport to the bottom of world, and trigger void teleport back to main island. So Can never play normally in nether.
I using multiverse teleport to IridiumSkyblock_nether, the schematics generate normally. No matter where I create nether portal, it will teleport to the bottom of world, and trigger void teleport again.
I try enter nether in 1.13.2 paper, with original config and database. It still work like 1.12.2, trigger void teleport.

**To Reproduce**
Config file contents in the Additional context. (For a good reading experience)

** Server Version and Plugin Version**
server version: 1.12.2 paper
plugin version: 3.0.8
economy plugin: [XConomy](https://www.spigotmc.org/resources/xconomy.75669/)

**Screenshots**
I will upload screenshots if needed

**Logs**
none

**Additional context**
Please forgive my poor English.

missions.yml:
https://paste.gg/p/Cnzw/6785c18a01324e95b2b04bac06bbaf80

inventories.yml
https://paste.gg/p/Cnzw/fed6a7c5016c4921936748bf9ad97bfa

**Comment by MertUnverdi** [comment]
don't paste configs to here use paste.gg ..

**Comment by MertUnverdi** [comment]
also needed the server version tho

**Comment by MertUnverdi** [comment]
and for about bank issue this plugin is depends vault but if you want withdraw/deposit money to bank it requires an economy plugin installed
Vault is only holder isn't economy plugin you need to download plugin like essentials

**Comment by Milan1026** [comment]
I have the same issue with the daily missions, only 2 of the 4 missions are showing. I'm using the pinned version on #support channel on Discord.
