### ISSUE TITLE
Error in console -> Legacy Material Support  

### ISSUE THREAD

**Issue by PatalJunior** [Iridium-Development/IridiumSkyblock#370]
**Describe the bug**
[[STDERR] ] org.bukkit.craftbukkit.v1_17_R1.legacy.CraftLegacy Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!

**To Reproduce**
1. Install the plugin on the plugins folder
2. Start server
3. Console prints error

**Expected behavior**
Not use Legacy Material Support ?

**Server Version and Plugin Version**

This server is running Paper version git-**Paper-196** (**MC: 1.17.1**) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 59d449d)

Plugin Version: **3.0.8**

**Screenshots**
![image](https://user-images.githubusercontent.com/81658559/130207445-705cd854-0908-4254-9312-3b7fb905506a.png)

**Logs**
https://paste.gg/p/anonymous/576192fae98c4b20abf1631b783b5a45

**Comment by dlsf** [comment]
This is not a bug but is necessary for backward compatibility. Consider IridiumSkyblock to be a "legacy plugin".
