### ISSUE TITLE
Biomes not working 100%

### ISSUE THREAD

**Issue by Milan1026** [Iridium-Development/IridiumSkyblock#372]
Greetings

**Describe the bug**
- When creating a Skyblock Island, the biome is different than the one put in the schematics.yml file. After regenerating, it seems to generate the biome correctly (not always).

**To Reproduce**
1. Create an Island.
2. Check the Island's biome.
(3. Regen the Island.)
(4. Check the Island's biome.)

**Expected behavior**
- The biomes should be the same as the ones put in the schematics.yml file upon creating the Island.

** Server Version and Plugin Version**
Copy and paste the results of `/version` and `/is about`

- Version: This server is running Paper version git-Paper-771 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 15 version(s) behind
Previous version: git-Paper-"ae892dc" (MC: 1.16.5)

- Plugin version; 3.0.8 (pinned version in support channel on Discord).

**Screenshots**
- Isn't really necessary concerning this issue in my opinion.

**Logs**
If there are error messages in your console, please send them via [this](https://paste.gg/)
- There are no errors.

**Additional context**
- I have explained everything already.

Thanks in advance
Milan

**Comment by Faun471** [comment]
Try these steps:
1. Change the biome
2. do /is regen
3. once the island is regenerated, leave and rejoin the server/world (the chunk has to be unloaded)

If the biomes are still inaccurate, then it's a bug, if it's accurate, then it isn't.

I did these steps like 5 times in a row, and couldn't replicate the issue you were having

**Comment by Milan1026** [comment]
Like I said, regenerating mostly fixes it. But I imagined we aren't really meant to always have to regen our island when creating it. However, I've noticed when leaving the island and going back fixes it too.

**Comment by MertUnverdi** [comment]
he said to see if it fixed or not

**Comment by Milan1026** [comment]
> he said to see is fixes it or not

Yes, it fixes it.

**Comment by MertUnverdi** [comment]
i now checking the method but everything is same how this happens idk

**Comment by MertUnverdi** [comment]
i have a idea but not sure could i join ur server for testing it?

**Comment by Milan1026** [comment]
> i have a idea but not sure could i join ur server for testing it?

Yes sure, wanna do it now?

**Comment by MertUnverdi** [comment]
let me on discord @SlashRemix :panda:
