### ISSUE TITLE
Armor stand access 

### ISSUE THREAD

**Issue by Darkside247** [Iridium-Development/IridiumSkyblock#373]
**Describe the bug**
even when visitors access is removed they can still interact with armor stands.
**To Reproduce**
1. Go to 'Your island'
2. Click on 'Place an armor stand and have a island visitors come one'
3. Scroll down to 'have the visitors play with the island armor stand'
4. See error they steel all your stuff from armor stands 

**Expected behavior**
them not to interact with armor stands 
** Server Version and Plugin Version**
Copy and paste the results of `/version` and `/is about`
latest - none of the commands provided work 
**Screenshots**

**Logs**
If there are error messages in your console, please send them via [this](https://paste.gg/)

**Additional context**

**Comment by PeachesMLG** [comment]
Added interact permissions

**Comment by Darkside247** [comment]
This fix did not work you are still able to remove items from armor stands without permissions

**Comment by dlsf** [comment]
Unfortunately, Spigot is dumb and interactions don't include armorstands.

**Comment by MertUnverdi** [comment]
Ye i was told it -_- its have another event

**Comment by Darkside247** [comment]
If it helps its why I use paper lol

**Comment by PeachesMLG** [comment]
Ok there its fixed >:C
