### ISSUE TITLE
Players stuck in void when deleting Island

### ISSUE THREAD

**Issue by Milan1026** [Iridium-Development/IridiumSkyblock#375]
Dear IridiumSkyblock staff, I found an issue;

**Describe the bug**
* When a player deletes it's island while on the island, the player gets teleported to the server lobby (essentials /spawn) which is in a different world than the Skyblock worldgroup. When the player goes back to Skyblock, that player is stuck in an endless loop of falling into the void because it's the player's last known location in that world.

**To Reproduce**
* Check above. You need to use Essentials and last_location option (Multiverse-Inventories).

**Expected behavior**
* The player should not be stuck in the void.  (A way to change the spawn?)

** Server Version and Plugin Version**
Copy and paste the results of `/version` and `/is about`
* Version: This server is running Paper version git-Paper-771 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 16 version(s) behind
Previous version: git-Paper-"ae892dc" (MC: 1.16.5)

* Plugin version; 3.0.8 (pinned version in support channel on Discord).

**Screenshots**
/

**Logs**
If there are error messages in your console, please send them via [this](https://paste.gg/)
/

**Additional context**
/

Thanks in advance
Milan

**Comment by djraymond** [comment]
just do /spawn

**Comment by MertUnverdi** [comment]
Lol

**Comment by Milan1026** [comment]
> just do /spawn

Bro what. Players are moving non-stop when stuck in the void so it won't teleport them.

**Comment by dlsf** [comment]
How exactly does the player go back to Skyblock? Does he visit another island? If so he should be teleported to the island correctly.

**Comment by Milan1026** [comment]
> How exactly does the player go back to Skyblock? Does he visit another island? If so he should be teleported to the island correctly.

The player goes back to skyblock with /warp skyblock. 

The point is that the island gets deleted so the player indeed teleports to the last known location (the island), but the island doesn't exist anymore. That's why the player gets stuck in an endless loop of falling into the void.

**Comment by MertUnverdi** [comment]
Use bungee its better way to fix

**Comment by Milan1026** [comment]
> Use bungee its better way to fix

I know but I can't since I'm hosting via Minehut.

**Comment by MertUnverdi** [comment]
Why is there /warp skyblock ?

**Comment by MertUnverdi** [comment]
oh is for spawning to skyblock server's spawn

**Comment by MertUnverdi** [comment]
So, when player deleted island, iridium teleports player to main spawn(hub) then player execute /warp skyblock it teleports to void instead skyblock spawn

**Comment by Milan1026** [comment]
> oh is for spawning to skyblock server's sp

> So, when player deleted island, iridium teleports player to main spawn(hub) then player execute /warp skyblock it teleports to void instead skyblock spawn

Yes, that's it. I think the new update was meant to be able to configure the Skyblock spawn. That also didn't work. (So when executing /is delete it should teleport the player to the Skyblock spawn instead of main spawn).

**Comment by MertUnverdi** [comment]
How we can do it? With a custom version for u ?? Or changing everything for u ???

**Comment by MertUnverdi** [comment]
I don't think its related to iridium 
/warp skyblock is teleports to wrong location we can't change it

**Comment by Milan1026** [comment]
> How we can do it? With a custom version for u ?? Or changing everything for u ???

I have no idea. Maybe an option to be able to change the world to spawn in when using Multiverse (-Inventories). Or executing /mvspawn (teleports the player to the same world's spawn (Multiverse)) instead of to the /spawn.

But if I'm the only one experiencing this issue you shouldn't put too much effort in it. Thank you very much for trying to help though.

**Comment by Milan1026** [comment]
> I don't think its related to iridium
> /warp skyblock is teleports to wrong location we can't change it

You're right, it's not directly related to Iridium. It's because of Multiverse-Inventories' last_location option, which teleports players to their last location in a world(group) upon entering that world.

**Comment by MertUnverdi** [comment]
is still seems about ur side i'll close issue if you're confirm it 
But i have an idea for fixing it:
Remove EssentialsSpawn we will teleport players to spawn location of your selected world (its on config.yml `spawnWorld`) set it to skyblock's spawn

But you will need a /spawn plugin for making players can go lobby
idk what u can do for this but there too much options for that :panda:

**Comment by Milan1026** [comment]
> is still seems about ur side i'll close issue if you're confirm it
> 
> But i have an idea for fixing it:
> Remove EssentialsSpawn then we will teleport players to spawn location of your selected world (its on config.yml `spawnWorld`) set it to skyblock's spawn world and set world's spawn location with multiverse or /setworldspawn command
> 
> But you will need a /spawn plugin for making players can go lobby
> idk what u can do for this but there too much options for that :panda:

Yes, you can close it. Seems like a good idea. I will try removing EssentialsSpawn and making a custom /spawn command with Skript.

**Comment by Milan1026** [comment]
> > is still seems about ur side i'll close issue if you're confirm it
> > But i have an idea for fixing it:
> > Remove EssentialsSpawn then we will teleport players to spawn location of your selected world (its on config.yml `spawnWorld`) set it to skyblock's spawn world and set world's spawn location with multiverse or /setworldspawn command
> > But you will need a /spawn plugin for making players can go lobby
> > idk what u can do for this but there too much options for that :panda:
> 
> Yes, you can close it. Seems like a good idea. I will try removing EssentialsSpawn and making a custom /spawn command with Skript.

I tried it and it fixed it. Thank you very much!

**Comment by MertUnverdi** [comment]
Great! <3
