### ISSUE TITLE
Island Border displays in different worlds

### ISSUE THREAD

**Issue by GabryVero** [Iridium-Development/IridiumSkyblock#376]
**Bug Description**
Hi, I have a problem with this plugin.
I'll start by saying that a good plugin.
My server has multiple worlds with various modes like skyblock.
But if I go for example in kitpvp and someone kills me, this happens to me.
(look at the screenshot
![2021-08-29_21 14 54](https://user-images.githubusercontent.com/89747917/131263155-70fe6469-52bb-4b57-84f0-e31755172c4d.png)
)

**Expected behavior**

** Server Version and Plugin Version**
Server version: 1.17.1
Plugin version: 3.0.8

**Additional context**

**Comment by TheHappyHopper** [comment]
Im having this same issue with 3.0.9, island upgrades keep resetting

**Comment by dlsf** [comment]
The upgrade issues have been fixed in #384

**Comment by MertUnverdi** [comment]
> The upgrade issues have been fixed in #384

no didn't

**Comment by MertUnverdi** [comment]
could you confirmed its fixed with 3.1.1  @TheHappyHopper @GabryVero ?

**Comment by GabryVero** [comment]
Yes It fixed, but now I respawn in the Island home and not in the spawn of world

**Comment by dlsf** [comment]
Please open a new issue for that if there isn't already one
