### ISSUE TITLE
problem with mysql

### ISSUE THREAD

**Issue by Meowlan** [Iridium-Development/IridiumSkyblock#379]
when i try to start the server the plugin disables it self and i cant seem to fix it.
https://pastebin.com/Pp8ndEuY -log
please help!

edit: it also doesnt create any tables on mysql im pretty new to mysql so please dont laugh at me 
it works just fine when i use sqlite

**Comment by PeachesMLG** [comment]
It means its failing to connect to your sql database, possibly the wrong ip or port or password, this isnt an issue with the plugin
