### ISSUE TITLE
Sticky pistons 

### ISSUE THREAD

**Issue by Darkside247** [Iridium-Development/IridiumSkyblock#380]
**Describe the bug**
People being able to use more pistons then allowed in block limits by using sticky pistons,

**To Reproduce**
1. Go to '...' island place down pistons till you hit your limit 
2. Click on '....'place down sticky pistons and place more then you are meant to be able to 

**Expected behavior**
Sticky pistons to be limited via the piston limit 
** Server Version and Plugin Version**
Copy and paste the results of `/version` and `/is about`
Latest 
**Screenshots**

**Logs**
If there are error messages in your console, please send them via [this](https://paste.gg/)

**Additional context**

**Comment by PeachesMLG** [comment]
Not really a bug, since Piston's and StickyPistons are different blocks
