### ISSUE TITLE
Crystals are depositing as experience

### ISSUE THREAD

**Issue by SlaVistaPL** [Iridium-Development/IridiumSkyblock#381]
**Describe the bug**
In 3.0.9 a crystal deposit/withdrawal system was introduced. But when you try to deposit your crystals, it shows that an experience was deposited and you can't get your crystals back.

**To Reproduce**
1. Run /is command (or /is bank)
2. When in main menu, select Bank section
3. Deposit some crystals
4. Observe the chat

**Expected behavior**
Crystals can be deposited and withdrew back.

** Server Version and Plugin Version**
This server is running Purpur version git-Purpur-1255 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
Plugin version is 3.0.9

**Screenshots**
Actual behavior: https://whenthe.imposter-is-s.us/imgs/D1jsY0rd

**Logs**
None

**Additional context**
None

**Comment by dlsf** [comment]
Fixed by #378
