### ISSUE TITLE
Making an island private kicks the person who made it private

### ISSUE THREAD

**Issue by joshwenke** [Iridium-Development/IridiumSkyblock#382]
**Describe the bug**
When you do /is private, you YOURSELF will get sent off the Island instead of everyone else

**To Reproduce**
1. Type /is private while someone is visiting your public Island
2. Watch as you are teleported off the island instead of them

**Expected behavior**

** Server Version and Plugin Version**
Copy and paste the results of `/version` and `/is about`
3.0.9

**Screenshots**

**Logs**
If there are error messages in your console, please send them via [this](https://paste.gg/)

**Additional context**

**Comment by MertUnverdi** [comment]
it shouldn't be possible we're checking is trusted or island member, r u sure?
