### ISSUE TITLE
youHaveBeenExpelled Lang entry doesn't replace the variable %kicker%

### ISSUE THREAD

**Issue by joshwenke** [Iridium-Development/IridiumSkyblock#383]
**Describe the bug**

In messages.yml, the youHaveBeenExpelled Lang entry doesn't properly replace the variable %kicker%, it just shows up as %kicker%

**To Reproduce**
1. Run /is expel

**Expected behavior**

** Server Version and Plugin Version**
Copy and paste the results of `/version` and `/is about`
3.0.9

**Screenshots**

**Logs**
If there are error messages in your console, please send them via [this](https://paste.gg/)

**Additional context**

**Comment by MertUnverdi** [comment]
Use %player% instead sorry for this typo

**Comment by MertUnverdi** [comment]
its my dumb fault :(
