### ISSUE TITLE
Syntax message doesn't work for /is rename

### ISSUE THREAD

**Issue by joshwenke** [Iridium-Development/IridiumSkyblock#386]
**Describe the bug**

Setting the "syntax" value in commands.yml doesn't display the custom when doing /is rename without an argument. It does work for other commands.

Screenshot attached
![image](https://user-images.githubusercontent.com/1607041/131914277-5f215c20-fcf4-4f5e-85a3-2d2a3fd8a8c1.png)

**Comment by dlsf** [comment]
Rename is the first argument in that list, therefore it is shown in-game. What exactly is wrong with that screenshot?

**Comment by PeachesMLG** [comment]
No, it seems for some reason we hard coded the /is rename https://github.com/Iridium-Development/IridiumSkyblock/blob/master/src/main/java/com/iridium/iridiumskyblock/commands/RenameCommand.java#L36

**Comment by joshwenke** [comment]
This is also broken for /is transfer, the syntax error message is hardcoded in
