### ISSUE TITLE
give crystals command not working 

### ISSUE THREAD

**Issue by DefaultVic** [Iridium-Development/IridiumSkyblock#393]
Every time I type /is givecrystals {name} {amount} it says  unknown command, wondering why this Is happening and if there is a possible fix?

**Comment by MertUnverdi** [comment]
damn it there no givecrystal command do /is bank give

**Comment by MertUnverdi** [comment]
Peoples always says "not working" never read the wiki..

**Comment by DefaultVic** [comment]
thank you :D
