### ISSUE TITLE
2 questions in a row

### ISSUE THREAD

**Issue by Aadi-mone** [Iridium-Development/IridiumSkyblock#394]
**1. is there a way to set the border off as default?

2. and is there a way to change the maps for the SkyBlock?**

**Comment by MertUnverdi** [comment]
here isn't for questions 👍🏻

**Comment by MertUnverdi** [comment]
https://discord.com/invite/6HJ73mWE7P

**Comment by Aadi-mone** [comment]
I don't have discord sorry :(

**Comment by dlsf** [comment]
1. Yes, in the border.yml
2. Yes, mark the corners of an island with /is pos <1/2> and save the schematic with /is saveschematic <Name>. You can then use it in the schematics.yml

Please create a Discord account for further question
