### ISSUE TITLE
Missions are broken

### ISSUE THREAD

**Issue by Chase0410** [Iridium-Development/IridiumSkyblock#395]
**Bug Description**
Mission fails to update and doesn't keep track of things such as Break/Craft/Grow

**To Reproduce**
Try to complete the *Crafting* quest, or the *Lumberjack* quest. 
Crafting a crafting table updates the mission, but nothing else does.

**Expected behavior**
Should update the number as it goes to give me a count of how many items have been broken/crafted/grown

**Server Version and Plugin Version**
Spigot 1.17.1 & 3.1.1

**Additional Context**
I have a video posted in the discord regarding this issue.

**Comment by Darkside247** [comment]
Is there a fix for this yet?

**Comment by SammyInMinecraft** [comment]
me too plz fix this

**Comment by MertUnverdi** [comment]
its a confirmed issue so wait for next update 👍🏻

**Comment by SammyInMinecraft** [comment]
thanks!

**Comment by PeachesMLG** [comment]
Fixed by: https://github.com/Iridium-Development/IridiumSkyblock/pull/412

**Comment by Darkside247** [comment]
How has this been fixed when there has been no update to fix it

**Comment by Darkside247** [comment]
How has this issue been fixed when no update has been released
