### ISSUE TITLE
Inventory full, but withdraws anyway your balance when you buy something in the store.

### ISSUE THREAD

**Issue by OtakuNL** [Iridium-Development/IridiumSkyblock#402]
**Describe the bug**
Inventory full, but withdraws anyway your balance.

**To Reproduce**
1. Fill up your inventory
2. Buy a item and you will see that it will withdraw anyway.

**Expected behavior**
Give only error that your inventory is full and no withdraws from your balance.

** Server Version and Plugin Version**
This server is running Paper version git-Paper-251 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 5960af9)
You are 8 version(s) behind 

![Capture](https://user-images.githubusercontent.com/90635403/133114378-74288347-0842-4d5d-a967-f158148447d3.JPG)

**Comment by Oribuin** [comment]
I patched in that PR, One of the other nerds can merge it (I'm looking at you @PeachesMLG)

**Comment by MertUnverdi** [comment]
@Oribuin for next time just link the issue :succes: (dum)
