### ISSUE TITLE
/is border and /is bank empty on default

### ISSUE THREAD

**Issue by srnyx** [Iridium-Development/IridiumSkyblock#406]
**Describe the bug**
`/is border` and `/is bank` are both completely filled with gray stained glass panes (none of the items that should be there are there).

**Server Version and Plugin Version**
- SERVER: This server is running Purpur version git-Purpur-1346 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: a2fb41a on ver/1.17.1)
- IS: v3.1.1

**Screenshots**
![img](https://srnyx-is.super-cool.xyz/r/ktqlel8tw9a.png)

**Additional context**
Changing this from `inventories.yml` fixed both of them (they are the only two that have this):
```yml
    items:
      9: null
```
_Path: `bankGUI.background.items` and `islandBorder.background.items`_

Changing it to this fixes it:
```yml
    items: {}
```

**Comment by MertUnverdi** [comment]
U shouldn't set anything to null its broke the plugin

**Comment by srnyx** [comment]
> U shouldn't set anything to null its broke the plugin

I never set anything to `null`, it was like that by default

**Comment by MertUnverdi** [comment]
its cannot be by default, we're using it for all guis how can be only exist only two guis?
Its just weird idk why happened to u :panda:

**Comment by MertUnverdi** [comment]
i never heard before this issue im also idk how happened

**Comment by MertUnverdi** [comment]
Could you check log files any errors about this? May we forgetting something

**Comment by srnyx** [comment]
Figured out this was cause I messed up when replacing materials in `inventories.yml`
