### ISSUE TITLE
Make it easier to edit the source code for config files

### ISSUE THREAD

**Issue by srnyx** [Iridium-Development/IridiumSkyblock#408]
Right now, it's impossible (at least I think so, not a huge coder) to add comments to the config files. It'd be a lot better if they were in `.yml` format, like most other plugin source codes, so that it's easier for people to edit them, and so that comments can be added.

**Comment by MertUnverdi** [comment]
Sorry we're using a custom yml loader instead bukkit's so isn't possible our side :( Also we has suggestions channel on discord

**Comment by srnyx** [comment]
> Sorry we're using a custom yml loader instead bukkit's so isn't possible our side :( Also we has suggestions channel on discord

So there isn't any way to add comments?

**Comment by MertUnverdi** [comment]
i don't think so @PeachesMLG @dlsf anyway?

**Comment by PeachesMLG** [comment]
no
