### ISSUE TITLE
Island crystals can't be redeemed in hand with an empty slot and it display message

### ISSUE THREAD

**Issue by Farmeurimmo** [Iridium-Development/IridiumSkyblock#410]
When I'm trying to redeem crystals from bank, my player hand is empty, the plugin give me the crystals and taking it back and display the message "You have redeem 1 crystals from your bank" but I didn't got it.
But with my player hand in another slot I can redeem crystals without any problems.

**Comment by PeachesMLG** [comment]
not sure I can replicate this? If the crystal is in my offhand it just does nothing for me, can you send a video explaining it?

**Comment by Farmeurimmo** [comment]
Bug patched, I just needed to restart my server
