### ISSUE TITLE
MySQL support

### ISSUE THREAD

**Issue by untuned** [Iridium-Development/IridiumSkyblock#42]
Attempting to put in `MYSQL` or `MARIADB` brings back an error saying that the jdbc connector is invalid. I believe it is because that expects the type to be `mysql` fully lowercase as it *does* connect, but the plugin disables itself before it can actually create the tables.

**Comment by JakeyPrime** [comment]
Also having this issue when trying to setup mysql or maria

**Comment by PeachesMLG** [comment]
on 3.0.0?

**Comment by JakeyPrime** [comment]
Yep, at least for me, compiled from here about 2 hours before this issue was created.
