### ISSUE TITLE
No schematics showing up on /is create

### ISSUE THREAD

**Issue by kingelectrixgyt** [Iridium-Development/IridiumSkyblock#435]
Server version: 1.15.2
Java version 11
I have just updated to the latest version from an older version 2.4.4 of this plugin i have world edit and world guard for my server version and when I do /is create it brings up the gui but no schematics to choose from are there ill link the schematics.yml here: https://pastebin.com/qXUYPecY

**Comment by kingelectrixgyt** [comment]
![2021-10-04_23 53 30](https://user-images.githubusercontent.com/38532714/135957532-bd15240c-e474-4e1e-9fb5-40ac8448ed80.png)

**Comment by PeachesMLG** [comment]
Any errors in the console? try resetting all your configs
