### ISSUE TITLE
Takes 10+ minutes to shutdown / saves twice

### ISSUE THREAD

**Issue by srnyx** [Iridium-Development/IridiumSkyblock#441]
**Describe the bug**
Iridium takes more than 10 minutes to shutdown, which causes my sever to just give up and terminate/kill.

**To Reproduce**
I was unable to reproduce this, but I'm 99% certain it's cause of the data.

**Expected behavior**
Iridium should've shutdown normally and allowed the sever to shutdown normally.

** Server Version and Plugin Version**
Server: Purpur 1402 1.17.1
Iridium: 3.1.2
Using MySQL as my data source for Iridium.

**Comment by dlsf** [comment]
Can you please send the log from after you stopped the server?

**Comment by srnyx** [comment]
> Can you please send the log from after you stopped the server?

https://paste.srnyx.xyz/oguwujamuz.md

**Comment by MertUnverdi** [comment]
isn't possible 10 minutes we haven't any data or something too much prob isn't due to iridiumsykblock

**Comment by MertUnverdi** [comment]
is it fixed?

**Comment by srnyx** [comment]
> is it fixed?

No

**Comment by srnyx** [comment]
Can this be reopened? https://github.com/Iridium-Development/IridiumSkyblock/pull/507 unfortunately didn't fix the issue and it still takes 10+ minutes to save all the data.

**Comment by MertUnverdi** [comment]
Share results

**Comment by PeachesMLG** [comment]
tf how? if its still taking 10 minutes to shutdown, its probabbly an issue with your servers

**Comment by srnyx** [comment]
> tf how? if its still taking 10 minutes to shutdown, its probabbly an issue with your servers

Keep in mind that I have around 2,000 islands

**Comment by srnyx** [comment]
> Share results

I'm not sure what you mean by this

**Comment by DoctaEnkoda** [comment]
I think the IslandLogs table is very slow. It must be very heavy

**Comment by DoctaEnkoda** [comment]
```CMD
[07:09:03 INFO]: [IridiumSkyblock] Sauvegarde des Islands
[07:09:05 INFO]: [IridiumSkyblock] Sauvegarde des Invites
[07:09:05 INFO]: [IridiumSkyblock] Sauvegarde des Permissions
[07:09:07 INFO]: [IridiumSkyblock] Sauvegarde des Blocks
[07:11:05 INFO]: [IridiumSkyblock] Sauvegarde des Spawners
[07:11:07 INFO]: [IridiumSkyblock] Sauvegarde des Banks
[07:11:11 INFO]: [IridiumSkyblock] Sauvegarde des Missions
[07:11:12 INFO]: [IridiumSkyblock] Sauvegarde des Reward
[07:11:12 INFO]: [IridiumSkyblock] Sauvegarde des Upgrades
[07:11:19 INFO]: [IridiumSkyblock] Sauvegarde des Confiances
[07:11:19 INFO]: [IridiumSkyblock] Sauvegarde des Booster
[07:11:22 INFO]: [IridiumSkyblock] Sauvegarde des Warps
[07:11:22 INFO]: [IridiumSkyblock] Sauvegarde des Logs
[07:13:22 INFO]: [IridiumSkyblock] Sauvegarde des Bans
[07:13:22 INFO]: [IridiumSkyblock] Sauvegarde des Settings
[07:13:31 INFO]: [IridiumSkyblock] Fin des sauvegardes
```

I'm just add sout :
```Java
       System.out.println("Sauvegarde des Users");
        getDatabaseManager().getUserTableManager().save();
        System.out.println("Sauvegarde des Islands");
        getDatabaseManager().getIslandTableManager().save();
        System.out.println("Sauvegarde des Invites");
        getDatabaseManager().getIslandInviteTableManager().save();
        System.out.println("Sauvegarde des Permissions");
        getDatabaseManager().getIslandPermissionTableManager().save();
        System.out.println("Sauvegarde des Blocks");
        getDatabaseManager().getIslandBlocksTableManager().save();
        System.out.println("Sauvegarde des Spawners");
        getDatabaseManager().getIslandSpawnersTableManager().save();
        System.out.println("Sauvegarde des Banks");
        getDatabaseManager().getIslandBankTableManager().save();
        System.out.println("Sauvegarde des Missions");
        getDatabaseManager().getIslandMissionTableManager().save();
        System.out.println("Sauvegarde des Reward");
        getDatabaseManager().getIslandRewardTableManager().save();
        System.out.println("Sauvegarde des Upgrades");
        getDatabaseManager().getIslandUpgradeTableManager().save();
        System.out.println("Sauvegarde des Confiances");
        getDatabaseManager().getIslandTrustedTableManager().save();
        System.out.println("Sauvegarde des Booster");
        getDatabaseManager().getIslandBoosterTableManager().save();
        System.out.println("Sauvegarde des Warps");
        getDatabaseManager().getIslandWarpTableManager().save();
        System.out.println("Sauvegarde des Logs");
        getDatabaseManager().getIslandLogTableManager().save();
        System.out.println("Sauvegarde des Bans");
        getDatabaseManager().getIslandBanTableManager().save();
        System.out.println("Sauvegarde des Settings");
        getDatabaseManager().getIslandSettingTableManager().save();
        System.out.println("Fin des sauvegardes");
```

**Comment by dlsf** [comment]
> ```batchfile
> [07:09:03 INFO]: [IridiumSkyblock] Sauvegarde des Islands
> [07:09:05 INFO]: [IridiumSkyblock] Sauvegarde des Invites
> [07:09:05 INFO]: [IridiumSkyblock] Sauvegarde des Permissions
> [07:09:07 INFO]: [IridiumSkyblock] Sauvegarde des Blocks
> [07:11:05 INFO]: [IridiumSkyblock] Sauvegarde des Spawners
> [07:11:07 INFO]: [IridiumSkyblock] Sauvegarde des Banks
> [07:11:11 INFO]: [IridiumSkyblock] Sauvegarde des Missions
> [07:11:12 INFO]: [IridiumSkyblock] Sauvegarde des Reward
> [07:11:12 INFO]: [IridiumSkyblock] Sauvegarde des Upgrades
> [07:11:19 INFO]: [IridiumSkyblock] Sauvegarde des Confiances
> [07:11:19 INFO]: [IridiumSkyblock] Sauvegarde des Booster
> [07:11:22 INFO]: [IridiumSkyblock] Sauvegarde des Warps
> [07:11:22 INFO]: [IridiumSkyblock] Sauvegarde des Logs
> [07:13:22 INFO]: [IridiumSkyblock] Sauvegarde des Bans
> [07:13:22 INFO]: [IridiumSkyblock] Sauvegarde des Settings
> [07:13:31 INFO]: [IridiumSkyblock] Fin des sauvegardes
> ```
> 
> I'm just add sout :
> 
> ```java
>        System.out.println("Sauvegarde des Users");
>         getDatabaseManager().getUserTableManager().save();
>         System.out.println("Sauvegarde des Islands");
>         getDatabaseManager().getIslandTableManager().save();
>         System.out.println("Sauvegarde des Invites");
>         getDatabaseManager().getIslandInviteTableManager().save();
>         System.out.println("Sauvegarde des Permissions");
>         getDatabaseManager().getIslandPermissionTableManager().save();
>         System.out.println("Sauvegarde des Blocks");
>         getDatabaseManager().getIslandBlocksTableManager().save();
>         System.out.println("Sauvegarde des Spawners");
>         getDatabaseManager().getIslandSpawnersTableManager().save();
>         System.out.println("Sauvegarde des Banks");
>         getDatabaseManager().getIslandBankTableManager().save();
>         System.out.println("Sauvegarde des Missions");
>         getDatabaseManager().getIslandMissionTableManager().save();
>         System.out.println("Sauvegarde des Reward");
>         getDatabaseManager().getIslandRewardTableManager().save();
>         System.out.println("Sauvegarde des Upgrades");
>         getDatabaseManager().getIslandUpgradeTableManager().save();
>         System.out.println("Sauvegarde des Confiances");
>         getDatabaseManager().getIslandTrustedTableManager().save();
>         System.out.println("Sauvegarde des Booster");
>         getDatabaseManager().getIslandBoosterTableManager().save();
>         System.out.println("Sauvegarde des Warps");
>         getDatabaseManager().getIslandWarpTableManager().save();
>         System.out.println("Sauvegarde des Logs");
>         getDatabaseManager().getIslandLogTableManager().save();
>         System.out.println("Sauvegarde des Bans");
>         getDatabaseManager().getIslandBanTableManager().save();
>         System.out.println("Sauvegarde des Settings");
>         getDatabaseManager().getIslandSettingTableManager().save();
>         System.out.println("Fin des sauvegardes");
> ```

Yeah, but we now only update islands with updates in their data. Even with dozens of islands, it should still be very fast.

**Comment by DoctaEnkoda** [comment]
Yes and no, it all depends on the content, and it's totally different:
![image](https://user-images.githubusercontent.com/26461373/143484877-8beae1dd-a320-4339-b404-808abfed7d1d.png)

**Comment by srnyx** [comment]
> Yes and no, it all depends on the content, and it's totally different: ![image](https://user-images.githubusercontent.com/26461373/143484877-8beae1dd-a320-4339-b404-808abfed7d1d.png)

![image](https://user-images.githubusercontent.com/25808801/143485456-7073327f-8f86-4c74-af45-550fec824adc.png)
