### ISSUE TITLE
Wiki button on Spigot page needs to be updated

### ISSUE THREAD

**Issue by partyp770** [Iridium-Development/IridiumSkyblock#45]
The "Wiki" button on the SpigotMC page links to the repository that was owned by IridiumLLC instead of Iridium-Development.
Just thought it was worth pointing out.

**Comment by dlsf** [comment]
We are already aware of that, thanks for reminding @PeachesMLG tho!

**Comment by PeachesMLG** [comment]
Making me do work >:C
