### ISSUE TITLE
FATAL ERROR ON ISLAND CREATE

### ISSUE THREAD

**Issue by Strahilchu** [Iridium-Development/IridiumSkyblock#450]
**Describe the bug**
After Updating to the latest version (with the new schematics changes) the server instantly errors and crashes when executing /is create. 

I have deleted the Schematics FOLDER + YML to reset them with the new ones and problem is still there!

I have tried PAPER + AIRPLANE Server Jars and have ruled that out as the cause.

Weirdly, after the server is restarted and I join back I can do /is home and it takes me to the island...

**To Reproduce**
1. Update to Iridium 3.1.2
2. Do or don't reset schematics folder and yml to the worldedit ones as it says in the ChangeLog
3. Run /is create

**Expected behavior**
No error and island creates and teleports player to it.

** Server Version and Plugin Version**
Server Version tested:
Paper version git-Paper-304
Airplane version git-Airplane-92
IridiumSkyBlock: v3.1.2

**Logs**
https://mclo.gs/R0PBxe0

**Comment by Strahilchu** [comment]
Almost looks like a WorldEdit error. 
I'm using version WorldEdit version 7.2.6-SNAPSHOT

I hope all this information helps, this is a critical error

**Comment by Strahilchu** [comment]
On a completely fresh server install, and completely fresh plugin install (WE, Vault, Iridium) full reset from scratch. 
This error still exists on /is create (however it does create the island and teleport me to it)
https://mclo.gs/7x84fJ4

I did this just to try and rule things out, resetting everything on production server is not an option for me. Especially seeing that there is still a problem somewhere within the plugin :(

**Comment by sh0inx** [comment]
It looks like it might be an issue with the schematic you're using. Loading the default island on a test server is working fine with no errors, even with the dev world edit version. Can you reproduce this error with the default schematics?

**Comment by dlsf** [comment]
Are you using the official 3.1.2 release or a custom/beta build? I'm 99% sure that these error messages can't be happening with the release.

**Comment by Strahilchu** [comment]
> It looks like it might be an issue with the schematic you're using. Loading the default island on a test server is working fine with no errors, even with the dev world edit version. Can you reproduce this error with the default schematics?

Yes sir, I made a completely new test server from complete scratch with just paper jar and iridium, vault, we, in the plugins folder to fully 100% clean install. On join I ran /is create ... https://mclo.gs/s8HRTma

> Are you using the official 3.1.2 release or a custom/beta build? I'm very sure that these error messages can't be happening with the latest official release.

Official release sir, I am as confused as you guys about it. :(

**Comment by PeachesMLG** [comment]
I think it might be caused by async chunks loading? possibly?

**Comment by DoctaEnkoda** [comment]
Just for try, can you test with AsyncWorldEdit or Fawe for check if your are identitic error ?
