### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Decibel0377** [Iridium-Development/IridiumSkyblock#462]
14.10 14:54:28 [Server] INFO Wuemeli issued server command: //island
14.10 14:54:29 [Server] WARN Plugin IridiumSkyblock v3.1.3 generated an exception while executing task 3761
14.10 14:54:29 [Server] INFO java.lang.NoSuchMethodError: 'com.sk89q.worldedit.EditSession com.sk89q.worldedit.WorldEdit.newEditSession(com.sk89q.worldedit.world.World)'
14.10 14:54:29 [Server] INFO at com.iridium.iridiumskyblock.schematics.WorldEdit.paste(WorldEdit.java:37) ~[?:?]
14.10 14:54:29 [Server] INFO at com.iridium.iridiumskyblock.managers.SchematicManager.lambda$pasteSchematic$0(SchematicManager.java:52) ~[?:?]
14.10 14:54:29 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1288]
14.10 14:54:29 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-1288]
14.10 14:54:29 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-1288]
14.10 14:54:29 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
14.10 14:54:29 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
14.10 14:54:29 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
14.10 14:54:29 [Server] WARN Plugin IridiumSkyblock v3.1.3 generated an exception while executing task 3759
14.10 14:54:29 [Server] INFO java.lang.NoSuchMethodError: 'com.sk89q.worldedit.EditSession com.sk89q.worldedit.WorldEdit.newEditSession(com.sk89q.worldedit.world.World)'
14.10 14:54:29 [Server] INFO at com.iridium.iridiumskyblock.schematics.WorldEdit.paste(WorldEdit.java:37) ~[?:?]
14.10 14:54:29 [Server] INFO at com.iridium.iridiumskyblock.managers.SchematicManager.lambda$pasteSchematic$0(SchematicManager.java:52) ~[?:?]
14.10 14:54:29 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1288]
14.10 14:54:29 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-1288]
14.10 14:54:29 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-1288]
14.10 14:54:29 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
14.10 14:54:29 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
14.10 14:54:29 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
14.10 14:54:29 [Server] WARN Plugin IridiumSkyblock v3.1.3 generated an exception while executing task 3760
14.10 14:54:29 [Server] INFO java.lang.NoSuchMethodError: 'com.sk89q.worldedit.EditSession com.sk89q.worldedit.WorldEdit.newEditSession(com.sk89q.worldedit.world.World)'
14.10 14:54:29 [Server] INFO at com.iridium.iridiumskyblock.schematics.WorldEdit.paste(WorldEdit.java:37) ~[?:?]
14.10 14:54:29 [Server] INFO at com.iridium.iridiumskyblock.managers.SchematicManager.lambda$pasteSchematic$0(SchematicManager.java:52) ~[?:?]
14.10 14:54:29 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1288]
14.10 14:54:29 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-1288]
14.10 14:54:29 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-1288]
14.10 14:54:29 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
14.10 14:54:29 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
14.10 14:54:29 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by PeachesMLG** [comment]
We dont support whatever version of worldedit your using
