### ISSUE TITLE
Mushroom Island does not generate

### ISSUE THREAD

**Issue by Strahilchu** [Iridium-Development/IridiumSkyblock#467]
**Describe the bug**
Mushroom Island does not generate, teleports me to empty void and falling down endlessly.

**To Reproduce**
1. Run /is create
2. Click on Mushroom Island

**Expected behavior**
Mushroom Island to generate as normal.

** Server Version and Plugin Version**
Plugin Version: 3.1.4
Server Version: Paper-336 (1.17.1)

**Logs**
There is no error log, it teleports me where the island should be but there is nothing, just a void.
Desert and Jungle Islands work as normal, I noticed Mushroom Island not spawning since 3.1.3 but didn't report it at the time.
Updated to 3.1.4 with (bug fixes) but this issue remains so I am reporting it. 

Extra: I tested this on production + freshly clean installed test server with same result. 
Plugins used in Fresh server: WorldEdit and Vault (required for Iridium, used latest versions of both)

**Comment by Strahilchu** [comment]
I see this was fixed, update coming on Spigot today?

**Comment by MertUnverdi** [comment]
will be tmr (our updates is every mondays)

**Comment by DreamVoid** [comment]
You can replace old schem file to [new file](https://github.com/Iridium-Development/IridiumSkyblock/blob/master/src/main/resources/mushroom.schem) and no need to restart server.

**Comment by MertUnverdi** [comment]
^^ but requires /is reload
