### ISSUE TITLE
Limit blocks [Bug]

### ISSUE THREAD

**Issue by MIsiuwa** [Iridium-Development/IridiumSkyblock#47]
The block limit does not work, after placing the maximum amount I can place again after 10-15 seconds.

**Comment by dlsf** [comment]
Is this an issue with IridiumSkyblock 3.0 or 2.6.7? This bug tracker is only for 3.0 bugs.

**Comment by PeachesMLG** [comment]
Considering we havent added that in 3.0.0 yet ima go and close this
