### ISSUE TITLE
Bungeecord breaks /is visit

### ISSUE THREAD

**Issue by dlsf** [Iridium-Development/IridiumSkyblock#482]
**Describe the bug**
You can't teleport to islands of offline players when using Bungeecord.

**To Reproduce**
1. Run `/is visit <name of an offline player>`
2. "No island found for that player"

**Expected behavior**
You should be teleported to the island.

**Server Version and Plugin Version**
IridiumSkyblock version: 3.1.4
Server version: git-Paper-349 (MC: 1.17.1)

**Additional context**
Might be related to Bungeecord, but it is set up correctly (online mode Bungeecord, offline mode server, `settings.bungeecord=true` in the `spigot.yml`).

**Comment by GavvyDizzle** [comment]
My server uses Bungee and I don't have this issue

**Comment by ajh123** [comment]
If we have this plugin on a lobby server, people cannot ```/is visit``` to their island on another proxied server e.g. skyblock
