### ISSUE TITLE
When a player dies in the nether, he can no longer interact with his island.

### ISSUE THREAD

**Issue by Kramels23** [Iridium-Development/IridiumSkyblock#488]
A player of my server died in the nether, and when he reappeared on his island (in the overworld), he couldn't interact with his island anymore (chests, blocks, cultures...) and he had a red color effect around his pc screen as if he was outside a world border (see the screen)
![image](https://user-images.githubusercontent.com/61807107/139711092-09927532-8862-4190-aae9-350488f18f88.png)

Minecraft client version: 1.17.1
Minecraft server version: 1.17.1
IridiumSkyBlock version: 3.1.5
(no errors)

**Comment by dlsf** [comment]
Could you please follow the issue template? We need the Minecraft + IridiumSkyblock version and error messages if there are any.

**Comment by Kramels23** [comment]
> Could you please follow the issue template? We need the Minecraft (including server software) + IridiumSkyblock version and error messages if there are any.

i update my issue sorry

**Comment by PeachesMLG** [comment]
does doing /is home fix it?

**Comment by Kramels23** [comment]
> does doing /is home fix it?

no :/

**Comment by PeachesMLG** [comment]
I dont think this is an issue with IridiumSkyblock, and I cant replicate it
