### ISSUE TITLE
Issues with Daily Missions

### ISSUE THREAD

**Issue by PeachesMLG** [Iridium-Development/IridiumSkyblock#499]
**Describe the bug**
Daily Missions are buggy and will sometimes only show a few daily missions

**To Reproduce**
:shrug: 

**Expected behavior**

**Server and Plugin Version**
Copy and paste the results of `/version` and `/is about`

**Screenshots**

**Logs**
If there are error messages in your console, please send them via [this](https://mclo.gs)

**Additional context**

**Comment by dlsf** [comment]
How dare you! Please follow the issue template! 😠
