### ISSUE TITLE
Change material to the AIR on Inventories.yml

### ISSUE THREAD

**Issue by atcpybd** [Iridium-Development/IridiumSkyblock#512]
**Describe the bug**

**To Reproduce**
1. Go to the Inventories.yml file
2. Scroll down to 'islandSchematicGUI'
3. change material on filler into AIR
4. See an error

**Expected behavior**
I want to change the "Select a Schematic" menu, which normally is a LIGHT_GRAY_STAINED_GLASS_PANE background but I want to change it to AIR.

**Server and Plugin Version**
Using Purpur, plugin version 3.1.9

**Screenshots**
![2021-11-20_23 45 25](https://user-images.githubusercontent.com/77416065/142744136-3359512b-4e85-4a5c-bafd-71e55e2e75bd.png)

**Logs**
 --> https://mclo.gs/yPZSIOY

**Additional context**

**Comment by dlsf** [comment]
The error message is shortened, most likely by your web interface or server software. Could you please search for the full one, for example in the latest.log or at the beginning of the log shortly after the server starts?

**Comment by atcpybd** [comment]
[latest.log](https://github.com/Iridium-Development/IridiumSkyblock/files/7575528/latest.log)

**Comment by atcpybd** [comment]
> The error message is shortened, most likely by your web interface or server software. Could you please search for the full one, for example in the latest.log or at the beginning of the log shortly after the server starts?
[latest.log](https://github.com/Iridium-Development/IridiumSkyblock/files/7575529/latest.log)

**Comment by dlsf** [comment]
Could you please send us your inventories.yml too?

**Comment by atcpybd** [comment]
> Could you please send us your inventories.yml too?

it say "We don't support that file type" so I send you by https://mclo.gs/4u4qU2N

**Comment by MertUnverdi** [comment]
Or paste.gg

**Comment by atcpybd** [comment]
> paste.gg

https://paste.gg/p/anonymous/940c587b7fc144718d47c34c0991d749

**Comment by PeachesMLG** [comment]
Should be fixed in this commit https://github.com/Iridium-Development/IridiumCore/commit/517cfc4802e9ea9fcceafb269614b7fd3b2c1ecb
