### ISSUE TITLE
WorldEdit schematics not working

### ISSUE THREAD

**Issue by SlaVistaPL** [Iridium-Development/IridiumSkyblock#513]
**Describe the bug**
As I stated in title - WorldEdit schematics are not working. When someone tries to create an island, it's stuck on the island creation message... and that's all. To prove it, I am attaching below (see section Logs) the stacktrace.

**To Reproduce**
1. Generate a new schematic (or if you have one already, import it into schematics folder)
2. Join the server from an account not having an island yet
3. Type /is create and select the schematic
4. Observe the chat

**Expected behavior**
Island should be created. Meanwhile it's stuck on creating island message.

**Server and Plugin Version**
Server info: *This server is running Purpur version git-Purpur-1255 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 89c9c90 on HEAD)
Unknown version
Previous version: git-Paper-79 (MC: 1.17)*
Plugin version is 3.2.1 (the latest at SpigotMC forum).

**Screenshots**
[none]

**Logs**
Here is the stacktrace: https://mclo.gs/iHEcPRH

**Additional context**
[none]

I would like to hear a reply from you ASAP - it's urgent.

**Comment by dlsf** [comment]
Please visit our [support Discord](https://discord.gg/6HJ73mWE7P) for assistance, this is not an IridiumSkyblock but a configuration issue.

But @PeachesMLG, maybe we should enhance the error message?
