### ISSUE TITLE
Some missions not working,

### ISSUE THREAD

**Issue by IconicDavexD** [Iridium-Development/IridiumSkyblock#517]
Describe the bug:
The registration of growing Cactus and Sugar Cane is not working in version 3.2.1 downloaded from the release section on GitHub.

To Reproduce:
Installed the plugin, tried to do the grow missions for Cactus and Sugar Canes

Self Troubleshooting:
When changing to other material in the same mission it works fine.
Have tried using the version from both Spigot and Github, with reset Iridium plugin folder.

Server Version and Plugin Version:
Server version Spigot 1.17.1
IridiumSkyblock version 3.2.1 (GitHub Release)

Additional context:
Server is running on a Bungeecord Network.

**Comment by Faun471** [comment]
Please use the bug report template.

**Comment by dlsf** [comment]
Should be fixed by https://github.com/Iridium-Development/IridiumSkyblock/commit/e7fa2558885e098776eb80d569335f578710e21d. Did you download the GitHub version from the releases section or GitHub Actions?

**Comment by IconicDavexD** [comment]
@dlsf  I downloaded the one from the releases [https://github.com/Iridium-Development/IridiumSkyblock/releases/tag/3.2.1](url)
I'm new to using GitHub, so didn't know about the actions tab if that's different. 
Should I download this one instead? [https://github.com/Iridium-Development/IridiumSkyblock/actions/runs/1505058838](url) or is that the same?

**Comment by dlsf** [comment]
Yes, you should download the other one
