### ISSUE TITLE
rosestacker blockstacking hook doesn't work. 

### ISSUE THREAD

**Issue by Pikaronga** [Iridium-Development/IridiumSkyblock#521]
**Describe the bug**
rosestacker hook doesn't work. (and therefore stacked blocks don't get removed on regen and the same for spawners these also don't count towards the island value.) (the actual block gets removed but the rosestacker holos are still there on regen

**To Reproduce**
Stack blocks with rosestacker. 

**Expected behavior**
Count em as value obv. 

**Server and Plugin Version**
Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)

[21:57:46 INFO]: Plugin Name: IridiumSkyblock
[21:57:46 INFO]: Plugin Version: 3.2.2
[21:57:46 INFO]: Plugin Author: Peaches_MLG
[21:57:46 INFO]: Plugin Contributors: das_, SlashRemix
[21:57:46 INFO]: Plugin Donations: www.patreon.com/Peaches_MLG

**Comment by Pikaronga** [comment]
There is also a problem when placing blocks normally it doesn't add to value when placed or when doing /is recalc. But it does add these values to the island when the server has been restarted for some reason.

**Comment by Faun471** [comment]
I couldn't replicate this
