### ISSUE TITLE
Nether biomes default to Ocean biomes when used with Overworld island schematics

### ISSUE THREAD

**Issue by devurose** [Iridium-Development/IridiumSkyblock#522]
In schematics.yml, I set have this code for a schematic:
`    overworld:
      biome: "NETHER_WASTES"
      schematicID: "crimson-island.schem"
      islandHeight: 90.0
      ignoreAirBlocks: true`
Generating it works as intended, the schematic loads up and everything, but when I press f3 to check the biome I get a random ocean biome. It does work if I do an overworld biome, such as plains.

The plugin version is 3.2.2 And the server is running paper 1.17.1
More info can be provided

**Comment by Faun471** [comment]
I think it's impossible to have a nether biome in the overworld dimension. Perhaps an option to choose where a player starts (overworld, nether or end) would "fix" the underlying issue?

**Comment by devaura15** [comment]
> I think it's impossible to have a nether biome in the overworld dimension. Perhaps an option to choose where a player starts (overworld, nether or end) would "fix" the underlying issue?

Perhaps it is no longer possible, it was possible on 1.16 before the recode so that might be worth mentioning. I do however believe your suggestion is a much better solution though!
