### ISSUE TITLE
Invite Menu Flickers

### ISSUE THREAD

**Issue by devaura15** [Iridium-Development/IridiumSkyblock#525]
The island command /is invite opens a menu, that once filled with any amount of player heads starts to flicker. No other menus to my knowledge do this, and it's quite distracting.

To reproduce it, invite someone to your island with /is invite playername and then run just /is invite.

I run plugin version 3.2.2, and Minecraft paper 1.17.1

**Comment by dlsf** [comment]
Can you still replicate this issue?

**Comment by dlsf** [comment]
Closed due to a lack of response. Please open a new issue or respond to this one if this problem persists.
