### ISSUE TITLE
Unkown Error in 3.2.2

### ISSUE THREAD

**Issue by Strahilchu** [Iridium-Development/IridiumSkyblock#529]
Console error seems to be happening randomly as far as I know, and one player couldn't do /is rewards unless they were in the nether.

:Server and Plugin Version:
git-Paper-397 (MC: 1.17.1)
IridiumSkyblock 3.2.2

https://mclo.gs/5s3nBa5

Posted this before but I closed it because I couldn't reproduce, saw it again so I am putting this error here. Still not sure how to reproduce though. Anyone else seen this?

**Comment by dlsf** [comment]
What is your RoseStacker version?

**Comment by Strahilchu** [comment]
> What is your RoseStacker version?

RoseStacker v1.4.0

**Comment by Strahilchu** [comment]
I will report on their github, I downgraded RoseStacker and issue seems to have gone away for now at least. Will keep this open until I'm sure but will open issue with them, seems like weird incompatibility with these latest versions

**Comment by PeachesMLG** [comment]
This has already been fixed
