### ISSUE TITLE
Crystal issue

### ISSUE THREAD

**Issue by wordangyou** [Iridium-Development/IridiumSkyblock#532]
**Describe the bug**

**To Reproduce**

**Expected behavior**
新版本的水晶op无法通过指令添加，希望作者能修复这个问题，谢谢！
**Server and Plugin Version**
Copy and paste the results of `/version` and `/is about`
MC:1.16.5  插件版本：3.3.1
**Screenshots**

**Logs**
If there are error messages in your console, please send them via [this](https://mclo.gs)

**Additional context**

**Comment by wordangyou** [comment]
打错了，是3.2.1,

**Comment by dlsf** [comment]
Are you looking for `/is bank give`? If not, please try to re-phrase your problem, the translations doesn't make much sense.

I would also appreciate if you could use https://www.deepl.com/ to translate the Chinese to English before posting it here.

**Comment by wordangyou** [comment]
Describe the bug

A clear and concise description of what the bug is.



To Reproduce

Steps to reproduce the behavior:



Go to '...'

Click on '....'

Scroll down to '....'

See error

Expected behavior

A clear and concise description of what you expected to happen.

The new version of crystal OP cannot be added through instructions. I hope the author can fix this problem. Thank you!

Server and Plugin Version

Copy and paste the results of /version and /is about

MC:1.16. 5. Plug in version: 3.3 one

Screenshots

If applicable, add screenshots to help explain your problem.



Logs

If there are error messages in your console, please send them via this



Additional context

Add any other context about the problem here.

**Comment by wordangyou** [comment]
> **描述 Bug**对 Bug 的清晰简洁的描述。
> The new version of crystal op cannot be added via the command, hopefully the author will fix this, thanks!

**Comment by dlsf** [comment]
Does `/is bank give` help you?

**Comment by wordangyou** [comment]
"/ is givecrystals" and "/ is removecrystars" cannot be used

**Comment by wordangyou** [comment]
Please add them again, thanks!

**Comment by wordangyou** [comment]
> 对您有帮助吗？`/is bank give`
"/ is givecrystals" and "/ is removecrystars" cannot be used

**Comment by wordangyou** [comment]
> 对您有帮助吗？`/is bank give`
Please add them again, thanks!

**Comment by dlsf** [comment]
`/is givecrystal` is now `/is bank give`

**Comment by wordangyou** [comment]
oh,thanks！

> `/is givecrystal` is now `/is bank give`
