### ISSUE TITLE
BUG MISSION BEETROOT

### ISSUE THREAD

**Issue by Su-kanah4612** [Iridium-Development/IridiumSkyblock#534]
I noticed a bug to create a mission with the beetroot.
i tested:
GROW: BEETROOT: 475
GROW: BEETROOTS: 475
GROW: BEETROOT_SEEDS: 475
GROW: BEETROOTS_SEED: 475
GROW: BEETROOTS_SEEDS: 475

without results

**Comment by dlsf** [comment]
Did you use spaces there?
It's supposed to be `GROW:BEETROOTS:475`

**Comment by dlsf** [comment]
I'll close this issue due to a lack of response, please answer again if the problem persists.
