### ISSUE TITLE
Island chunks loads every 20 seconds

### ISSUE THREAD

**Issue by bertek41** [Iridium-Development/IridiumSkyblock#540]
**Describe the bug**
I was testing ApiaEnvoy with unloaded chunk situations and saw that chunks were loading even if you are not in the island world. I tested without my plugin and confirmed this isn't related to me.

**To Reproduce**
Compile this:
```
@EventHandler
public void onChunkLoad(ChunkLoadEvent event) {
	if(event.getWorld().getName().equals("IridiumSkyblock"))
		getServer().getConsoleSender().sendMessage("loaded: " + event.getChunk().getX() + ":" + event.getChunk().getZ());
}
```
Then start the server and go to some another world. You will see every 20 seconds island chunks will be loaded.

**Expected behavior**
If it happens for every island there is a serious loss of performance. So it shouldn't load chunks of islands.

**Server and Plugin Version**
Server: This server is running Paper version git-Paper-399 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d4318a6 on ver/1.17.1)
Plugin Version: 3.2.3

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/20637793/146976687-a07e775a-f386-4c1a-aa08-8c175bb24f94.png)
(0:-9 is my island center)

**Comment by MertUnverdi** [comment]
Kanka bizim chunk load etme gibi hiç bir şeyimiz yok bizden kaynaklı değil

**Comment by MertUnverdi** [comment]
Recalculate ile alakalı olabilir sunucuda oyuncu yok iken load ediyor ise discorddan bana ulaş SlashRemix

**Comment by bertek41** [comment]
Ben de öyle düşünüyordum ama sadece Iridium ve test eklentisiyle denedim. Kodu compile edip deneyebilirsin. Sunucuda sadece ben varım oyuncusuz test etmedim.

**Comment by MertUnverdi** [comment]
Yinede dediğim gibi auto recalculate load etmez bukkit mantığına göre chunku load etmiyor blockdata için direkt worldden alıyor 
Iridiumsuz veya oyuncusuz test edersen emin olabiliriz sonuçları bekliyorum

**Comment by bertek41** [comment]
Iridiumsuz dünya yüklenmeyeceği için tabii ki de herhangi bir sonuç alınmayacak. Oyuncusuz denedim ve chunkları yüklemeye devam ediyor:
![image](https://user-images.githubusercontent.com/20637793/147060185-8484c9a9-d836-4c1a-b757-3f579ad59d02.png)

**Comment by MertUnverdi** [comment]
Bundan emin olmalıyız dostum çünkü chunk load edicek hiç birşeyimiz yok
20 saniye olduğunu belirtmişsin configten `islandRecalculateInterval` 20 saniye yemi ayarlı bi kontrol edermisin

**Comment by bertek41** [comment]
10'a ayarlı. Herhangi bir block işlemi veya Location#getBlock tarzı eylemler chunk load ediyor. Kodları incelemediğim için bir şey diyemem ama Iridium'dan kaynaklandığına eminim.

**Comment by MertUnverdi** [comment]
getBlock un load etmesi saçmalık olur bildiğim kadarıyla direkt world datasından çekiyor eski veriyi veriyor sonuçta chunk load edilmediği sürece değişiklik olamayacak yinede bunu bi araştırayım ayrıyeten @dlsf ile detaylı konuşacağım  teşekkürler

**Comment by PeachesMLG** [comment]
I have no idea what yall just said just now, but this is probabbly caused by the islands being recalculated in the background

**Comment by bertek41** [comment]
This happens even if there is no online players in the server. Isn't that a problem?

**Comment by PeachesMLG** [comment]
> This happens even if there is no online players in the server. Isn't that a problem?

No? Is this causing alot of lag or anything?

**Comment by bertek41** [comment]
> > This happens even if there is no online players in the server. Isn't that a problem?
> 
> No? Is this causing alot of lag or anything?

Well, I don't know. I am not running a production server. It depends how you load chunks but afaik Spigot doesn't support async loading so it will cause lag.

**Comment by freethemice** [comment]
I'm not sure if this help, but I had the same problem with my plugins and what it was is that every time you use Bukkit Location it loads that chunks location, you have to check and see if the chunk is loaded first before calling it, here is the code I used.
`    public static boolean isLoaded(Location loc)
    {
        if (loc == null) return false;
        if (loc.getWorld() == null) return false;
        World world = loc.getWorld();
        return world.isChunkLoaded(loc.getBlockX() >> 4, loc.getBlockZ() >> 4);
    }`

**Comment by bertek41** [comment]
> I'm not sure if this help, but I had the same problem with my plugins and what it was is that every time you use Bukkit Location it loads that chunks location, you have to check and see if the chunk is loaded first before calling it, here is the code I used.
> `    public static boolean isLoaded(Location loc)
>     {
>         if (loc == null) return false;
>         if (loc.getWorld() == null) return false;
>         World world = loc.getWorld();
>         return world.isChunkLoaded(loc.getBlockX() >> 4, loc.getBlockZ() >> 4);
>     }
> `

Location is just a constructor. Its getBlock method that loads the chunks.

**Comment by DoctaEnkoda** [comment]
You can set islandRecalculateInterval on 0 for disabled it ! 
https://github.com/Iridium-Development/IridiumSkyblock/pull/562

**Comment by freethemice** [comment]
[iridium-skyblock](https://www.spigotmc.org/resources/iridium-skyblock-1-13-1-18.62480/)
the option in the config is islandRecalculateInterval
