### ISSUE TITLE
YawHome does not work in schematics file

### ISSUE THREAD

**Issue by obanc** [Iridium-Development/IridiumSkyblock#541]
Confirmed by the Lord himself:

![image](https://user-images.githubusercontent.com/95717163/147174260-ac8795f0-de62-4cf9-8a7e-e6a161d9424d.png)

**Comment by dlsf** [comment]
Works fine on my server.

IridiumSkyblock 3.2.3
Paper 1.18.1-101

Could you please describe what you change and how you test it?

**Comment by obanc** [comment]
Not much I can describe to be honest. When changing the yawHome amount in a schematics.yml file it does not change my rotation at all to which the Lord said he replicated and confirmed. I am using 3.2.3 and paper 1.17.1-388. I just retested. 
![image](https://user-images.githubusercontent.com/95717163/147887227-919f1aef-41e6-4618-8ec0-a5105d4e13e1.png)

**Comment by dlsf** [comment]
You saved the config, restarted the server and generated a new island?

**Comment by obanc** [comment]
Yes, I have.

**Comment by dlsf** [comment]
Do you have any way to check if this is related to 1.17.1? I can test it too, but I would appreciate your cooperation because I'm unable to replicate this issue
