### ISSUE TITLE
End portal teleporting to Island Home

### ISSUE THREAD

**Issue by jonaas13** [Iridium-Development/IridiumSkyblock#542]
**Describe the bug**
I previously had end and nether disabled. 
I enabled them in the config and the nether is working although the schematics doesn't generate automatically on islands before I switched them on. (i get why)
The problem is the end portal, it takes you to the islands home and not the end. 

**To Reproduce**
1. Change plugin so it has nether and end off.
2. Change configs to completely disable end and nether.
3. Make island
4. Re-enable end and nether in server configs and plugin.
5. Test end portal (nether works but no schematic is generated for old islands).

**Expected behavior**
End portal should take player to the end.

**Server and Plugin Version**
Paper version git-Paper-402 (MC: 1.17.1) 
Iridium Skyblock 3.2.3

**Screenshots**
Check play.landsofminearchy.com (islands server)

**Logs**
There are no errors on startup or on command execution.

**Additional context**
My spawn world is world and islands world is islands.
I have custom schematics setup, all island point to the same schematic files for end and nether.
Server folder contains both world_the_end and islands_the_end.

**Comment by jonaas13** [comment]
With F3 I can see that the islands_the_end world gets loaded but almost immediatly you get tp'ed to back to your island home with the message "teleporting to your island home".

**Comment by jonaas13** [comment]
https://www.youtube.com/watch?v=gV32Q8gJQxg

**Comment by MertUnverdi** [comment]
it seems your end island schematic is corrupted,
try using same nether schematic for end tho (copy from nether schematic and update file name)

**Comment by jonaas13** [comment]
I don't think the schematic is corrupted. I'm getting the same error with the nether schematic also tried to make a new schematic.

**Comment by jonaas13** [comment]
the portal spawned me on y 0 and void-teleport:true is teleporting me to my home. Possibly because the schematic didn't load in correctly. (Because my island was generated before I enabled nether and end.)

**Comment by jonaas13** [comment]
It is fixed now. Found a workaround and made some mistakes in the config.
