### ISSUE TITLE
Stacked blocks(RoseStacker) are not counted when there is no one on the island. Bug Report

### ISSUE THREAD

**Issue by iliakravets677** [Iridium-Development/IridiumSkyblock#544]
**Describe the bug**
Stacked blocks(RoseStacker) are not counted when there is no one on the island.

**To Reproduce**
If you create Stacked blocks using RoseStacker on your island, and leave the island, it will count one block, but Stacked blocks will not

**Expected behavior**
So that the block rating is always correct.
rosestacker 1.4.1
![image](https://user-images.githubusercontent.com/56079131/147772504-4217dbab-8af6-4d0a-9c87-38ceef95e549.png)

**Server and Plugin Version**
Copy and paste the results of `/version` and `/is about`

**Screenshots**
![image](https://user-images.githubusercontent.com/56079131/147772538-cfb1e3dd-9173-433f-9a85-478b107b0a9c.png)
![image](https://user-images.githubusercontent.com/56079131/147772546-a635f10d-ff5a-460b-b0a5-197527df0e7f.png)
![image](https://user-images.githubusercontent.com/56079131/147772553-05253f95-9296-49bf-84a1-430af1de7c78.png)

**Logs**
no errors

**Additional context**

**Comment by PeachesMLG** [comment]
So it looks like the code we are using to get the StackedBlocks only returns the stackedblocks in loaded chunks

**Comment by iliakravets677** [comment]
> So it looks like the code we are using to get the StackedBlocks only returns the stackedblocks in loaded chunks

it can be fixed?

**Comment by dlsf** [comment]
Yeah, we are working on it

**Comment by iliakravets677** [comment]
> Yeah, we are working on it

also check the work with loading when the owner of the island is in another world
