### ISSUE TITLE
Nether Islands do not work with Multiverse Nether Portals 

### ISSUE THREAD

**Issue by James-Cotterill** [Iridium-Development/IridiumSkyblock#547]
**Describe the bug**
I’ve managed to replicate the issue on a test server with just iridium (+vault) and multiverse. As soon as I add the multiverse nether portals plugin it seems to break the nether island generation where it will teleport you to the correct world but with no island/border. While it takes me to the same/correct world it just doesn’t generate the island and therefore allow the player to build. This works fine for the end island/world. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Run server with IridiumSkyblock, vault, multiverse and multiverse nether portals. 
2. Create a new island
3. Create a nether portal and go through and there will be no island. 
4. This will however work for end islands or as soon as multiverse nether portals is removed.
 
**Expected behavior**
The nether island portal should generate / teleport inbetween the players island borders.

**Server and Plugin Version**
This server is running Paper version git-Paper-405 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2a827e3 on ver/1.17.1)

IS 3.2.3

**Screenshots**
![image](https://user-images.githubusercontent.com/76694654/147859329-1a4307e2-df06-48ea-9878-f6ad815a71d6.png)

**Logs**
This was checked with the support staff in discord and no errors were found. 

**Additional context**
https://discord.com/channels/543944856498864169/592092308514537510/926880773741613066

**Comment by dlsf** [comment]
What Multiverse version are you using?

**Comment by James-Cotterill** [comment]
> What Multiverse version are you using?

Latest at the time of posting. 

MV 3.4.0

**Comment by dlsf** [comment]
Thanks, I'll look into it

**Comment by dlsf** [comment]
I unfortunately wasn't able to find time yet

**Comment by James-Cotterill** [comment]
Sorry to chase but any update on this as it's been a few months now. 

I have also updated MV again and the issue persists.

Thanks

**Comment by KillerRose83** [comment]
get multiverse nether portals and do /mvnplink nether iridiumSkyblock iridiumSkyblock_nether

then you might have a problem with mv inventories add that plugin and group the iridiumSkyblokc worlds under *your group name here*
if you use mvinv it might reset ur inventory beware
