### ISSUE TITLE
Island Value Bug

### ISSUE THREAD

**Issue by splix-io** [Iridium-Development/IridiumSkyblock#550]
**Describe the bug**
if I place a spawner, 
the island value goes up x2 of the spawner value
So
![image](https://user-images.githubusercontent.com/71552521/147880106-5df2520b-7299-4271-a0cb-a02e6abb6ba5.png)
this spawner value is 10K
if I place this the value goes to 20K when the value is meant to be at 10K
![image](https://user-images.githubusercontent.com/71552521/147880143-407d7518-c696-4983-a77b-7da175f164c5.png)
But when I break the spawner the value goes to 10K
![image](https://user-images.githubusercontent.com/71552521/147880166-b9300022-7981-4836-b28b-4ba675bfa92d.png)
And if I place another one, the value goes up to 30K instead of 20K
![image](https://user-images.githubusercontent.com/71552521/147880184-2cc4f04f-cb31-4f12-a57c-17d2af2aa790.png)

But if I do /is recalc
The value goes to 0 even though there is a spawner with 10K value
![image](https://user-images.githubusercontent.com/71552521/147880213-78a0aa4c-99ac-4e28-8cd7-0e57368a586c.png)
![image](https://user-images.githubusercontent.com/71552521/147880219-91a7454d-9305-4c91-a3f8-cc0ded0e0775.png)

**To Reproduce**
1. Set a spawner value
2. restart the server
3. place a spawner on your island
4. break the spawner
5. place another spawner
6. do /is recalc

**Expected behavior**
I expected the value to go from 0 ---> 10K ---> 0 --->10K ---> 10K

**Server and Plugin Version**
Copy and paste the results of `/version` and `/is about`
![image](https://user-images.githubusercontent.com/71552521/147880292-226ec00b-86b6-486b-8934-a0e8e26a7130.png)
![image](https://user-images.githubusercontent.com/71552521/147880305-42eeb5cf-a1fb-4e30-b2a1-c2239cd9d712.png)

**Screenshots**
Pasted above in order

**Comment by OtakuNL** [comment]
I have the exact same issue on my server. The same description.

**Comment by DoctaEnkoda** [comment]
Can be closed : https://github.com/Iridium-Development/IridiumSkyblock/pull/573
@PeachesMLG

**Comment by dlsf** [comment]
@DoctaEnkoda just link the issues to your pull request (e.g. by writing `Fixes #xyz` in the description)
