### ISSUE TITLE
Error message spamming in console

### ISSUE THREAD

**Issue by Paradox101** [Iridium-Development/IridiumSkyblock#553]
**Describe the bug**
Error message spamming in console

**To Reproduce**
Unknown, no one was using plugin while this started.

**Expected behavior**
Fix cause of error.

**Server and Plugin Version**
This server is running Paper version git-Paper-137 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: c3d812d)
Iridium Skyblock 3.2.3

**Screenshots**

**Logs**
https://mclo.gs/gS6i5bo

**Additional context**

**Comment by dlsf** [comment]
This issue has already been fixed by #548, please wait for the next update, download the beta version from Github Actions or request it on our support Discord server.
