### ISSUE TITLE
Spawner Stacking Error w/ RoseStacker

### ISSUE THREAD

**Issue by freethemice** [Iridium-Development/IridiumSkyblock#557]
**Describe the bug**
Try to stack spawners, using rosestacker plugin, when the amount gets to the max placed amount it spams the following error

**To Reproduce**
1. stack spawners(using rosestacker plugin)
2. keep stacking them until the max allowed

**Expected behavior**
no errors in console 

**Server and Plugin Version**
papper 1.18.1, IridiumSkyblock-3.2.3, RoseStacker-1.4.2, SimpleScore-3.9.1, PlaceholderAPI-2.11.1

**Screenshots**
![image](https://user-images.githubusercontent.com/6777346/148662289-be2a590d-d615-4a43-9ea8-9d8e7fe6abeb.png)

**Logs**
https://mclo.gs/GMAvVs5

**Additional context**

**Comment by dlsf** [comment]
Could you please send the full error message? The most important part is missing

**Comment by freethemice** [comment]
Sorry for that: https://mclo.gs/3vaOIl9

**Comment by dlsf** [comment]
We already fixed this issue in #556, please wait for the next update, download the beta from Github Actions or request it on the support Discord server.
