### ISSUE TITLE
Trusted players bypass island limits

### ISSUE THREAD

**Issue by Baxer97** [Iridium-Development/IridiumSkyblock#564]
Hey, i noticed a bug: trusted player (not invited) can bypass the spawner and hopper limit. Let's say that the spawner limit is 4 and there are already 4 spawner placed on the island: in this case the trusted player can't place anymore spawners but if a member of the island breaks one of the spawners the trusted player is not affected anymore by the limit and can place as many spawners as he wants. Same for hoppers. Thanks for taking the time to read this

**Comment by dlsf** [comment]
Could you please follow the bug report template and send us your IridiumSkyblock & Minecraft version and any relevant log files?

**Comment by Baxer97** [comment]
IridiumSkyBlock: 3.2.3
Version: AirPlane 1.17.1
Logs: No error in console

**Comment by Baxer97** [comment]
Video: https://www.youtube.com/watch?v=oVbQL4oT25A
