### ISSUE TITLE
Sea generation error

### ISSUE THREAD

**Issue by Aizark** [Iridium-Development/IridiumSkyblock#570]
Error description:
If you try to create a water world for marine survival, then you can get problems.
It's about version 1.18.1.
Since this version, a negative value of the depth of the world has been introduced.
To create a sea, you need to specify two layers of land, what kind of block, and its height.
The world is created up to height -63
However, the generated bottom of the world is not generated below 0 height. You will see an abyss without a sea, all the way to the bedrock. Also, if you specify sand and gravel, when working with it, a cascading collapse of blocks will begin. Because the blocks are not on bedrock.
Apparently it doesn't work as intended.

If you specify sea surface values ​​as a negative value, then the sea will cause unpredictable errors. For example, bedrock will not be generated at all, or one of the layers of the sea will not appear.

Personally, I need a smooth and deep sea, without vegetation and other bonuses. One layer of bedrock and one layer of something else.

I know this is a bug report, But if it's not difficult for you, except for the fix,but I would add bedrock and vegetation to the sea settings to create an empty and flat sea

IMG:
https://cdn.discordapp.com/attachments/411072686626832384/933224446188216340/unknown.png

**Comment by dlsf** [comment]
I know that you were told to open this issue, but it works as intended (which doesn't mean that it's a good solution).

Please suggest it in the IridiumSkyblock suggestions channel.

**Comment by dlsf** [comment]
My bad, I meant to close your other issue

**Comment by dlsf** [comment]
Can you please send us your configuration.yml?
