### ISSUE TITLE
Turning off worlds

### ISSUE THREAD

**Issue by Aizark** [Iridium-Development/IridiumSkyblock#571]
Perhaps you, as an author, conceived the work of your plugin. But I will describe my problem.

I'm using a plugin and I don't need end and nether worlds in it. There is an option to turn them off in the configuration settings. However, the plugin continues to generate these worlds every time I'm busy developing the server. Even if they are removed.
Even when I delete worlds, then the plugin will work with these worlds, informing about the preparation of the spawn area

It may be intended, but I would remove the loading of worlds if they are not needed, speeding up the performance of the server and its speed of getting up.

**Comment by dlsf** [comment]
I know that you were told to open this issue, but it works as intended (which doesn't mean that it's a good solution).

Please suggest it in the IridiumSkyblock suggestions channel.
