### ISSUE TITLE
is bank problem

### ISSUE THREAD

**Issue by GizliBaskan** [Iridium-Development/IridiumSkyblock#582]
I have 50 dollars in money in the island bank, but I cannot withdraw this money.

The following message: "Insufficient %type% to withdraw"
no error in console
![image](https://user-images.githubusercontent.com/55203750/150777716-4b3e8941-ddb4-4277-a83b-2e0ac865ff9f.png)

server ver:
![image](https://user-images.githubusercontent.com/55203750/150777865-c9d040e4-2223-4cde-9470-302fa0dd94c9.png)

**Comment by MertUnverdi** [comment]
Çözdün mü?
