### ISSUE TITLE
is chat not working

### ISSUE THREAD

**Issue by GizliBaskan** [Iridium-Development/IridiumSkyblock#583]
![image](https://user-images.githubusercontent.com/55203750/150777986-cb3cd75b-0a6c-4a11-b891-b0d9ea0701b7.png)
`islandMemberChat: "%prefix% &7 <GRADIENT:8d99ae>%player% &8» &f%message%</GRADIENT:edede8>"`
/is chat not working :/
no error in console
server ver:
![image](https://user-images.githubusercontent.com/55203750/150778169-5c1fe3bf-5916-413b-b760-8464ec4cf760.png)

**Comment by MertUnverdi** [comment]
Bu bi tık imposs kullandığın chat eklentisi vs var mı?
