### ISSUE TITLE
Island Blasting...

### ISSUE THREAD

**Issue by GizliBaskan** [Iridium-Development/IridiumSkyblock#584]
Server Ver:
![image](https://user-images.githubusercontent.com/55203750/150875322-bf0ae54e-5204-4dd6-884f-476acd0baa41.png)

Someone on the islands next to each other builds a TNT launch machine on their own island and sends TNT to another island so that they can blow up that island.

I know that the problem can be solved by turning off tnt explosions from the ada settings, but it is not disabled by default. That's why this needs to be fixed

**Comment by MertUnverdi** [comment]
Pistonlar border dışına çalışmaz(dışarıya block itemez) border dışına build yapamazlar bu makinayı nasıl kuruyorlar amk
