### ISSUE TITLE
Fix bugs in Issues and add Commands as well as add a placeholder

### ISSUE THREAD

**Issue by MCJiaoLong** [Iridium-Development/IridiumSkyblock#592]
Bugs:
1.#588
Money cannot be added after the store is sold. Is this an economic system that supports plug-ins such as CMI?
2.#589
Please revise it. There is no problem after I revise it.
Commands:
3.Add command to view player's crystals.
4.Add commands to increase, decrease and set player's crystals.
Placeholder:
5. Add a player variable, which can display the number of crystals of the player
Others:
6.Adding support for economic plugins such as Xconomy is the binding of empty island money and gold coins of economic plugins

Can you fix and add these?
I think these will make this plugin better！
Thank you very much！

In Chinese:
Bugs:
1.#588
商店出售后金钱无法添加,这个支持CMI等插件的经济系统吗
2.#589
请修改一下,我修改后是没有问题了
Commands:
3.添加查看玩家水晶的命令
4.添加增加、减少、设置玩家水晶的命令
Placeholder:
5.添加玩家变量,它可以显示玩家的水晶数量
Others:
6.添加对XConomy等经济插件的支持,
就是空岛金钱与经济插件的金币绑定

你能修复并添加这些吗？我想这会让这个插件变得更好！非常感谢啊！

**Comment by MertUnverdi** [comment]
Follow the correct issue template

**Comment by dlsf** [comment]
Please open one issue for each problem, send feature requests on the Discord server and respond in existing issues if possible
