### ISSUE TITLE
Treeassist and missions

### ISSUE THREAD

**Issue by Robotek019** [Iridium-Development/IridiumSkyblock#606]
**Describe the bug**

**To Reproduce**
1. Install IridiumSkyblock and Treeassist plugin (https://www.spigotmc.org/resources/treeassist.67436/)
2. Try to finish task lumberjack"

**Expected behavior**
felling a tree with a plug-in should "calculate the amount" of tree felled 

**Server and Plugin Version**
IridiumSkyblock Version 3.2.5

Current: git-Purpur-1547 (MC: 1.18.1)*
* You are 4 version(s) behind
Download the new version at: https://purpurmc.org/downloads

**Screenshots**
------------------

**Logs**
without errors with console

**Comment by dlsf** [comment]
That's a feature request, not a bug
