### ISSUE TITLE
Crash when Accessing PalettedContainer from multiple threads

### ISSUE THREAD

**Issue by Luke100000** [Iridium-Development/IridiumSkyblock#608]
**Describe the bug**
Game crashes from time to time due to invalid concurrent access.

**To Reproduce**
Install the newest Spiggot version, newest plugin version, and wait.
Started to happen after a while, but then very frequently.

**Server and Plugin Version**
CraftBukkit version 3427-Spigot-6edb62f-de95135 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)
Plugin Version 3.2.5

**Logs**
https://mclo.gs/8m4TnRd

**Additional context**
We "fixed" that issue by commenting out `com.iridium.iridiumskyblock.managers.IslandManager.recalculateIsland:841` as it's one of the 2 access calls.

**Comment by Luke100000** [comment]
Yes, we tried the newest version from spigotmc.org

**Comment by dlsf** [comment]
Are you still experiencing this issue? Did you try updating to the latest Spigot / Paper version?
