### ISSUE TITLE
is shop fill item

### ISSUE THREAD

**Issue by Cimejes666** [Iridium-Development/IridiumSkyblock#615]
I was making an is shop, when I noticed that somehow now there is one of the fill items (black glass stained pane) in my inventory whenever I use the /is shop. just in case, staff in discord told me to report it here.
 discord url message just in case: https://discord.com/channels/543944856498864169/592092308514537510/942917306340745277
![image](https://user-images.githubusercontent.com/99695528/153963268-86781c45-9d5c-4b37-a460-4efc5c473808.png)

**Comment by Cimejes666** [comment]
dk what I did but made it disappear. Maybe its solved.. But maybe it returns or it happens to someone else and that person dk how to solve it. So Ill leave this issue here in case someone else has this problem

**Comment by dlsf** [comment]
I don't see how this could happen. You're the first one to report such an issue, and we almost haven't changed the shop system for over a year.

Just out of curiosity, what is your Minecraft version, server software and client (Lunar, Labymod, Optifine, Vanilla, ...)?

**Comment by dlsf** [comment]
No further occurrences of this issue have been reported, I believe it's unrelated to IridiumSkyblock
