### ISSUE TITLE
Iridium Placeholders don't update on NPC's (Citizens 2)

### ISSUE THREAD

**Issue by OtakuNL** [Iridium-Development/IridiumSkyblock#623]
**Describe the bug**
If I try to place a placehodler from Iridium SKyblock the NPC just shows N/A. Weird thing is, when I remove the character it did put the NPC with the correct name when it asks for confirmation.

**To Reproduce**
1. Place an NPC with typing /npc create (name) or placeholder in this case

**Expected behavior**
That the placeholder will be placed above the NPC

**Server and Plugin Version**
This server is running Paper version git-Paper-214 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: bfa50ad)
You are running the latest version
Previous version: git-Paper-207 (MC: 1.18.1)

**Screenshots**

**Logs**
No error logs

**Additional context**

**Comment by OtakuNL** [comment]
<a href="https://ibb.co/743D7SZ"><img src="https://i.ibb.co/743D7SZ/unknown.png" alt="unknown" border="0"></a>

**Comment by dlsf** [comment]
What placeholders did you use?
