### ISSUE TITLE
not letting me create island

### ISSUE THREAD

**Issue by Brodie20122005** [Iridium-Development/IridiumSkyblock#627]
everytime i do /is create it comes up with a "schematics" gui. when that comes up it wants me to select something but nothing is there to select

**Comment by Brodie20122005** [comment]
![Capture](https://user-images.githubusercontent.com/101097586/157008463-28a36f5b-7501-4d5f-93ef-429826ce1242.PNG)

**Comment by dlsf** [comment]
Please follow the issue template, we need more information. It would also be great if you could visit our [support Discord](https://discord.gg/6HJ73mWE7P) first.

I'll close this issue, please contact us on Discord or provide more information in a new issue.
