### ISSUE TITLE
Regenerating Island does not wipe entire old island (for large islands)

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [Iridium-Development/IridiumSkyblock#633]
**Describe the bug**
When regenerating large islands the island will not fully be wiped. The issue is the plugin wipes only the island portions within the border so if the island is larger than the starter border then it causes this problem. 

**How to solve it:** Allow us to configure default border size. I did not see a way to in the config files. I know we could alternatively make smaller islands but that may not be ideal considering we already made them.

**To Reproduce**
1. Create a schematic of a large island and use it for /island generation. The schematic needs to be larger than the border.
2. Regenerate your island to a new island.
3. Admire the old island's remains outside of the border.

**Expected behavior**
I expected it to wipe the entire old island.

**Server and Plugin Version**
Copy and paste the results of `/version` and `/is about`
13.03 06:23:56 [Server] INFO Current: git-Purpur-1566 (MC: 1.18.1)*
13.03 06:23:56 [Server] INFO Previous: git-Paper-408 (MC: 1.17.1)
13.03 06:23:56 [Server] INFO * You are running the latest version
13.03 06:23:59 [Server] INFO Plugin Name: IridiumSkyblock
13.03 06:23:59 [Server] INFO Plugin Version: 3.2.6
13.03 06:23:59 [Server] INFO Plugin Author: Peaches_MLG
13.03 06:23:59 [Server] INFO Plugin Contributors: das_, SlashRemix, DoctaEnkoda
13.03 06:23:59 [Server] INFO Plugin Donations: www.patreon.com/Peaches_MLG

**Screenshots**
https://gyazo.com/de4100f5fa720d8d26d6133d84abccc3

**Logs**
My console is being spammed by TempFly (I reported a bug to them as well, see [here](https://github.com/ChiefMoneyBags/TempFly/issues/51)). So I cannot check if there are console errors currently.

latest.log: https://gist.github.com/PiggiesGoSqueal/94f1f86bf1efb27ce4ec0f30cbf4b447

**Comment by ChiefMoneyBags** [comment]
The current version of TempFly does not support hooking into your version of IridiumSkyblock. The TempFly error is unfortunately not what is causing your larger issue regarding island regeneration. The error simply means that TempFly is trying to ask IridiumSkyblock if a specific world is an island world as it wants to check flight restrictions in that island world. The method to do so in recent versions of IridiumSkyblock has changed so TempFly errors as it does not know what to do. You can prevent the TempFly error by navigating to the skyblock config file located in TempFly/hooks/SkyBlock/IridiumSkyblock.yml and set the value "enabled" to false.

**Comment by ChiefMoneyBags** [comment]
The current version of TempFly does not support hooking into your version of IridiumSkyblock. The TempFly error is unfortunately not what is causing your larger issue regarding island regeneration. The error simply means that TempFly is trying to ask IridiumSkyblock if a specific world is an island world as it wants to check flight restrictions in that island world. The method to do so in recent versions of IridiumSkyblock has changed so TempFly errors as it does not know what to do. You can prevent the TempFly error by navigating to the skyblock config file located in TempFly/hooks/SkyBlock/IridiumSkyblock.yml and set the value "enabled" to false.
