### ISSUE TITLE
New Schem Not Loading

### ISSUE THREAD

**Issue by PyroFT** [Iridium-Development/IridiumSkyblock#647]
It was nether season on my server and I opened up the nether. I placed a new schem and put it in both the schem config and enabled it in the config. When they make a portal it generates the same island as the beginner island. Even tho the config says "netherisnald.schem". they have to completely wipe both islands with /is delete and start a new island for the new schem to work.

**Comment by dlsf** [comment]
Please open a new issue which follows the issue template if the problem persists.
