### ISSUE TITLE
SEVERAL BUG WITH DUPE MONEY [ /is deposit money]

### ISSUE THREAD

**Issue by MrDeathMatch** [Iridium-Development/IridiumSkyblock#648]
Good afternoon, there is a very serious bug with which you can MULTIPLY YOUR MONEY.

There is a serious BUG that multiplies the money. The bug is that if I enter, for example, "40M" with the command /is deposit money 50000000, which is "50 M", the money is deposited but it is not taken away.

Video: https://youtu.be/kPsIjhi8zoI

**Comment by dlsf** [comment]
Please open a new issue where you follow the issue template. Additionally, a list of your plugins might be helpful to track down the issue.
