### ISSUE TITLE
Login on Island forcefully

### ISSUE THREAD

**Issue by Dharuzz** [Iridium-Development/IridiumSkyblock#651]
I use SetTheSpawn plugin and I have it so it teleports everyone to the spawn when they log in, also have disabled the "per-world-login" configuration so it always teleports me to the spawn no matter where I am.
I can log out on every world (main world, nether, end, survival world, test world) and will always log in on the Spawn. Except when I log out on my Island, it always stays on the Island.

On configuration.yml I have this: `respawnOnIsland: false`

1. Log out on every other World
2. Log in back in main Spawn
3. Log out on Island
4. Log in on Island

**Expected behavior**
I would like to be sent to the main Spawn despite where I logged out

**Server and Plugin Version**
![image](https://user-images.githubusercontent.com/100977552/163279726-215166be-7dd1-4a88-b100-42b57ea21136.png)
![image](https://user-images.githubusercontent.com/100977552/163279781-dde591d6-0b11-43a8-bc53-ffdf076de51c.png)

**Logs**
No messages on console.

**Comment by dlsf** [comment]
We don't influence the join location at all, please check other plugins like world managers. Please don't hesitate to ask for help on our support Discord server.
