### ISSUE TITLE
[Feature] Add new locale config option (per-player-localel)

### ISSUE THREAD

**Issue by lordhadow1** [Iridium-Development/IridiumSkyblock#654]
Add a new config option that makes Iridium SkyBlock to use the language from the client(s) instead of one language for the whole Server.

You can use the Spigot method player.spigot().getLocale to resolve the client language or you could use the Protocollib packet PacketType.Play.Client.SETTINGS which is a bit faster.

**Comment by dlsf** [comment]
Please use our support Discord server for feature requests. You can find an invite in the README.
