### ISSUE TITLE
Cannot translate "True" "False" and "Default" in /is settings

### ISSUE THREAD

**Issue by SpiziTV** [Iridium-Development/IridiumSkyblock#657]
**Describe the bug**
Cannot translate "True" "False" and "Default" in /is settings

**To Reproduce**
1. Do a /is settings
2. Put mouse on any settings
3. The value "True" "False" and "Default" aren't translatable in the lang file

**Expected behavior**
Add an option in the lang file to translate it

**Server and Plugin Version**
Server is running Paper version 1.18.2-R0.1-SNAPSHOT
Iridium Skyblock 3.2.8

**Screenshots**
![unknown](https://user-images.githubusercontent.com/99984955/167825814-1a561705-2d9e-4757-b574-0bfd12c15797.png)
![unknown](https://user-images.githubusercontent.com/99984955/167825888-34c8e010-6fdf-4607-8541-d31baf001d0d.png)
![unknown](https://user-images.githubusercontent.com/99984955/167825913-a8e4aa5d-57db-4bbc-8c57-d0766e2ada7f.png)

**Comment by MertUnverdi** [comment]
peaches stoopid, i was did everything configurable about is settings but..

#421 "(
