### ISSUE TITLE
Value Duplication

### ISSUE THREAD

**Issue by Jbacot** [Iridium-Development/IridiumSkyblock#662]
**Describe the bug**
Burning or exploding blocks that have value do not lower island value. This can be used to duplicate island value.

**To Reproduce**
1. Place down a block that has value
2. Blow it up or burn it
3. Value does not decrease

**Expected behavior**
Value is suppose to go down

**Server and Plugin Version**
Paper version git-paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git:cc43ba7 on ver/1.17.1)
Plugin Version: 3.2.8

**Comment by Jbacot** [comment]
It seems to update after you place and break a block that has value.

**Comment by MertUnverdi** [comment]
Missing listeners @dlsf @PeachesMLG

**Comment by MertUnverdi** [comment]
The fışkın github buttons
