### ISSUE TITLE
1.9 Breaks Nether

### ISSUE THREAD

**Issue by zzkanezz2** [Iridium-Development/IridiumSkyblock#675]
**Describe the bug**
Your islands generate outside nether border, rollbacking to 1.8 fixes this. This issue has been confirmed by others.

**To Reproduce**
1. Go to 'minecraft 1.9'
2. Click on 'skyblock'
3. Scroll down to 'nether island'
4. See error 'none'

**Expected behavior**
Island generates in border for nether.

**Server and Plugin Version**
Copy and paste the results of `/version` and `/is about`
/1.9 /1.9

**Screenshots**
N/A

**Logs**
If there are error messages in your console, please send them via [this](https://mclo.gs)
N/A

**Additional context**

**Comment by siskulous** [comment]
I also ran into this issue. The affected player set /is border to off and was able to play on his nether normally again.

**Comment by MertUnverdi** [comment]
This plugin only works for 1.13+ please check supported versions of plugins before downloading it
