### ISSUE TITLE
Possibility to pour water and lava onto another player's island without permission

### ISSUE THREAD

**Issue by KaBoom13** [Iridium-Development/IridiumSkyblock#69]
It is possible to spill water/lava on an island that you do not have permission to do. the error is that if you fly, for example, on a fly and the cursor moves up, there is a chance that it will not withdraw the water/lava

**Server specification:**
- server version 1.8.8
- server engine paperspigot
- plugin version 2.6.7

**Used client versions for the bug test:**
- 1.16.5
- 1.8.9

making the baggage in the video version:
https://youtu.be/oNOBhTmMPak

**Comment by RyVador** [comment]
this github is for 3.0.0, if you have issues with 2.6.7 ask on the support discord: https://discord.gg/6mdyZbuSDk

**Comment by KaBoom13** [comment]
well.  and the database in 3.0.0 is compatible with 2.6.7?

**Comment by dlsf** [comment]
It most likely will be. Please use the Discord for further questions

**Comment by dlsf** [comment]
This is a Spigot / Minecraft bug by the way, I already reported it: https://hub.spigotmc.org/jira/browse/SPIGOT-6351
