### ISSUE TITLE
Pistons can push players through the island border

### ISSUE THREAD

**Issue by SFlakeZ** [Iridium-Development/IridiumSkyblock#701]
**Describe the bug**
If you use a Piston, you can push yourself out of the border of the island
and place blocks, which you can no longer destroy.

**Steps to reproduce the behavior:**
1. Build yourself to the border.
2. Build a piston one block away from the border, facing the border.
3. Activate the Piston to push yourself out of the wall and quickly place a block.

**Expected behavior**
Players have no advantage due to the bug, but the blocks outside the border cannot be removed.
The expected behavior would be, of course, that the player cannot push himself out of the border with pistons.

**Server and Plugin Version**
`Paper: git-Paper-484 (MC: 1.19.4)`
`IridiumSkyblock: 4.0.0`
`FAWE: Build-391`

**Screenshots**
![image](https://user-images.githubusercontent.com/62914389/229314691-e05a39aa-f854-4d1a-9209-179d5be376dd.png)
![image](https://user-images.githubusercontent.com/62914389/229314741-297575b3-5ad7-4dd9-a680-5cedf7afc502.png)

**Comment by MertUnverdi** [comment]
[Fix](https://github.com/Iridium-Development/IridiumTeams/pull/14) this should work
