### ISSUE TITLE
Floating sand, [...]

### ISSUE THREAD

**Issue by SFlakeZ** [Iridium-Development/IridiumSkyblock#702]
**Describe the bug**
Blocks that fall down without a supporting block underneath
remain on their placed position. (SAND, RED_SAND, GRAVEL)

**Steps to reproduce the behavior:**
1. Grab blocks like sand or gravel and place them on a wall without a block underneath.
2. Witness the magic of how the block is not attracted by gravity.

**Expected behavior**
The mentioned blocks should behave as in a vanilla world.
In a default world, for example, sand falls to the ground perfectly fine.

**Server and Plugin Version**
`Paper: git-Paper-484 (MC: 1.19.4)`
`IridiumSkyblock: 4.0.0`
`FAWE: Build-391`

**Screenshots**
![image](https://user-images.githubusercontent.com/62914389/229315569-d76d2212-f7dc-416d-9e4a-6f3e827cf70b.png)

**Comment by MertUnverdi** [comment]
Can you try with the ENTITY_GRIEF setting is disabled?

**Comment by sh0inx** [comment]
block update after enabling island setting entity grief lets the gravity affected blocks fall 👍
