### ISSUE TITLE
On Join

### ISSUE THREAD

**Issue by Michotek** [Iridium-Development/IridiumSkyblock#703]
**Describe the bug**
Everytime a player logs into the server, the plugin generates error

**To Reproduce**
1. log into server

**Server and Plugin Version**
![image](https://user-images.githubusercontent.com/64899181/229594955-3c2f3873-8770-47ba-8e60-28ed33ef575c.png)
![image](https://user-images.githubusercontent.com/64899181/229594981-493814b3-37e5-423e-8766-6f841c7dae04.png)

**Logs**
https://mclo.gs/Yk6VrQZ

**Comment by MertUnverdi** [comment]
it seems about another plugin, do u have any spawn plugin?
So like a plugin trying teleport player to somewhere when player join but they doesn't listen the event correctly cuz PlayerJoinEvent is fires when someone click to "Join Server" button, in this case player wasn't on server they should listen the event with EventPriority.MONITOR

**Comment by Testic19** [comment]
This is problem for me too

**Comment by sh0inx** [comment]
can't replicate, further information required

**Comment by PeachesMLG** [comment]
id imagine this is more an error on spigots side. are you using a fork or anything
