### ISSUE TITLE
Server lag due to mass iteration of blocks when deleting island region

### ISSUE THREAD

**Issue by Jeremys556** [Iridium-Development/IridiumSkyblock#706]
https://github.com/Iridium-Development/IridiumSkyblock/blob/cab99322d4e30cbd16c081dbb1f315343de420be/src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java#L168

When I create an island, especially with a larger size, it lags my server greatly. I believe that the function at the mentioned line is the issue; as far as I understand, when you create an island it first calls the above function to clear the area, which causes the lag. I believe this could be fixed by replacing it with a WorldEdit call that way users who receive lag can install FAWE which should optimize this and clear up the lag.

While I'm not sure if this is the correct solution, I am sure that something has to be done because this lag makes the plugin unusable for me.

**Comment by sh0inx** [comment]
the plugin uses an async paster and has FAWE support now, try again, and re-open this issue if you have any more problems
