### ISSUE TITLE
Placeholder Troubles

### ISSUE THREAD

**Issue by Yuukyboi** [Iridium-Development/IridiumSkyblock#711]
Need Help With The Placeholders, Either I Am So Dumb Or The Documentation Is Outdated.

I Would Just Really Appreciate Help Trying To Get These Working Or Understand How To Actually Use Them.

Plugins I Am Using;
AlonsoLevels, AuctionMaster, AuctionMasterItemDisplay, BetterProfiles, BetterSocial, BuycraftX, ChatInjector, CustomCommands, DisplayName, Economobs, Essentials, EssentialsChat, EssentialsSpawn, ExcellentCrates, FancyCrafting, FastAsyncWorldEdit, GCore, HolographicDisplays, ILibrary, IridiumSkyblock, JSEngine, LevelledMobs, LM_Items, LuckPerms, Multiverse-Core, NBTAPI, NexEngine, PerWorldInventory, PlaceholderAPI, ProtocolLib, PunishGUI, ServersNPC, SimpleScore, SuperMobCoins, TAB, TradeSystem, UberEnchant, UltimateAntiBot, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldGuard

**Comment by Yuukyboi** [comment]
Place Holders I Tried Using;
%iridiumskyblock_island_top_1_rank%
%iridiumskyblock_island_rank%
%iridiumskyblock_island_members%

Places Holders I **Tried** And Worked;
%iridiumskyblock_island_value%
%iridiumskyblock_island_owner%

**Comment by sh0inx** [comment]
documentation is out of date, we're working on updating it, but the placeholders you need are located on our discord for now
