### ISSUE TITLE
Allow players to get/break an end portal frame by shift clicking on it

### ISSUE THREAD

**Issue by Oybekuz** [Iridium-Development/IridiumSkyblock#713]
Every time when players placing end portal wrong, they asking me to fix that. Can you add an option to get back end portal to hands by shift clicking on them (for example)? Like getting an obsidian as lava bucket...

**Comment by sh0inx** [comment]
right click with a wooden pickaxe will now consume the pickaxe and return the end portal frame to the player's inventory 👍
