### ISSUE TITLE
missions stop function after /is delete for all island

### ISSUE THREAD

**Issue by izo276** [Iridium-Development/IridiumSkyblock#720]
**Describe the bug**

**To Reproduce**
1. Do '/is delete'
2. Click on 'yes'
3. Create a new island
4. When u try to do missions they all increase and i cant do it

**Expected behavior**

**Server and Plugin Version**
iridium 4.03
paper 1.19.4

**Screenshots**

**Logs**
If there are error messages in your console, please send them via [this](https://mclo.gs)

**Additional context**
in the database "TeamMissionData" it create a data where "mission_id"=0 and this data is read for all missions

**Comment by PeachesMLG** [comment]
Fixed in 4.0.4
