### ISSUE TITLE
/is delete is not deleting blocks of a persons island.

### ISSUE THREAD

**Issue by WinterPlays123** [Iridium-Development/IridiumSkyblock#721]
**Describe the bug**
When I do /is delete, the persons island is not deleted, the blocks are still there.

**To Reproduce**
1. Create island
2. Delete island
3. Create new island
4. See that old island is still there.

**Expected behavior**
Should delete island and delete the blocks of the island too.

**Server and Plugin Version**
This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)
Plugin Version 4.0.3

**Screenshots**
![image](https://github.com/Iridium-Development/IridiumSkyblock/assets/141188064/a5af24d6-f336-483e-96ec-41d2a3d511e3)
My old island is still here.

**Logs**
No logs.

**Additional context**
N/A

**Comment by PeachesMLG** [comment]
Added option to delete blocks in latest version
