### ISSUE TITLE
that SQL error we've been hunting for like 2 months now

### ISSUE THREAD

**Issue by sh0inx** [Iridium-Development/IridiumSkyblock#725]
**Describe the bug**
the console is spammed with an SQL error, and im unsure of what the cause is, can't replicate it (seems to be on an interval?)

**Server and Plugin Version**
purpur 1.20.1 (2025)
4.0.4

**Logs**
https://mclo.gs/XVNa08r

**Additional context**
default config, attaching db file to discord because github is stupid

**Comment by SeussCZ** [comment]
I have same problem on the latest version.

**Comment by Faun471** [comment]
> I have same problem on the latest version. Do you know which version is stable without errors and warnings?

I'm sorry, but if we do have a version where this issue is fixed, we would've released that version and closed this issue.

Do not comment here unless you can provide information that would help us. Asking if it's fixed is a bit counterproductive, I would say.

**Comment by sh0inx** [comment]
the issues page is for current issues 😔
