### ISSUE TITLE
End Portal Cannot Be Activated

### ISSUE THREAD

**Issue by sh0inx** [Iridium-Development/IridiumSkyblock#727]
**Describe the bug**
End portal frame cannot be activated.

**To Reproduce**
1. use end portal frames to create an end portal
2. activate the end portal frame with an eye of ender

**Expected behavior**
 block state changes to activated end portal frame

**Server and Plugin Version**
purpur 1.20.1 (2025)
4.0.4

**Additional context**
 faun and i both tested this, we think there's something cancelling the block event but we can't figure it out

**Comment by PeachesMLG** [comment]
I cant reproduce this

**Comment by sh0inx** [comment]
thats so strange, i wonder if its a server base issue then? what fork are you using?

**Comment by sh0inx** [comment]
appears to be an issue with an outdated version of purpur, latest version fixes this
