### ISSUE TITLE
Certain Missions Do Not Register

### ISSUE THREAD

**Issue by sh0inx** [Iridium-Development/IridiumSkyblock#728]
**Describe the bug**
depending on the context of the mission, it won't register the task as completed, such as:
- sugarcane 

**To Reproduce**
1. attempt the mission required (i.e. Grow 10 Sugarcane)
2. check `/is missions`
3. notice that the number didn't go up, very unsatisfactory

**Expected behavior**
number go up

**Server and Plugin Version**
- purpur 1.20.1 (2025)
- 4.0.4

**Screenshots**
![image](https://github.com/Iridium-Development/IridiumSkyblock/assets/24255866/3515d647-4fbc-44bb-8ec3-7e8cd30450d2)

**Comment by PeachesMLG** [comment]
Also noticed a similar bug where Wheat will contribute towards the grow mission at every stage of its growth, not just when its finished growing

**Comment by sh0inx** [comment]
im actually in the middle of writing that issue 😂

**Comment by sh0inx** [comment]
im going to test and see if this one is related to the crop being like cactus and growing by adding more blocks instead of changing block state

**Comment by PeachesMLG** [comment]
That would be my suspision aswell... even tho the docs say it applies to sugarcane aswell https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/BlockGrowEvent.html but hey, you know how it is

**Comment by PeachesMLG** [comment]
Also similar issues with Potion Brewing

**Comment by sh0inx** [comment]
yeah i saw that, i hadn't truly tested it so i didn't make an issue

**Comment by PeachesMLG** [comment]
Fixed in https://github.com/Iridium-Development/IridiumTeams/commit/56f6b0af2ced059bd3aa2f8b512656a6062fa2db
