### ISSUE TITLE
Wheat Growth Mission Counted More Than Once

### ISSUE THREAD

**Issue by sh0inx** [Iridium-Development/IridiumSkyblock#729]
**Describe the bug**
when growing wheat, the counter for the growth mission increases more than it should (counting every stage)

**To Reproduce**
1. grow wheat
2. run `/is missions`
3. watch the number go up

**Expected behavior**
number go up relative to crop number

**Server and Plugin Version**
purpur 1.20.1 (2025)
4.0.4

**Screenshots**
1 crop on the island
![image](https://github.com/Iridium-Development/IridiumSkyblock/assets/24255866/5a518d7f-14dd-44c0-92a2-438ae93eebd6)

**Comment by PeachesMLG** [comment]
Fixed in https://github.com/Iridium-Development/IridiumTeams/commit/ee9fe5ec560bdd549031f98b46afeeb99c1209ba
