### ISSUE TITLE
Brewing Missions Do Not Register

### ISSUE THREAD

**Issue by sh0inx** [Iridium-Development/IridiumSkyblock#730]
**Describe the bug**
brewing a potion for a brewing mission does not count towards the mission (it should)

**To Reproduce**
1. make a potion that the mission is supposed to be tracking
2. check ``/is missions`` to see that it hasn't updated

**Expected behavior**
brewed potion counts towards mission progress

**Server and Plugin Version**
- purpur 1.20.1 (2025)
- 4.0.4

**Screenshots**
![image](https://github.com/Iridium-Development/IridiumSkyblock/assets/24255866/eb745ea7-0f27-43ed-929c-586eeea93204)

**Comment by PeachesMLG** [comment]
Fixed in https://github.com/Iridium-Development/IridiumTeams/commit/56f6b0af2ced059bd3aa2f8b512656a6062fa2db
