### ISSUE TITLE
Island Upgrades Bug (I can buy infinite upgrades)

### ISSUE THREAD

**Issue by AuzziPuppy** [Iridium-Development/IridiumSkyblock#731]
Hey,

A player can currently buy infinite upgrades when it should only allow them to buy up to a maximum number. For example, a player can currently buy the island upgrades that I have defined, but even after getting to this page : https://i.imgur.com/hsimknl.png , they can click the icon again and "buy" another level. It DOES take the money, but obviously it doesn't actually do anything. It originally had minlevel: 0 for all of them, but I deleted that line and it is still doing the same thing. This doesnt allow me to add yml files so here is a picture: https://i.imgur.com/3xV9Cep.png

**Comment by sh0inx** [comment]
how much money does it take, the screenshot says the upgrade cost is N/A

**Comment by AuzziPuppy** [comment]
I believe it is taking the most recent upgrade price. So, last size upgrade
(for 150x) is 5,000,000 and it is taking 5m from me even though it says N/A

**Comment by PeachesMLG** [comment]
Fixed in https://github.com/Iridium-Development/IridiumTeams/commit/34bdf653b20b099ce54f151bc70addb932cbcb85
