### ISSUE TITLE
Unable to Strip Logs and Right Click Soil To Make Path

### ISSUE THREAD

**Issue by ImSnipper** [Iridium-Development/IridiumSkyblock#737]
**Describe the bug**
When the island setting "Island Entity Grief" is enabled, player's are unable to right click a log to strip them, and are also unable to right click soil with a shovel to create a path.

**To Reproduce**
1. Enable Island Entity Grief
2. Attempt to strip a log (You will not be able to)
3. Disable Island Entity Grief
4. Attempt to strip a log (You will now be able to)

**Expected behavior**
You should be able to strip logs, and right click soil to create a path.

**Server and Plugin Version**
Current: git-Purpur-2049 (MC: 1.20.1)*
* You are 7 version(s) behind
Download the new version at: https://purpurmc.org/downloads

Iridium Skyblock Version: 4.0.5

**Screenshots**

**Logs**
If there are error messages in your console, please send them via [this](https://mclo.gs)

**Additional context**

**Comment by PeachesMLG** [comment]
Fixed in https://github.com/Iridium-Development/IridiumTeams/commit/0c71b57bb7e0add012979ac0fea0340d6163886c
