### ISSUE TITLE
Grow Missions (Potato, Sugarcane, Bamboo) not tracking progress

### ISSUE THREAD

**Issue by ImSnipper** [Iridium-Development/IridiumSkyblock#738]
**Describe the bug**
Progress for the following GROW missions do not track: Potato, Sugarcane, Bamboo

**To Reproduce**
1. Attempt to plant/harvest potato's, sugarcane, or bamboo
2. Check your island mission progress - you will see the progress does not increase

**Expected behavior**
Should count toward progress.

**Server and Plugin Version**
Current: git-Purpur-2049 (MC: 1.20.1)*
* You are 7 version(s) behind
Download the new version at: https://purpurmc.org/downloads

Iridium Skyblock Version: 4.0.5

**Comment by MertUnverdi** [comment]
Can we see how u set the mission data so like what is material for potato's

**Comment by ImSnipper** [comment]
Yes.

GROW:POTATO:500

**Comment by MertUnverdi** [comment]
![Potato](https://github.com/Iridium-Development/IridiumSkyblock/assets/69310169/7d5fac58-2d71-4570-bedb-9eb9c6f9cf88)
![image](https://github.com/Iridium-Development/IridiumSkyblock/assets/69310169/c5813e81-8f10-4070-ad8f-866fd1c9507f)


Like there Potato is not ageable
We're checking is it ageable, for grow event
Try with potatoes also same for others

**Comment by MertUnverdi** [comment]
Sugarcane must be SUGAR_CANE
Bamboo try with BAMBOO_BLOCK

**Comment by ImSnipper** [comment]
Thank you for the response! 

I have changed POTATO to POTATOES, and CARROT to CARROTS and can confirm that those values are working.

I am currently using SUGAR_CANE for Sugarcane, and BAMBOO_BLOCK for Bamboo. I have tested those values, as well as several player's on my server, and still not working.

**Comment by PeachesMLG** [comment]
Fixed
