### ISSUE TITLE
Commands in missions.yml not implemented

### ISSUE THREAD

**Issue by Zomblard** [Iridium-Development/IridiumSkyblock#739]
**Describe the bug**
commands do not execute in the mission.yml configuration
`commands: [give %player% dirt 1]`
This must be the same for the levelRewards in the configuration.yml line 127 ???

**To Reproduce**
1. Go to mission.yml
2. Add a commands to `commands:`
3. Restart
4. Test
5. Nothing happens when I collect the reward

**Expected behavior**
Let the command be executed :)

**Server and Plugin Version**
1.9.3 > 4.0.5

**Screenshots**
N/A

**Logs**
N/A

**Additional**
Discord discussion : https://discord.com/channels/543944856498864169/592092308514537510/1152568347548979310

**Comment by PeachesMLG** [comment]
Fixed
