### ISSUE TITLE
Certificate fault nexus repo

### ISSUE THREAD

**Issue by tomkeuper** [Iridium-Development/IridiumSkyblock#740]
**Describe the bug**
The nexus repo has a NET::ERR_CERT_DATE_INVALID error
https://nexus.iridiumdevelopment.net/

**Comment by sh0inx** [comment]
you should be able to download the repo you need from the site by navigating to said repo on a browser and then use kts syntax to redirect to the local repo

**Comment by tomkeuper** [comment]
The repo is now completely empty for some reason. maven-releases and maven-snapshots have no components in the repo

**Comment by PeachesMLG** [comment]
yep, im currently working on it, give me a second...

**Comment by PeachesMLG** [comment]
Should be all working now
