### ISSUE TITLE
IridiumSkyblock Menu Item Head Flickering Issue

### ISSUE THREAD

**Issue by RealisticCarrot** [Iridium-Development/IridiumSkyblock#744]
Hello, some of the item heads in parts of the Iridiumskyblock menu are flickering between the default head and the head I set. 

Server Version: paper-1.20.1-195.jar
Plugin Version: 4.0.6

![image](https://github.com/Iridium-Development/IridiumSkyblock/assets/69768653/f964e92e-fc7b-4ae7-b08c-2a48584dcf81)
![image](https://github.com/Iridium-Development/IridiumSkyblock/assets/69768653/a831bf68-e9aa-413f-ac38-dba30f8c8e81)

https://github.com/Iridium-Development/IridiumSkyblock/assets/69768653/059ab41d-0079-47d0-9500-e964fa837e1d

**Comment by sh0inx** [comment]
that is really weird, have you tried lowering your refresh interval at all? im going to see if i can replicate this

**Comment by RealisticThreat** [comment]
Yeah, cause not all of the menu item heads are flickering.

**Comment by sh0inx** [comment]
which menus have this occurrence? we can probably narrow down the cause with that information

**Comment by RealisticThreat** [comment]
The main menu /is menu, the island members menu, and the island bank menu.

**Comment by Faun471** [comment]
your full log file would greatly help

**Comment by RealisticCarrot** [comment]
https://pastebin.com/rEXyDXLw

**Comment by PeachesMLG** [comment]
Im wondering if this is a spigot bug since I was only able to replicate it once I updated

**Comment by sh0inx** [comment]
same thing here, I can't pinpoint a cause tho

**Comment by lvanko** [comment]
Having the same issue.

**Comment by nickynice1** [comment]
same issue here.

**Comment by LucaMezz** [comment]
same issue

**Comment by PeachesMLG** [comment]
Seems to have been introduced in this Paper commit when updating to 1.20.2 https://github.com/PaperMC/paper/commit/e284bb12156fad92767ceadf3d5e57cbc71e5b21

**Comment by sh0inx** [comment]
if thats the case that means spigot wont replicate it, im going to try that rq

**Comment by PeachesMLG** [comment]
Spigot also has the same issues between 1.20.1 and 1.20.2, not sure if its a specific commit that caused it though since I cba to compile it

**Comment by sh0inx** [comment]
i do it dw

**Comment by PeachesMLG** [comment]
Fixed in https://github.com/Iridium-Development/IridiumCore/blob/master/plugin/src/main/java/com/iridium/iridiumcore/utils/ItemStackUtils.java#L141C46-L141C46
