### ISSUE TITLE
Schematic tiles dissapear

### ISSUE THREAD

**Issue by Proodyr** [Iridium-Development/IridiumSkyblock#75]
After making a schematic when i create island some tiles like bamboo or vines are dissapearing or are in wrong direction, screens below.
Server version 1.16.5
Before: 
![image](https://user-images.githubusercontent.com/45770501/119265967-27890f80-bbe9-11eb-841d-54c524e2abff.png)
After
![image](https://user-images.githubusercontent.com/45770501/119265984-34a5fe80-bbe9-11eb-85a8-3439d7600b4b.png)
Before:
![image](https://user-images.githubusercontent.com/45770501/119265999-47203800-bbe9-11eb-8e3e-78182642a92f.png)
After:
![image](https://user-images.githubusercontent.com/45770501/119266015-5b643500-bbe9-11eb-864b-2bd7423bb102.png)

**Comment by SamGamerYT** [comment]
Any news on the fix?

**Comment by Proodyr** [comment]
On the discord is vote for changing Iridium schematic system to world edit schematics

**Comment by PeachesMLG** [comment]
https://github.com/Iridium-Development/IridiumSkyblock/issues/340
