### ISSUE TITLE
Entity Grief Setting Not Toggling Off

### ISSUE THREAD

**Issue by sh0inx** [Iridium-Development/IridiumSkyblock#754]
island settings ``ENTITY GRIEF`` is not toggling correctly

if you chance the island setting for entity griefing to false, the expectation is that mobs such as creepers will not be able to explode and break blocks, but they still can

purpur-2026 (1.20.1)
4.0.6

possibly related to #702 fix

**Comment by sh0inx** [comment]
interesting discovery to be had here
i believe this setting is toggling properly - however, because creepers explode, the TNT setting is overriding how they affect islands
perhaps we should have a check for this?

**Comment by Faun471** [comment]
what other mobs can grief the island?

**Comment by sh0inx** [comment]
I tested silverfish, which is a good a mob as any to test with, but I can do some more testing to determine it

the thing that tips me off to the creeper damage is the fact that the creeper does not explode when the TNT damage is off, it literally disappears like regular TNT does

**Comment by PeachesMLG** [comment]
https://github.com/Iridium-Development/IridiumTeams/commit/50cbdddcb074f080a854864d8d32da338b5d6684
