### ISSUE TITLE
Improper pasting of schematics (Problems Centering)

### ISSUE THREAD

**Issue by yzz17** [Iridium-Development/IridiumSkyblock#766]
**Describe the bug**

the schematics are created with extra offset to the north and west, instead the
south and east is the reverse, I attach photos, I already tried to modify the size
of the parcel to an even and odd number it happens the same, as a comment: 
I think the nature of the world border is "a even number" by default in mojang, 
But I also think it's possible to adjust it

**To Reproduce**

1.Create islands of X size In this example use 101 and 100 
2.Create land of the same theoretical size as the parcel
3.Wasting more than two hours trying to center the land hehe.

**Expected behavior**

properly centered at the time of creating a parcel

**Server and Plugin Version**
purpur [2091](https://api.purpurmc.org/v2/purpur/1.20.2/2091/download)
plugin: [Version 4.0.8](https://www.spigotmc.org/resources/iridium-skyblock-1-13-1-20.62480/update?update=522721)

**Screenshots**
![1](https://github.com/Iridium-Development/IridiumSkyblock/assets/13352920/c866bc63-fc8c-4b47-80c6-97e81df01d7d)
![2](https://github.com/Iridium-Development/IridiumSkyblock/assets/13352920/ddb62d06-bcf8-4a0e-8204-4c5a19b89bd2)

**Logs**

Well I'm experiencing this, but I'm not sure if it's related, it's been happening since I install the plugin, i thing is that it came out when I changed the name of the world, even though I'm not sure about this

https://mclo.gs/wgRHkOc

**Additional context**

Thank you for creating this plugin ! , reporting I hope to help improve it, cheers !,  (It was because a server user told me that the center of an island was wrong, that's why I did this with debug reasons)

**Comment by PeachesMLG** [comment]
Just to confirm, have you added any air blocks in your schematic? when you created the schematic, did you set the positions to be the exact size?

**Comment by yzz17** [comment]
> Just to confirm, have you added any air blocks in your schematic? when you created the schematic, did you set the positions to be the exact size?

It has air, yes, but not on the sides, just on the top ,  I tried everything, to make it exact, I even made a schematic on the space already generated, I even tried removing and adding blocks on some sides, I put a color for each one so it guided me, thinking that it changed the rotation etc, I checked with the count command if it really had a box etc, if I am afraid that for some reason it moves

**Comment by yzz17** [comment]
It doesn't hurt, I think the plugin has an option so that it doesn't leave air when pasting, something like //paste -a, I'm going to try and check again

**Comment by yzz17** [comment]
Well, before I move anything to the settings, I'm going to try this:

I'll create an airless one, a cube, over the space that's generated
![a](https://github.com/Iridium-Development/IridiumSkyblock/assets/13352920/f4bb712a-bda0-4841-a4ce-3efd67d36887)

![b](https://github.com/Iridium-Development/IridiumSkyblock/assets/13352920/f2ad47c2-33a4-46b1-afd3-37488bd5f812)

Now I'm going to stand in the exact center marked with glass

![c](https://github.com/Iridium-Development/IridiumSkyblock/assets/13352920/e72966a0-c146-4b84-b49c-96d1cfbbc10d)

Let's upload the schematic...

 restart server, delete.. create a new island

![d](https://github.com/Iridium-Development/IridiumSkyblock/assets/13352920/51fa4f20-b9aa-4011-b016-63af9a6053a9)
![e](https://github.com/Iridium-Development/IridiumSkyblock/assets/13352920/974f4b76-aa6f-4267-a422-953202fef1f6)

same result, I'll try that option now 

![f](https://github.com/Iridium-Development/IridiumSkyblock/assets/13352920/b7d5fd16-4b11-4a17-b217-85695df727ad)


changed it to false... I was already in True :/, restart server ,delete.. create a new island

![x1](https://github.com/Iridium-Development/IridiumSkyblock/assets/13352920/ad79c8d4-8788-4e06-ab23-4bc5eaebe762)
![x2](https://github.com/Iridium-Development/IridiumSkyblock/assets/13352920/59e018c3-d3d2-45b4-9865-95b496233bcf)

Everything seems, at least on my server, to be unrelated to air blocks

**Comment by yzz17** [comment]
interesting hadn't I noticed, in empty space does the biome change ?

**Comment by yzz17** [comment]
I see you're adjusting the placement before pasting the schematic:  iridiumskyblock/schematics/worldedit.class:

int width = clipboard.getDimensions().getBlockX();
int height = clipboard.getDimensions().getBlockY();
int length = clipboard.getDimensions().getBlockZ();
location.subtract(width / 2.0D, height / 2.0D, length / 2.0D);

This seems to be meant to paste the schematic into the center of the given location. However, if the dimensions of your schematic are odd, this could cause an offset because you're dividing by 2.0D (a decimal number), which could result in a location with fractional coordinates???

You could try rounding these coordinates to the nearest whole number before pasting the schematic. This can be done using Math.round() in Java. myb:

location.subtract(Math.round(width / 2.0D), Math.round(height / 2.0D), Math.round(length / 2.0D));

If the dimensions of the schematics are odd, it could cause them to shift off center. This is because you're dividing the dimensions by 2 to get the center, which can result in a decimal (fractional) number if the dimensions are odd ???

When you try to paste the schematic into a location with fractional coordinates, Minecraft will round these coordinates to the nearest block, which could cause the offset you're observing??

On the other hand, if they are even numbers, could it explain the behavior ?

**Comment by yzz17** [comment]
bump

**Comment by sh0inx** [comment]
dont

**Comment by sh0inx** [comment]
The reason that your schematic is "off-centered" is likely a result of your current island size being set as an even number - the default for the first size level is 50 blocks, which would render the center of the schematic a 2x2 square instead of a singular block, and this is why it appears off-centered. Change it to an odd number.
