### ISSUE TITLE
1.16.5 Arclight - Problem after creating a world

### ISSUE THREAD

**Issue by Eisenbahn** [Iridium-Development/IridiumSkyblock#767]
Ello!
So, i'm using a 1.16.5 Arclight server (Bukkit+forge hybrid)
Apparently the plugin works fine but the server crashes as soon as i create a new /is or regen my IS.

Logs:
https://mclo.gs/7gi0OtK

Peace!

**Comment by sh0inx** [comment]
we dont support arclight or any fabric/forge and bukkit hybrid server, so this is unlikely to be fixed

**Comment by Eisenbahn** [comment]
Oh, sorry. And thank you anyway
Peace
