### ISSUE TITLE
[ BUG ] Console error on new island

### ISSUE THREAD

**Issue by SkyDude0** [Iridium-Development/IridiumSkyblock#768]
**Describe the bug**
Console Error https://pastebin.com/nxJ6CGyv

**To Reproduce**
1. Create new island
2. Check console for the error

**Expected behavior**
No error

**Server and Plugin Version**
SERVER: 1.18.2

PL: 4.0.8

**Comment by sh0inx** [comment]
for some reason the plugin cant load the world
strange, provide your entire log via https://mclo.gs please

**Comment by sh0inx** [comment]
is ``spawn1`` your IridiumSkyblock world? could be related to world name, try renaming it to IridiumSkyblock

**Comment by sh0inx** [comment]
okay then where is your skyblock world? because it only loaded the one world, and iridiumSkyblock cant really do anything without its world loaded

**Comment by sh0inx** [comment]
havent had the time to check on this

**Comment by sh0inx** [comment]
fixed in [IS 774](https://github.com/Iridium-Development/IridiumSkyblock/pull/774)
