### ISSUE TITLE
[ BUG ] Error when i place a block on island ( Eco integration )

### ISSUE THREAD

**Issue by SkyDude0** [Iridium-Development/IridiumSkyblock#769]
**Describe the bug**
Console error with eco plugin. Error: https://pastebin.com/0kbk1tNx

Eco dev say that iridium need to update itself.. so here a reminder.

**To Reproduce**
1. Place a block on island with eco installed
2. Check console

**Expected behavior**
Eco compatibility

**Comment by sh0inx** [comment]
uh, they're wrong lol
v4 of our plugin does not have the ``PermissionType`` class, which is why this error is persisting

tell them to update their API access to v4
https://docs.iridiumdevelopment.net/en/API
