### ISSUE TITLE
When Skyblock is restarted, you lose your progress in your missions.

### ISSUE THREAD

**Issue by Joetorp** [Iridium-Development/IridiumSkyblock#773]

**Comment by Joetorp** [comment]
I didn't understand why, after chopping down numerous trees and having 4 stacks of oak logs, and mining enough cobblestone to have 5 stacks, the /is missions says I have 87 logs and 120 cs.  Then my developer said when the plugin is restarted, skyblock forgets what you have and starts counting from the beginning all over again.

**Comment by sh0inx** [comment]
see [IS 725](https://github.com/Iridium-Development/IridiumSkyblock/issues/725)
