### ISSUE TITLE
(/is create) isn't working

### ISSUE THREAD

**Issue by UpCloudHost** [Iridium-Development/IridiumSkyblock#778]
**Describe the bug**
The command /is create isn't working. When new players
join the server and use /is create the command just doesn't do anything. In the latest version.
It brings up the create and choose template menu but when clicking on a
template it doesn't do anything

**To Reproduce**
1. Create a server
2. download the latest jar of iridium skyblock
3. and start the server.

**Expected behavior**
It was supposed to make a new island
for the player.

**Server and Plugin Version**
![image](https://github.com/Iridium-Development/IridiumSkyblock/assets/102461124/505f25ce-3323-4178-ba76-90d88733ed30)
Server version: 1.20 (17)
with viaversion, and viabackwards.

**Screenshots**
I can't screenshot anything since it just does nothing. Not even a error message in chat

**Logs**
https://mclo.gs/UtKqnNJ

**Additional context**
It was fine until we updated to the latest version from IridiumSkyblock-4.0.3.jar to the latest version.
Before we updated everything worked properly.

**Comment by sh0inx** [comment]
``Cannot read field "money" because "schematicConfig.regenCost" is null``

read the [wiki](https://docs.iridiumdevelopment.net/en/Schematics), you're missing a config section
