### ISSUE TITLE
/is join is not working

### ISSUE THREAD

**Issue by fabiboy123** [Iridium-Development/IridiumSkyblock#781]
i cant do /is join

**To Reproduce**
1. download iridium skyblock  and go in the server 
2. create the island
3. type /is home
4.  See error

expacted behavior:
it was supposed to teleport me to my island

**Server and Plugin Version**
![Minecraft Screenshot 2023 12 30 - 08 23 14 41](https://github.com/Iridium-Development/IridiumSkyblock/assets/155219441/04ccd4b1-0635-4711-919f-b7fe8c8423b3)

version 1.20.4 

**Logs**
logs are: https://mclo.gs/f4UTqw6

**Additional context**
i use spigot bukkit on aternos

**Comment by MertUnverdi** [comment]
Please update your worldedit version [WorldEdit](https://dev.bukkit.org/projects/worldedit/files/4954406/download) [Fawe](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/artifacts/FastAsyncWorldEdit-Bukkit-2.8.5-SNAPSHOT-639.jar)

**Comment by fabiboy123** [comment]
its stil says could not find a safe place to teleport to

**Comment by sh0inx** [comment]
you need to create an island, ``/is create``, and then go to the island, ``/is home``, please use ``/is help`` for more information

**Comment by fabiboy123** [comment]
i do /is home

**Comment by MertUnverdi** [comment]
isn't about iridium its just a version issue from worldedit or paper if you still have this issues please contact us on discord this isn't a issue

**Comment by fabiboy123** [comment]
ok

**Comment by fabiboy123** [comment]
what is your discord?

**Comment by sh0inx** [comment]
its linked on our repo's README, but in case you need it again
[here](https://discord.gg/6HJ73mWE7P)

**Comment by JDChris100** [comment]
Also note we dont support craftbucket, Paper (or a fork) is prefered

**Comment by PeachesMLG** [comment]
Also note we dont support craftbucket, paper or a fork is prefered

**Comment by MertUnverdi** [comment]
(They're already using spigot)
