### ISSUE TITLE
Player Kick from Island while offline

### ISSUE THREAD

**Issue by Barpadzik** [Iridium-Development/IridiumSkyblock#782]
**Describe the bug**
When I try to kick a player off the island and he is offline, an error is displayed in the console and "Internal Error" in the chat

**To Reproduce**
1. Add someone to the island
2. The added person must leave the server
3. Try to kick the added player

**Expected behavior**
That the player will be kicked

**Server and Plugin Version**
The latest Paper 1.20.1 engine
The latest version of the plugin is 4.0.8

**Screenshots**
https://cdn.discordapp.com/attachments/1112701908856078336/1190796258500149288/image.png?ex=65a31a6f&is=6590a56f&hm=dcd9a3720503229f9a26ff9aeb76ad6f2099a60e020ad4d3e7aba2179aca72af&

https://cdn.discordapp.com/attachments/1136768670421499947/1190799136262471690/2023-12-31_00.png?ex=65a31d1e&is=6590a81e&hm=8770f270aa3d3731f35a48ca43939f79c32b94f82b7ff522afbbed43c777fbea&

Don't worry about the translated command, it's not the source of the problem

**Logs**
https://mclo.gs/d9FDtEi

**Additional context**
Need more info or have question? >Discord: Barpad
I will try to look here but it will be much less frequently

**Comment by PeachesMLG** [comment]
https://github.com/Iridium-Development/IridiumTeams/blob/master/src/main/java/com/iridium/iridiumteams/commands/KickCommand.java#L44C16-L44C16

Looks like its because we are casting an offline player to a player here

**Comment by PeachesMLG** [comment]
Fixed in https://github.com/Iridium-Development/IridiumTeams/commit/82378f6b937605fec45c59d0752e1207b0e78549 re open if this still occurs
