### ISSUE TITLE
[BUG] double click to remove active permission

### ISSUE THREAD

**Issue by SkyDude0** [Iridium-Development/IridiumSkyblock#783]
**Describe the bug**
When you try to disable an active permission, you must click on the permission 2 times to disable it.

If permission is disabled by default, work normally.

**To Reproduce**
1. Go to permission setting
2. Click to an active permission 2 time and check the chat

**Expected behavior**
1 click to disable permission

**Server and Plugin Version**
Server version: 1.18.2
Plugin version: 4.0.8

**Comment by PeachesMLG** [comment]
Fixed in https://github.com/Iridium-Development/IridiumSkyblock/commit/6a16f84cdc2e2a0c60d27b807fa58649065f2026
