### ISSUE TITLE
[BUG] Trapdoor permission bug

### ISSUE THREAD

**Issue by SkyDude0** [Iridium-Development/IridiumSkyblock#784]
**Describe the bug**
If i disable all permission, visitator can open tradoors

**To Reproduce**
1. Disable all permission
2. tp to the island and try to open a trapdoor

**Expected behavior**
Trapdoor remain closed

**Server and Plugin Version**
SERVER: 1.18.2
PLUGIN: 4.0.8

**Comment by PeachesMLG** [comment]
Fixed in https://github.com/Iridium-Development/IridiumTeams/commit/98cedf364941a0d8cbc27cb6da2958b1540d07f3
