### ISSUE TITLE
Chat Spam

### ISSUE THREAD

**Issue by Barpadzik** [Iridium-Development/IridiumSkyblock#789]
**Describe the bug**
Iridium message triggers spam

**To Reproduce**
1. Go to someone island without any permission
2. Step on Pressure Plate
3. See Chat

**Expected behavior**
The message will appear once when stepped on

**Server and Plugin Version**
Last Paper 1.20.1 Build / 4.0.8

**Screenshots**
https://imgur.com/a/P5sxt8s

The message is translated into Polish*

**Logs**
No logs in console

**Additional context**
I think not

**Comment by sh0inx** [comment]
I'm going to go ahead and close this, and instead create an issue for a chat overhaul that should hopefully remedy this situation once fully implemented.
