### ISSUE TITLE
Ore Generator Doesnt work With MCMMO'S Mining Skill

### ISSUE THREAD

**Issue by LilCloud420** [Iridium-Development/IridiumSkyblock#801]
**Describe the bug**

**To Reproduce**
1. Using the latest version of the MCMMo plugin and IridiumSkyblock2
2. When you mine ores or stone from the ore generator you do not gain mcmmo mining expierence
3. Tested Other skills in the same world and they work. Mcmmo seems to be reading the ore gen blocks as player placed blocks

**Expected behavior**
Many other servers have it where when you mine blocks from the ore generator the mcmmo skill for mining increases.

**Server and Plugin Version**
Copy and paste the results of `/version` and `/is about`
Version: Current: git-Purpur-2060 (MC: 1.20.1)*
IridiumSkyblock: 4.0.9
MCMMO: 2.1.226-SNAPSHOT

**Comment by sh0inx** [comment]
set ``LavaStoneAndCobbleFarming: false`` in ``experience.yml`` in mcMMO's config (you must be in survival mode)
![image](https://github.com/Iridium-Development/IridiumSkyblock/assets/24255866/ec075b40-6bdc-4919-9a57-7e47012a60ad)
