### ISSUE TITLE
Sometimes, when clicking 'back' in certain menus, they are taking us to another random menu.

### ISSUE THREAD

**Issue by caiobarnes** [Iridium-Development/IridiumSkyblock#806]
**Describe the bug**

**To Reproduce**
1. Go to 'Island Settings'
2. Click on 'Island Member'
3. Click on 'Back'
4. See the error

**Expected behavior**
I expected to return to the settings menu, not to another random menu.

**Server and Plugin Version**
This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)

Plugin Name: IridiumSkyblock
Plugin Version: 4.0.9
Plugin Author: Peaches_MLG
Plugin Donations: [www.patreon.com/Peaches_MLG](http://www.patreon.com/Peaches_MLG)

**Screenshots**
https://youtu.be/EZ84KRX_BsQ

**Logs**
https://mclo.gs

**Additional context**
Now I understand why my players were resetting their islands.

**Comment by sh0inx** [comment]
you need to save your log on that website in order for us to view it

**Comment by sh0inx** [comment]
either way, i cant replicate this, so without your log, there isn't much i can extrapolate from this

**Comment by caiobarnes** [comment]
> either way, i cant replicate this, so without your log, there isn't much i can extrapolate from this

https://mclo.gs/e10kMpc
https://mclo.gs/qHm6GLt
https://mclo.gs/0EniUx2

One person said they think it might be something to do with translation.

**Comment by caiobarnes** [comment]
UP!

**Comment by sh0inx** [comment]
no.

**Comment by PeachesMLG** [comment]
I thought I replied here, I also cant replicate this, are you able to replicate it reliably? Does it always go back to the same gui, Can you replicate this on a server with no other plugins than Iridium?
