### ISSUE TITLE
Plugin crashes...

### ISSUE THREAD

**Issue by herrvogel04** [Iridium-Development/IridiumSkyblock#808]
**When I open the plugin for the first time in my server there is no problem, however when I create an "island" and close my server there is always an error when I try to start my server again.**

1. I start my server with the plugin (first time)
2. When I'm sure everything is normal, I close the server. (This time I'm not creating an "island")
3. I start the server again and everything is fine. There is no error.
4. Afterwards, when my server is open again, I create my "island".
5. When I'm sure everything is normal, I close the server. (This time I have an "island")
6. I start the server again, but the plugin gives an error. Only thing I changed is that I now created an island in the server.

**Server and Plugin Version**
This server is running Paper version git-Paper-423 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 31699ae)

[02:45:02 INFO]: Plugin Name: IridiumSkyblock
[02:45:02 INFO]: Plugin Version: 4.0.9
[02:45:02 INFO]: Plugin Author: Peaches_MLG
[02:45:02 INFO]: Plugin Donations: www.patreon.com/Peaches_MLG

**Screenshots**
![Ekran görüntüsü 2024-02-16 022455](https://github.com/Iridium-Development/IridiumSkyblock/assets/107989410/e24e7e49-f3d8-4784-80cf-3ae38ba98920)

**Logs**
First Run https://mclo.gs/DSuMl5I
Second Run https://mclo.gs/Jdv7EeF

**Comment by sh0inx** [comment]
are you using a custom schematic / which schematic are you using?

**Comment by PeachesMLG** [comment]
Can you reproduce this on a fresh server with default configuration?

**Comment by PeachesMLG** [comment]
Im unable to replicate this... can you dm me on discord and send me a zip of your server? Then ill look into it
