### ISSUE TITLE
/is rewards - Unexpected behaviour

### ISSUE THREAD

**Issue by jappamc** [Iridium-Development/IridiumSkyblock#809]
**Describe the bug**
Multiple players are running into primarily 3 different unexpected behaviours when running /is rewards and attempting to claim.
- The mission reward disappears after an undetermined amount of time before the player can try to claim it from the GUI.
- Mission rewards disappear from the GUI if there are multiple rewards present, and any one of them is claimed.
- Mission rewards do not clear from the /is rewards GUI after claiming, and are able to be claimed infinitely.

**To Reproduce**
I'm unable to replicate this error, it seems to happen quite randomly and through my testing I haven't been able to make it happen for myself intentionally.

You'd expect the mission rewards to be present in the rewards GUI indefinitely until they are claimed, rather than disappearing or exhibiting any of the behaviours I've outlined above.

[16:38:34]: Plugin Name: IridiumSkyblock
[16:38:34]: Plugin Version: 4.0.9
[16:38:34]: Plugin Author: Peaches_MLG
[16:38:34]: Plugin Donations: www.patreon.com/Peaches_MLG

[16:38:43]: IridiumSkyblock version 4.0.9
[16:38:43]: Skyblock Redefined
[16:38:43]: Author: Peaches_MLG

**Screenshots**
![image](https://github.com/Iridium-Development/IridiumSkyblock/assets/160303660/c2be36c8-b4fd-4d0c-b541-8312e329fc86)
![image](https://github.com/Iridium-Development/IridiumSkyblock/assets/160303660/090988c4-a429-4124-8fae-3037d540bb18)

**Logs**
https://mclo.gs/8sf5GtP

**Comment by LordOfTurk** [comment]
Unfortunately, I have the same problem, unfortunately, I look at a player who has made a level 9000 candidate. :/

**Comment by JamieNan** [comment]
I have experienced similar issues, with overlapping rewards disappearing, as well as being able to infinitely claim a reward. I haven't been able to successfully reproduce it and its occurence is random.

**Comment by SwierczKacper** [comment]
"Mission rewards do not clear from the /is rewards GUI after claiming, and are able to be claimed infinitely." - I can confirm this

**Comment by treasurebro123** [comment]
Yup happens with my server as well. Is this mod dead now? This is a game breaking bug and its been almost a year and still "unconfirmed" what lol.

**Comment by treasurebro123** [comment]
Ah I see now. I just noticed that there wasn't an update in the modrinth plugin site for a couple months and seeing that tag threw me off thanks for explaining the situation to me!

**Comment by Annie-I** [comment]
Hello!
I also have this issue with missions that I created. 
Server Plugins (6): CommandItems, Vault, AuraSkills, Essentials, EssentialsSpawn, IridiumSkyblock

Sometimes I can collect reward infinitely and if I don't claim the reward for mission that has several iterations (1, 2, 3, ...), it gets overwritten by next.

Please tell me how I can help, what has to be provided in order for you to be able to fix this.

**Comment by sh0inx** [comment]
@Annie-I we need a reliable way to reproduce these issues.

In order for us to determine what's causing the issue, we need to identify how the problem is occurring, which we can only do if we can replicate the issue.

**Comment by Annie-I** [comment]
What I did to recreate mission reward rewrite issue:

1. Create https://scalacube.com game server with spigot version 1.20
2. Install Vault plugin (version 1.7.3 )
3. Install IridiumSkyblock plugin (version 4.0.9.1)
4. Install EssentialsX plugin (version 2.21.0-dev+129-2ac37d8)
5. Give yourself admin
6. /economy give {username} 1000
7. /is create
8. Choose jungle island
9. Replace server > plugins > IridiumSkyblock > missions.jml content with text from 
[missions.txt](https://github.com/user-attachments/files/17882345/missions.txt)
10. Reboot server
11. Create cobblestone generator
12. Complete "expert miner" missions
13. Check rewards and see that only 3rd reward is collectable [https://www.loom.com/share/549371304d234507a7ed31b32b33f667?sid=e81040cc-f7a7-44c8-b6d8-786ad0d06b98](url)
14. Check money and island crystals and see that indeed only 3rd mission reward was collected

**Comment by PeachesMLG** [comment]
> What I did to recreate mission reward rewrite issue:
> 
>     1. Create https://scalacube.com game server with spigot version 1.20
> 
>     2. Install Vault plugin (version 1.7.3 )
> 
>     3. Install IridiumSkyblock plugin (version 4.0.9.1)
> 
>     4. Install EssentialsX plugin (version 2.21.0-dev+129-2ac37d8)
> 
>     5. Give yourself admin
> 
>     6. /economy give {username} 1000
> 
>     7. /is create
> 
>     8. Choose jungle island
> 
>     9. Replace server > plugins > IridiumSkyblock > missions.yml content with text from
>        [missions.txt](https://github.com/user-attachments/files/17882345/missions.txt)
> 
>     10. Reboot server
> 
>     11. Create cobblestone generator
> 
>     12. Complete "expert miner" missions
> 
>     13. Check rewards and see that only 3rd reward is collectable [https://www.loom.com/share/549371304d234507a7ed31b32b33f667?sid=e81040cc-f7a7-44c8-b6d8-786ad0d06b98](url)
> 
>     14. Check money and island crystals and see that indeed only 3rd mission reward was collected

This is slightly different to the issue being discuessed here, but I have fixed it in https://github.com/Iridium-Development/IridiumSkyblock/pull/930

**Comment by PeachesMLG** [comment]
https://github.com/Iridium-Development/IridiumSkyblock/pull/930 has also patched the other issue

**Comment by PeachesMLG** [comment]
Added some extra safeguards in https://github.com/Iridium-Development/IridiumTeams/commit/a00177c4fa3b7de8754d90775127c81c288d2d53


Potentially if there was an exception or issue in the addContent loop, this would stop it updating the internal cache.

And then there was no check to see if the TeamReward still existed when redeeming it.

So I simply added an if statement to see if the reward still exists and if it doesnt return
