### ISSUE TITLE
PlayerEvents overloading my CPU

### ISSUE THREAD

**Issue by PureSkyblock** [Iridium-Development/IridiumSkyblock#810]
**Describe the bug**
Hello I did a Timings Report on my server: https://timings.aikar.co/dev/?id=589ff0c53b544ca5a3a9e5cae8fbb66a and it showed that the IridiumSkyblockplugin is overloading my server with Player Events from movement to cliking mouse buttons this is unacceptable and it's causing alot of lagg please fix this bug because I can't imagine this being on purpouse.

**To Reproduce**
1. Go to ['...'](https://timings.aikar.co/dev/?id=589ff0c53b544ca5a3a9e5cae8fbb66a)
2. Check all to do with IridiumSkyblock

**Server and Plugin Version**
Copy and paste the results of `/version` and `/is about`
This server is running Paper version git-Paper-426 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ccefdc)

**Screenshots**
![Capture](https://github.com/Iridium-Development/IridiumSkyblock/assets/160346685/6e9f7456-89fa-4ff4-b157-90385573bd5a)

**Logs**
If there are error messages in your console, please send them via [this](https://mclo.gs)

**Additional context**

**Comment by PeachesMLG** [comment]
Is this still an issue? dm me on discord
