### ISSUE TITLE
Island Missions dont reset

### ISSUE THREAD

**Issue by PeachesMLG** [Iridium-Development/IridiumSkyblock#815]
basically there are two types of Daily missions:

1) Where you set slot = null, where it will randomly pick a new one each day
2) Where you specify a slot

#1 reset, #2 dont

So we just need some logic in here: https://github.com/Iridium-Development/IridiumTeams/blob/master/src/main/java/com/iridium/iridiumteams/gui/MissionGUI.java#L55 to see if they have expired or not

**Comment by PeachesMLG** [comment]
Looks like here we filter out where slot == null

https://github.com/Iridium-Development/IridiumTeams/blob/master/src/main/java/com/iridium/iridiumteams/managers/TeamManager.java#L322

I cant remember why at all though, so ill take a quick look over the code and try figure out what past me wrote

**Comment by sh0inx** [comment]
we have an expiration boolean in the team database, i was thinking we could reference that?

**Comment by sh0inx** [comment]
somethin like this [#136](https://github.com/Iridium-Development/IridiumTeams/pull/136)

**Comment by PeachesMLG** [comment]
> we have an expiration boolean in the team database, i was thinking we could reference that?

Yeah, thats what the above references.


Looking at the code we have two different types of missions.

1) If the slot == null it will randomly pick some and fill random ones in the dailySlots - This is the default behaviour

2) If the slot != null, it will always put that mission in that slot.




#1
This gets managed here: https://github.com/Iridium-Development/IridiumTeams/blob/master/src/main/java/com/iridium/iridiumteams/managers/TeamManager.java#L322 You can also see it manage deleting expired ones a few lines down aswell.


#2
I have no idea how this gets managed, lemme look a little more
