### ISSUE TITLE
Possible for setting permissions for nobody's space?

### ISSUE THREAD

**Issue by MaBoCoMark** [Iridium-Development/IridiumSkyblock#826]
### What I want to do:

I'd want to build some decorative stuffs in the void that belongs to nobody.

### Fact that I'm facing now:

I cannot build blocks in the space between 2 skyblocks, even I'm the server OP.
When placing blocks in this kind of space, it shows `You cannot place blocks in this Island` so I'm wondering if it could be done by some permission settings. My request maybe kind of strange ; _ ; .

Still reading the document now xD.
Thanks for any reply.

**Comment by sh0inx** [comment]
``/is bypass``
