### ISSUE TITLE
Singleplayer configuration

### ISSUE THREAD

**Issue by lgrosz** [Iridium-Development/IridiumSkyblock#830]
First off, I want to apologize if this is not the correct place for questions.. but I found this plugin as it seems to be among the most popular Skyblock plugins. I am hosting a few servers for my friends and I wanted to include a Skyblock world where we could each have our own islands and visit each other. Out of the gate I noticed the dependency on the vault/economy mods.. Any pointers for configuring a singleplayer/very-small-server experience. Or am I better off searching for another solution?

**Comment by sh0inx** [comment]
we don't have any specific configs listed for small servers, but we're more than happy to help you with tailoring your config in the discord server - issues isn't really a good place for this because this would be more of a question about using the software than a discussion about the code

**Comment by PeachesMLG** [comment]
https://discord.com/invite/6HJ73mWE7P
