### ISSUE TITLE
How to edit an island as an admin

### ISSUE THREAD

**Issue by MrHawk93** [Iridium-Development/IridiumSkyblock#836]
**Describe the bug**
I have tried with all the permissions, and I have op, how can I open the chests or edit a user's island? I have no possibility to check the chests, or modify any block

**Server and Plugin Version**
Paper 484 1.20.4 - IS 4.0.9

**Comment by sh0inx** [comment]
``/is bypass``

**Comment by MrHawk93** [comment]
You should publish this command since I have not found it anywhere, thank you very much

**Comment by sh0inx** [comment]
guess i must have forgotten to add it to the wiki lol, i'll fix it soon

**Comment by sh0inx** [comment]
added to commands' administration section, see https://docs.iridiumdevelopment.net/e/en/Commands-&-Permissions
