### ISSUE TITLE
Placeholders are bad optimized

### ISSUE THREAD

**Issue by Micosedeunha** [Iridium-Development/IridiumSkyblock#849]
The placeholders, specially %iridiumskyblock_island_level%, are causing a lot of lag in the server. We use this placeholder at menus and TAB.

**Expected behavior**
Expected to be better optimized 

**Server and Plugin Version**
server version 1.20.4
plugin version 4.1.0 BETA

**Screenshots**
(https://spark.lucko.me/omVjIa0DHB)

**Comment by PeachesMLG** [comment]
Is this still an issue on the latest beta?

**Comment by sh0inx** [comment]
we did a lot of placeholder optimization since this issue was posted, so im going to go ahead and close it - if the problem persists, we'll reopen it
