### ISSUE TITLE
Critical menu bad optimization

### ISSUE THREAD

**Issue by leogianfagna** [Iridium-Development/IridiumSkyblock#852]
**Describe the bug**
Using /is visit or /is top  generate a big lag when your server has to many players. 

**To Reproduce**
1. In my case, my server has 500+ islands
2. Use /is top or /is visit and see the /TPSBAR

**Expected behavior**
As I can see, the placeholders in this plugin is bad optimized (#849). This menus has a large amount of placeholders to show stats and, until the player close the GUI, the server keeps lagging. 

**Server and Plugin Version**
IridiumSkyblock version 4.1.0B

**Screenshots**
![image](https://github.com/Iridium-Development/IridiumSkyblock/assets/142264317/58039143-e1bf-47be-84ba-0eb3ac58f9f7)

**Logs**
This is **gold**, a spark report: https://spark.lucko.me/mJWyFq0JM2

**Comment by sh0inx** [comment]
We have a few PRs to fix placeholders, these will hopefully be fixed in the near future (you'll also be able to request a list via ``/is top list <sortType> <amount>``, so there won't be an API delay or item lag)

**Comment by sh0inx** [comment]
nice menu btw

**Comment by leogianfagna** [comment]
> We have a few PRs to fix placeholders, these will hopefully be fixed in the near future (you'll also be able to request a list via `/is top list <sortType> <amount>`, so there won't be an API delay or item lag)

@sh0inx hey I'm léo from discord. I thought that would be good to report this on github as well since is a really important thing. Hoping for the best, :)

**Comment by sh0inx** [comment]
hi leo 👋 thanks for making the PR, it does help! if you're familiar with github and want to see a lil behind the scenes in the discord, i'll go ahead and give you the nerd role (lets you see #nerd-chat and #issues-and-todo in our staff channels)
