### ISSUE TITLE
Stealing obsidians

### ISSUE THREAD

**Issue by Micosedeunha** [Iridium-Development/IridiumSkyblock#854]
**Describe the bug**
Players can fill their bucket with lava when clicking at obsidians placed in others players islands

**To Reproduce**
1. visit someone island where you dont have any permissions.
2. Make sure to set ``obsidianBucket: true``
3. try to get the obsidian with the bucket

**Expected behavior**
Players shouldn't be able to stole obsidian from others players islands

**Server and Plugin Version**
Plugin version 4.1.0B
server version 1.20.4

**Comment by PeachesMLG** [comment]
Just needs a permission check here, ill add it tomorrow

https://github.com/Iridium-Development/IridiumSkyblock/blob/master/src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java#L39

**Comment by sh0inx** [comment]
nu-uh, i do it tonight

**Comment by sh0inx** [comment]
uh this is already fixed in master
https://github.com/Iridium-Development/IridiumSkyblock/blob/4120244698ece555c0c65b200de271be66d25fe5/src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java#L30
