### ISSUE TITLE
Bad optimization when there are a lot of players

### ISSUE THREAD

**Issue by Micosedeunha** [Iridium-Development/IridiumSkyblock#855]
**Describe the bug**
Something bad optimized is causing a lot of lag with 77 members online and 200 connected to proxy

**Server and Plugin Version**
Server version 1.20.4
Plugin version 4.1.0B

**Logs**
https://spark.lucko.me/cKn4wl5FCp

**Additional context**
It seems to be related with island members, it tries to find the location of every member even if they are offline

**Comment by sh0inx** [comment]
The PlayerMoveEventListener only fires when a player moves (shocking, I know), it literally cannot react to offline players. 
However, you have 200 players on your network? That means that for every single player, and every single movement, this event will fire. Not sure how you have your network set up, but the listener cannot be restricted to a single world.
We know that this needs optimizing, though, so this PR will stay open for now.
