### ISSUE TITLE
High timings problem (low tps)

### ISSUE THREAD

**Issue by leogianfagna** [Iridium-Development/IridiumSkyblock#856]
https://spark.lucko.me/eLwJwe50ij

As I can see, this is no related to placeholders as I reported once, and probably is related to the class managers.IslandManager. Is really bad optimized and this spark is catching only ticks above 200.

This spark will help to find a way to optimize this better.
When more players, less TPS.

This is my machine so it's not a hardware problem.
![image](https://github.com/Iridium-Development/IridiumSkyblock/assets/142264317/92e0be9c-01f8-4aec-bb8a-ad5b93dc6420)

**Server and Plugin Version**
server version 1.20.4
plugin version 4.1.0 BETA

**Comment by PeachesMLG** [comment]
I believe this should be fixed in the next update

**Comment by austv** [comment]
> I believe this should be fixed in the next update

![image](https://github.com/Iridium-Development/IridiumSkyblock/assets/66658478/2bebee20-9e4b-4399-acdd-b75c2642ea90)
help please. where can I found this update?

**Comment by sh0inx** [comment]
its not out yet...

**Comment by sh0inx** [comment]
if you want to try the beta, we have it listed on [modrinth](https://modrinth.com/plugin/iridiumskyblock/version/4.1.0B), but you may encounter issues

**Comment by austv** [comment]
I already using 4.1.0 BETA

**Comment by sh0inx** [comment]
then you just wait ✨
