### ISSUE TITLE
XSeries changed their Enchantment enum's so the old configs will break

### ISSUE THREAD

**Issue by PeachesMLG** [Iridium-Development/IridiumSkyblock#865]
AS the title says, potentially same with Potion effects.

We should add a custom (de)serialization of these enums here: https://github.com/Iridium-Development/IridiumCore/blob/master/plugin/src/main/java/com/iridium/iridiumcore/Persist.java

So it uses the `matchXEnchantment` function to parse strings

**Comment by sh0inx** [comment]
this should fix it
https://github.com/Iridium-Development/IridiumCore/pull/106
