### ISSUE TITLE
Can break ender portal frame as a visitor on an island

### ISSUE THREAD

**Issue by Seeting-yt** [Iridium-Development/IridiumSkyblock#889]
### Steps to Reproduce

1. go on an island where you're a visitor
2. go to an end portal frame
3. take a pickaxe 
4. shift left click on the frame

### Expected Behavior

I thought i could'nt break the frame

### Actual Behavior

The frame just dropped and I was able to recover it

### Screenshots

![image](https://github.com/user-attachments/assets/85f7c3e6-c86f-4048-b5f6-d3ec324b7633)
I have not the 'is bypass' activate

![image](https://github.com/user-attachments/assets/18ed22d9-a503-4ecd-acfb-be9628876214)
I shift right click and...

![image](https://github.com/user-attachments/assets/1587aaf5-eae6-479a-9988-30a969798eae)
The frame drop

### Server Software & Minecraft Version

paper 1.20.4

### IridiumSkyblock version

4.1.0B2

**Comment by dlsf** [comment]
And the island owner didn't give you block break permissions, by any chance?

**Comment by PeachesMLG** [comment]
Fixed in https://github.com/Iridium-Development/IridiumSkyblock/pull/931
