### ISSUE TITLE
Mission A reward is being overriden by unrelated mission B

### ISSUE THREAD

**Issue by theRealhoi12** [Iridium-Development/IridiumSkyblock#894]
### Steps to Reproduce

1. Finish mission A
2. View /is rewards but do not claim mission A reward
3. Finish mission B
4. View /is rewards and be baffled that mission B has overwritten A and A is not available anymore :(

### Expected Behavior

I expect reward B to appear next to reward A in the /is rewards menu.

### Actual Behavior

Reward A was overwritten by reward B, resulting in the inability to claim reward A. 

More specifically, mine_Stone 2 was overwritten by mine_MelonPumpkin 1
https://mclo.gs/gDsUZmy

My full missions.yml can be found below
https://mclo.gs/PDcr9fO

### Screenshots

https://github.com/user-attachments/assets/1415d119-19c4-48e9-9ffd-0d3e5dd336bb

### Server Software & Minecraft Version

[20:17:33 INFO]: This server is running Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4) You are running the latest version Previous version: 1.20.6-148-20f5165 (MC: 1.20.6)

### IridiumSkyblock version

[20:17:53 INFO]: Plugin Name: IridiumSkyblock [20:17:53 INFO]: Plugin Version: 4.1.0 [20:17:53 INFO]: Plugin Author: Peaches_MLG [20:17:53 INFO]: Plugin Donations: www.patreon.com/Peaches_MLG

### Additional Comments

![image](https://github.com/user-attachments/assets/5617995a-4564-4c5d-b5f6-d43b8fe0bf3c)
Jar used is a custom jar, yet wolfie mentioned 'we havent updated anything regarding rewards and missions since i did the level overhaul'

**Comment by sh0inx** [comment]
Related to #809

**Comment by PeachesMLG** [comment]
Fixed in https://github.com/Iridium-Development/IridiumSkyblock/pull/930
