### ISSUE TITLE
Island Value Top bug

### ISSUE THREAD

**Issue by RasulbekHak1mov** [Iridium-Development/IridiumSkyblock#917]
### Steps to Reproduce

1. Put a block
2. Look at "/is top value".
3. When it reaches 99900, it goes back to 98700

### Expected Behavior

I used Google Translate

### Actual Behavior

the value does not exceed 100000 on one player's island, when it reaches 99900, it returns to 98700 by itself, but the blocks do not disappear

### Server Software & Minecraft Version

1.20.1

### IridiumSkyblock version

IridiumSkyblock-4.0.9.1

### Additional Comments

the value does not exceed 100000 on one player's island, when it reaches 99900, it returns to 98700 by itself, but the blocks do not disappear

**Comment by RasulbekHak1mov** [comment]
only at the very bottom of the island

**Comment by sh0inx** [comment]
as of stable release (4.0.9.1), value is not counted past y < 0

this has since been fixed in beta and master
