### ISSUE TITLE
Players can place as many item_frame/paintings as they like on island.

### ISSUE THREAD

**Issue by ATCatBoss** [Iridium-Development/IridiumSkyblock#928]
### Steps to Reproduce

game version: 1.20.2
plugin version: 4.0.9.1
use: paper.jar
I don't speak English
please fix it
thanks

### Expected Behavior

Other players can place item_frame and painting on my island

### Actual Behavior

Other players can place item_frame and painting on my island

### Server Software & Minecraft Version

1.20.2

### IridiumSkyblock version

4.0.9.1

**Comment by sh0inx** [comment]
this is fixed with a new permission coming in a future update
