### ISSUE TITLE
Schematic issues with 1.8

### ISSUE THREAD

**Issue by dlsf** [Iridium-Development/IridiumSkyblock#95]
The new schematics cannot be loaded in version 1.8: https://paste.helpch.at/ifomijakez.md

**Comment by dlsf** [comment]
This stack trace was generated using this fix for 1.8.8: https://github.com/Iridium-Development/IridiumSkyblock/pull/96

**Comment by PeachesMLG** [comment]
Should be fixed using this https://github.com/Iridium-Development/IridiumSkyblock/commit/fc918ad513109138a5a9ff79fbf6116bc7812349
